"""
Django settings for application project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
import pymysql
from env import *
pymysql.install_as_MySQLdb()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_int(name: str, default: int) -> int:
    try:
        return int(str(os.environ.get(name, default)).strip())
    except (TypeError, ValueError):
        return default


def _env_float(name: str, default: float) -> float:
    try:
        return float(str(os.environ.get(name, default)).strip())
    except (TypeError, ValueError):
        return default


def _env_str(name: str, default: str = "") -> str:
    value = os.environ.get(name, default)
    return str(value or "").strip()


def _env_bool(name: str, default: bool) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return str(value).strip().lower() not in {'0', 'false', 'no'}


def _env_list(name: str, default: list[str] | None = None) -> list[str]:
    value = os.environ.get(name)
    if value is None:
        return list(default or [])

    items = [
        item.strip()
        for item in str(value).replace('\n', ',').split(',')
        if item.strip()
    ]
    return items or list(default or [])

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!
CURRENT_ENV = _env_str('ZQ_ENV', str(globals().get('ENV', 'dev'))).lower() or 'dev'
DEBUG = _env_bool('DEBUG', CURRENT_ENV != 'prd')
DATABASE_CONN_MAX_AGE = _env_int(
    'DATABASE_CONN_MAX_AGE',
    120 if CURRENT_ENV == 'prd' else 60,
)

# 从环境变量读取，如果没有则使用默认值，但生产环境必须设置
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-y(df$uwnha$0nrkmh5g(ri^=^#3qru3bf8$pw+t6e_wb*op7gj')

# 生产环境检查 SECRET_KEY
if SECRET_KEY == 'django-insecure-y(df$uwnha$0nrkmh5g(ri^=^#3qru3bf8$pw+t6e_wb*op7gj' and not DEBUG:
    raise ValueError("DJANGO_SECRET_KEY must be set in production environment")

ALLOWED_HOSTS = _env_list(
    'ALLOWED_HOSTS',
    ['*'] if DEBUG else ['127.0.0.1', 'localhost', '[::1]'],
)
CSRF_TRUSTED_ORIGINS = _env_list('CSRF_TRUSTED_ORIGINS', [])

# Application definition

INSTALLED_APPS = [
    'django.contrib.staticfiles',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django_celery_beat',
    'django_celery_results',
    'ninja',
    'channels',
    'core',
    'scheduler',
    'apps.failure_mode',
    'apps.performance',
    'apps.project_manager',
    'apps.integration_report',
    'apps.auto_test_report',
    'apps.code_compliance',
    'apps.cmc_contribution',
    'apps.delivery_matrix',
    'apps.code_scan',
    'apps.deepaudit',
    'apps.environment_management',
    'apps.tools',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
            ],
        },
    },
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'common.middleware.DevCorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'common.middleware.SecurityHeadersMiddleware',
    'common.middleware.ApiLoggingMiddleware',
]

ROOT_URLCONF = 'application.urls'
AUTH_USER_MODEL = 'core.User'

WSGI_APPLICATION = 'application.wsgi.application'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# 数据库配置
if DATABASE_TYPE == "MYSQL":
    # Mysql数据库
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "HOST": DATABASE_HOST,
            "PORT": DATABASE_PORT,
            "USER": DATABASE_USER,
            "PASSWORD": DATABASE_PASSWORD,
            "NAME": DATABASE_NAME,
            # 允许通过环境变量复用数据库连接，减少角色页这类多接口页面的建连开销。
            "CONN_MAX_AGE": DATABASE_CONN_MAX_AGE,
            "CONN_HEALTH_CHECKS": True,
            "OPTIONS": {
                "connect_timeout": 10,  # 连接超时
                "read_timeout": 30,     # 读取超时
                "write_timeout": 30,    # 写入超时
            }
        }
    }
elif DATABASE_TYPE == "SQLSERVER":
    # SqlServer数据库
    DATABASES = {
        "default": {
            "ENGINE": "mssql",
            "HOST": DATABASE_HOST,
            "PORT": DATABASE_PORT,
            "USER": DATABASE_USER,
            "PASSWORD": DATABASE_PASSWORD,
            "NAME": DATABASE_NAME,
            # 全局开启事务，绑定的是http请求响应整个过程
            'ATOMIC_REQUESTS': True,
            'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
            },
        }
    }
elif DATABASE_TYPE == "POSTGRESQL":
    # POSTGRESQL
    DATABASES = {
        "default": {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            "HOST": DATABASE_HOST,
            "PORT": DATABASE_PORT,
            "USER": DATABASE_USER,
            "PASSWORD": DATABASE_PASSWORD,
            "NAME": DATABASE_NAME,
            # 全局开启事务，绑定的是http请求响应整个过程
            'ATOMIC_REQUESTS': True,
        },
    }
else:
    # sqlite3 数据库
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
            'OPTIONS': {
                'timeout': 20,
            },
        }
    }

# 数据库路由器配置
# DATABASE_ROUTERS = ['application.db_router.DatabaseRouter']

# Redis 连接配置
REDIS_PORT = int(globals().get('REDIS_PORT', os.environ.get('REDIS_PORT', 6379)))
REDIS_DB = str(globals().get('REDIS_DB', os.environ.get('REDIS_DB', '2')))
REDIS_CELERY_DB = str(globals().get('REDIS_CELERY_DB', os.environ.get('REDIS_CELERY_DB', REDIS_DB)))
REDIS_CHANNEL_DB = str(globals().get('REDIS_CHANNEL_DB', os.environ.get('REDIS_CHANNEL_DB', REDIS_DB)))


def build_redis_url(db: str | int | None = None) -> str:
    auth = f':{REDIS_PASSWORD}@' if REDIS_PASSWORD else ''
    base = f'redis://{auth}{REDIS_HOST}:{REDIS_PORT}'
    if db is None:
        return base
    return f'{base}/{db}'


REDIS_URL = build_redis_url()

# 缓存配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": build_redis_url(REDIS_DB),
        "TIMEOUT": None,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
}

# # ================================================= #
# # ********************* 日志配置 ******************* #
# # ================================================= #

SERVER_LOGS_FILE = os.path.join(BASE_DIR, "logs", "server.log")
ERROR_LOGS_FILE = os.path.join(BASE_DIR, "logs", "error.log")
LOGS_FILE = os.path.join(BASE_DIR, "logs")
if not os.path.exists(os.path.join(BASE_DIR, "logs")):
    os.makedirs(os.path.join(BASE_DIR, "logs"))
DEEPAUDIT_LOG_LEVEL = str(os.environ.get('DEEPAUDIT_LOG_LEVEL', 'DEBUG' if DEBUG else 'INFO')).upper()

# 格式:[2020-04-22 23:33:01][micoservice.apps.ready():16] [INFO] 这是一条日志:
# 格式:[日期][模块.函数名称():行号] [级别] 信息
STANDARD_LOG_FORMAT = (
    "[%(asctime)s][%(name)s.%(funcName)s():%(lineno)d] [%(levelname)s] %(message)s"
)
CONSOLE_LOG_FORMAT = (
    "[%(asctime)s][%(name)s.%(funcName)s():%(lineno)d] [%(levelname)s] %(message)s"
)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {"format": STANDARD_LOG_FORMAT},
        "console": {
            "format": CONSOLE_LOG_FORMAT,
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "file": {
            "format": CONSOLE_LOG_FORMAT,
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "application.logging_handlers.ProcessAwareRotatingFileHandler",
            "filename": SERVER_LOGS_FILE,
            "maxBytes": 1024 * 1024 * 10,  # 100 MB
            "backupCount": 5,  # 最多备份5个
            "formatter": "standard",
            "encoding": "utf-8",
        },
        "error": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": ERROR_LOGS_FILE,
            "maxBytes": 1024 * 1024 * 10,  # 100 MB
            "backupCount": 3,  # 最多备份3个
            "formatter": "standard",
            "encoding": "utf-8",
        },
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "console",
            "filters": ["non_worker_console"],
        },

    },
    "filters": {
        "non_worker_console": {
            "()": "application.logging_handlers.NonWorkerConsoleFilter",
        },
    },
    "loggers": {
        "": {
            "handlers": ["console", "error", "file"],
            "level": "INFO",
        },
        "django": {
            "handlers": ["console", "error", "file"],
            "level": "INFO",
            "propagate": False,
        },
        'django.db.backends': {
            'handlers': ["console", "error", "file"],
            'propagate': False,
            'level': "INFO"
        },
        "apps.deepaudit": {
            "handlers": ["console", "error", "file"],
            "level": DEEPAUDIT_LOG_LEVEL,
            "propagate": False,
        },
        "uvicorn.error": {
            "level": "INFO",
            "handlers": ["console", "error", "file"],
        },
        "uvicorn.access": {
            "handlers": ["console", "error", "file"],
            "level": "INFO"
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# # ================================================= #
# # ******************** Celery 配置 ***************** #
# # ================================================= #
CELERY_BROKER_URL = build_redis_url(REDIS_CELERY_DB)
DJANGO_CELERY_BEAT_TZ_AWARE = False
CELERY_ENABLE_UTC = False
CELERY_WORKER_CONCURRENCY = 2  # 并发数
CELERY_MAX_TASKS_PER_CHILD = 5  # 没个worker最多执行5个任务便自我销毁释放内存
CELERY_TIMEZONE = TIME_ZONE  # celery 时区问题
CELERY_RESULT_BACKEND = 'django-db'  # celery结果存储到数据库中
CELERY_WORKER_HIJACK_ROOT_LOGGER = False

# # ================================================= #
# # ******************** JWT 配置 ***************** #
# # ================================================= #

# 生产环境验证密钥已配置
if not DEBUG:
    if JWT_ACCESS_SECRET_KEY == 'default-access-secret-key-change-in-production':
        raise ValueError("JWT_ACCESS_SECRET_KEY must be set in production environment")
    if JWT_REFRESH_SECRET_KEY == 'default-refresh-secret-key-change-in-production':
        raise ValueError("JWT_REFRESH_SECRET_KEY must be set in production environment")

JWT_ALGORITHM = "HS256"
# 修复：缩短 token 过期时间
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = int(os.environ.get('JWT_ACCESS_TOKEN_EXPIRE_MINUTES', 60 * 24))  # 默认1小时
JWT_REFRESH_TOKEN_EXPIRE_MINUTES = int(os.environ.get('JWT_REFRESH_TOKEN_EXPIRE_MINUTES', 60 * 24 * 7))  # 默认7天


# # ================================================= #
# # ******************** 邮箱 配置 ***************** #
# # ================================================= #

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.163.com'  # 邮件服务器地址
EMAIL_PORT = 25  # 邮件服务器端口
EMAIL_USE_TLS = False  # 是否使用 TLS
EMAIL_HOST_USER = ''  # 发件人邮箱
EMAIL_HOST_PASSWORD = ''  # 发件人邮箱密码

# 接口白名单，不需要授权直接访问 - 修复：缩小范围
API_WHITE_LIST = [
    '/api/core/menu/route/tree',
    '/api/core/menu/get/tree',
    '/api/core/permCode',
    '/api/core/userinfo',
]

API_LOG_ENABLE = True
ENABLE_LOGIN_ANALYSIS_LOG = True
API_LOG_METHODS = 'ALL'
API_MODEL_MAP = {}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# # ================================================= #
# # ******************** 安全配置 ***************** #
# # ================================================= #

# HTTPS 和安全头配置
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
# SameSite Cookie
SESSION_COOKIE_SAMESITE = 'Strict'
CSRF_COOKIE_SAMESITE = 'Strict'

# 安全 HTTP 头
SECURE_HSTS_SECONDS = 31536000  # 1年
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# 防止内容类型嗅探
SECURE_CONTENT_TYPE_NOSNIFF = True

# 点击劫持防护
X_FRAME_OPTIONS = 'DENY'

# ================================================= #
# ********************* 文件存储配置 ******************* #
# ================================================= #

# 文件存储类型: local, oss, minio, azure
FILE_STORAGE_TYPE = 'local'

# 本地存储配置
FILE_STORAGE_LOCAL_PATH = os.path.join(BASE_DIR, 'media', 'file_manager')

# 阿里云OSS配置
OSS_ENDPOINT = ''
OSS_ACCESS_KEY_ID = ''
OSS_ACCESS_KEY_SECRET = ''
OSS_BUCKET_NAME = ''

# Minio配置
MINIO_ENDPOINT = ''
MINIO_ACCESS_KEY = ''
MINIO_SECRET_KEY = ''
MINIO_BUCKET_NAME = ''

# Azure Blob配置
AZURE_ACCOUNT_NAME = ''
AZURE_ACCOUNT_KEY = ''
AZURE_CONTAINER_NAME = ''

# ================================================= #
# ********************* AAD配置 ******************* #
# ================================================= #

# Azure AD 租户ID
AAD_TENANT_ID = ''

# Azure AD 应用程序(客户端) ID
AAD_CLIENT_ID = ''

# 如果需要验证特定的租户，可以设置为具体的租户ID
# AAD_TENANT_ID = 'your-tenant-id'


# ============前端版本 v5为Vben V5，v2位Vben2================== #

# ================================================= #
# ********************* Channels WebSocket配置 ******************* #
# ================================================= #

# ASGI 应用程序
ASGI_APPLICATION = 'application.asgi.application'

# Channels 层配置
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [build_redis_url(REDIS_CHANNEL_DB)],
            "symmetric_encryption_keys": [SECRET_KEY],
        },
    },
}

DEFAULT_PASSWORD = "123456"


def _env_int(name: str, default: int) -> int:
    try:
        return int(str(os.environ.get(name, default)).strip())
    except (TypeError, ValueError):
        return default


def _env_float(name: str, default: float) -> float:
    try:
        return float(str(os.environ.get(name, default)).strip())
    except (TypeError, ValueError):
        return default


def _env_str(name: str, default: str = "") -> str:
    value = os.environ.get(name, default)
    return str(value or "").strip()


def _env_bool(name: str, default: bool) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return str(value).strip().lower() not in {'0', 'false', 'no'}


# 代码合规漏合检测只保留环境相关配置；固定 URL 模板在 client 模块中维护。
CODE_COMPLIANCE_CR_API_TOKEN = _env_str('CODE_COMPLIANCE_CR_API_TOKEN', '')
CODE_COMPLIANCE_CR_API_HEADERS_JSON = _env_str('CODE_COMPLIANCE_CR_API_HEADERS_JSON', '{}')
CODE_COMPLIANCE_CR_FORCE_MOCK = _env_bool('CODE_COMPLIANCE_CR_FORCE_MOCK', False)
# MR 与 CR 可独立开关；未配置时沿用 CR 设置，避免两类采集在开发环境行为不一致。
CODE_COMPLIANCE_MR_FORCE_MOCK = _env_bool('CODE_COMPLIANCE_MR_FORCE_MOCK', CODE_COMPLIANCE_CR_FORCE_MOCK)

# CMC 贡献看板数据湖配置。除日期和分页外，部门查询参数保持固定，避免页面查询直接访问数据湖。
CMC_CONTRIBUTION_API_URL = _env_str('CMC_CONTRIBUTION_API_URL', '')
CMC_CONTRIBUTION_API_TOKEN = _env_str('CMC_CONTRIBUTION_API_TOKEN', '')
CMC_CONTRIBUTION_API_HEADERS_JSON = _env_str('CMC_CONTRIBUTION_API_HEADERS_JSON', '{}')
CMC_CONTRIBUTION_API_TIMEOUT = _env_float('CMC_CONTRIBUTION_API_TIMEOUT', 20)
CMC_CONTRIBUTION_API_VERIFY_SSL = _env_bool('CMC_CONTRIBUTION_API_VERIFY_SSL', True)
CMC_CONTRIBUTION_MAX_PAGES = _env_int('CMC_CONTRIBUTION_MAX_PAGES', 500)

DEEPAUDIT_DOCKER_ENABLED = os.environ.get('DEEPAUDIT_DOCKER_ENABLED', 'true').lower() not in {'0', 'false', 'no'}
DEEPAUDIT_QUEUE = os.environ.get('DEEPAUDIT_QUEUE', 'deepaudit')
AGENT_SKILLS_QUEUE = os.environ.get('AGENT_SKILLS_QUEUE', 'agent_skills')
DEEPAUDIT_TIKTOKEN_MODE = _env_str('DEEPAUDIT_TIKTOKEN_MODE', 'local') or 'local'
DEEPAUDIT_GIT_CLONE_TIMEOUT = _env_int('DEEPAUDIT_GIT_CLONE_TIMEOUT', 1800)
DEEPAUDIT_GIT_LS_REMOTE_TIMEOUT = _env_int('DEEPAUDIT_GIT_LS_REMOTE_TIMEOUT', 120)
DEEPAUDIT_GIT_RETRY_COUNT = _env_int('DEEPAUDIT_GIT_RETRY_COUNT', 3)
DEEPAUDIT_REPO_CACHE_ENABLED = _env_bool('DEEPAUDIT_REPO_CACHE_ENABLED', True)
DEEPAUDIT_REPO_CACHE_TTL_SECONDS = _env_int('DEEPAUDIT_REPO_CACHE_TTL_SECONDS', 1800)
TIKTOKEN_CACHE_DIR = _env_str('TIKTOKEN_CACHE_DIR', '')
DATA_GYM_CACHE_DIR = _env_str('DATA_GYM_CACHE_DIR', '')

# DeepAudit LLM / Embedding 默认配置（作为用户未单独配置时的系统回退）
LLM_PROVIDER = _env_str('LLM_PROVIDER', '')
LLM_MODEL = _env_str('LLM_MODEL', '')
LLM_API_KEY = _env_str('LLM_API_KEY', '')
LLM_BASE_URL = _env_str('LLM_BASE_URL', '')
LLM_TIMEOUT = _env_int('LLM_TIMEOUT', 150)
LLM_TEMPERATURE = _env_float('LLM_TEMPERATURE', 0.1)
LLM_MAX_TOKENS = _env_int('LLM_MAX_TOKENS', 4096)
LLM_FIRST_TOKEN_TIMEOUT = _env_int('LLM_FIRST_TOKEN_TIMEOUT', 30)
LLM_STREAM_TIMEOUT = _env_int('LLM_STREAM_TIMEOUT', 60)
TOOL_TIMEOUT_SECONDS = _env_int('TOOL_TIMEOUT_SECONDS', 60)
SUB_AGENT_TIMEOUT_SECONDS = _env_int('SUB_AGENT_TIMEOUT_SECONDS', 600)
AGENT_TIMEOUT_SECONDS = _env_int('AGENT_TIMEOUT_SECONDS', 1800)
OUTPUT_LANGUAGE = _env_str('OUTPUT_LANGUAGE', 'zh-CN') or 'zh-CN'
CODEHUB_TOKEN = _env_str('CODEHUB_TOKEN', '') or _env_str('GITHUB_TOKEN', '') or _env_str('GITLAB_TOKEN', '') or _env_str('GITEA_TOKEN', '')
GITHUB_TOKEN = _env_str('GITHUB_TOKEN', '')
GITLAB_TOKEN = _env_str('GITLAB_TOKEN', '')
GITEA_TOKEN = _env_str('GITEA_TOKEN', '')
MAX_ANALYZE_FILES = _env_int('MAX_ANALYZE_FILES', 0)
LLM_CONCURRENCY = _env_int('LLM_CONCURRENCY', 3)
LLM_GAP_MS = _env_int('LLM_GAP_MS', 500)

OPENAI_API_KEY = _env_str('OPENAI_API_KEY', '')
OPENAI_BASE_URL = _env_str('OPENAI_BASE_URL', '')
QWEN_API_KEY = _env_str('QWEN_API_KEY', '')
GEMINI_API_KEY = _env_str('GEMINI_API_KEY', '')
CLAUDE_API_KEY = _env_str('CLAUDE_API_KEY', '')
DEEPSEEK_API_KEY = _env_str('DEEPSEEK_API_KEY', '')
ZHIPU_API_KEY = _env_str('ZHIPU_API_KEY', '')
MOONSHOT_API_KEY = _env_str('MOONSHOT_API_KEY', '')
BAIDU_API_KEY = _env_str('BAIDU_API_KEY', '')
MINIMAX_API_KEY = _env_str('MINIMAX_API_KEY', '')
DOUBAO_API_KEY = _env_str('DOUBAO_API_KEY', '')
OLLAMA_BASE_URL = _env_str('OLLAMA_BASE_URL', '')

EMBEDDING_PROVIDER = _env_str('EMBEDDING_PROVIDER', '')
EMBEDDING_MODEL = _env_str('EMBEDDING_MODEL', '')
EMBEDDING_API_KEY = _env_str('EMBEDDING_API_KEY', '')
EMBEDDING_BASE_URL = _env_str('EMBEDDING_BASE_URL', '')
EMBEDDING_DIMENSIONS = _env_int('EMBEDDING_DIMENSIONS', 1536)
EMBEDDING_BATCH_SIZE = _env_int('EMBEDDING_BATCH_SIZE', 100)
EMBEDDING_CONFIG_LOCKED = _env_bool('EMBEDDING_CONFIG_LOCKED', False)
VECTOR_DB_TYPE = _env_str('VECTOR_DB_TYPE', 'chroma') or 'chroma'
CHROMA_PERSIST_DIRECTORY = _env_str('CHROMA_PERSIST_DIRECTORY', os.path.join(BASE_DIR, 'media', 'deepaudit', 'vector_db'))

SSH_CONNECT_TIMEOUT = _env_int('SSH_CONNECT_TIMEOUT', 15)
SSH_TEST_TIMEOUT = _env_int('SSH_TEST_TIMEOUT', 20)
SSH_CLONE_TIMEOUT = _env_int('SSH_CLONE_TIMEOUT', 300)
SSH_CONFIG_PATH = _env_str('SSH_CONFIG_PATH', os.path.join(BASE_DIR, 'media', 'deepaudit', 'ssh'))

SANDBOX_IMAGE = _env_str('SANDBOX_IMAGE', 'python:3.11-slim')
SANDBOX_MEMORY_LIMIT = _env_str('SANDBOX_MEMORY_LIMIT', '512m')
SANDBOX_CPU_LIMIT = _env_float('SANDBOX_CPU_LIMIT', 1.0)
SANDBOX_TIMEOUT_SECONDS = _env_int('SANDBOX_TIMEOUT_SECONDS', 30)
SANDBOX_NETWORK_DISABLED = _env_str('SANDBOX_NETWORK_DISABLED', 'true').lower() not in {'0', 'false', 'no'}
SANDBOX_READ_ONLY_ROOTFS = _env_str('SANDBOX_READ_ONLY_ROOTFS', 'true').lower() not in {'0', 'false', 'no'}
SANDBOX_CAP_DROP = _env_str('SANDBOX_CAP_DROP', 'ALL') or 'ALL'
SANDBOX_NO_NEW_PRIVILEGES = _env_str('SANDBOX_NO_NEW_PRIVILEGES', 'true').lower() not in {'0', 'false', 'no'}

# ================================================= #
# ********************* 阿里云短信服务配置 ******************* #
# ================================================= #

# 阿里云短信服务配置
ALIYUN_SMS_ACCESS_KEY_ID = ""  # 请填入您的AccessKey ID
ALIYUN_SMS_ACCESS_KEY_SECRET = ""  # 请填入您的AccessKey Secret
ALIYUN_SMS_SIGN_NAME = ""  # 请填入您的短信签名
ALIYUN_SMS_TEMPLATE_CODE = ""  # 请填入您的短信模板代码
