# Generated by Django 5.2.7 on 2026-01-24 23:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_user_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('change_id', models.CharField(help_text='ChangeId', max_length=255)),
                ('title', models.CharField(blank=True, help_text='Title', max_length=500, null=True)),
                ('update_time', models.DateTimeField(blank=True, help_text='UpdateTime', null=True)),
                ('url', models.CharField(blank=True, help_text='URL', max_length=500, null=True)),
                ('missing_branches', models.JSONField(default=list, help_text='Missing Branches')),
                ('status', models.IntegerField(choices=[(0, '待处理'), (1, '无风险'), (2, '已修复')], default=0, help_text='状态')),
                ('remark', models.TextField(blank=True, help_text='备注', null=True)),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
                ('user', models.ForeignKey(db_constraint=False, help_text='关联用户', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='core.user')),
            ],
            options={
                'verbose_name': '合规风险记录',
                'verbose_name_plural': '合规风险记录',
                'db_table': 'compliance_record',
                'ordering': ('-update_time',),
            },
        ),
    ]
