# Generated by Django 5.2.7 on 2026-01-27 22:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_compliance', '0001_initial'),
        ('core', '0006_alter_user_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancerecord',
            name='missing_branches',
        ),
        migrations.CreateModel(
            name='ComplianceBranch',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('branch_name', models.CharField(help_text='分支名称', max_length=255)),
                ('status', models.IntegerField(choices=[(0, '待处理'), (1, '无风险'), (2, '已修复')], default=0, help_text='状态')),
                ('remark', models.TextField(blank=True, help_text='备注', null=True)),
                ('record', models.ForeignKey(db_constraint=False, help_text='关联的合规记录', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='code_compliance.compliancerecord')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '合规风险分支',
                'verbose_name_plural': '合规风险分支',
                'db_table': 'compliance_branch',
                'ordering': ('branch_name',),
            },
        ),
    ]
