# Generated by Codex on 2026-09-01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("code_compliance", "0013_repair_contribution_source_identity"),
        ("core", "0009_alter_permission_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancemissingmergerecord",
            name="dts_no",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128, verbose_name="关联DTS单号"),
        ),
        migrations.AddField(
            model_name="compliancemissingmergerecord",
            name="dts_status_name",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="关联DTS状态"),
        ),
        migrations.AddField(
            model_name="compliancemissingmergerecord",
            name="dts_title",
            field=models.CharField(blank=True, default="", max_length=500, verbose_name="关联DTS标题"),
        ),
        migrations.CreateModel(
            name="ComplianceMissingMergeDtsBackfillTask",
            fields=[
                ("id", models.CharField(default=uuid.uuid4, editable=False, help_text="主键ID", max_length=36, primary_key=True, serialize=False)),
                ("sys_create_datetime", models.DateTimeField(auto_now_add=True, db_index=True, help_text="创建时间")),
                ("sys_update_datetime", models.DateTimeField(auto_now=True, db_index=True, help_text="更新时间")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, help_text="是否删除（软删除标识）")),
                ("sort", models.IntegerField(db_index=True, default=0, help_text="排序（数字越大越靠前）")),
                ("status", models.CharField(choices=[("pending", "待执行"), ("running", "执行中"), ("success", "成功"), ("failed", "失败")], db_index=True, default="pending", max_length=32, verbose_name="任务状态")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="结束时间")),
                ("scanned_count", models.IntegerField(default=0, verbose_name="扫描记录数")),
                ("linked_count", models.IntegerField(default=0, verbose_name="关联DTS数")),
                ("status_resolved_count", models.IntegerField(default=0, verbose_name="状态命中数")),
                ("failed_count", models.IntegerField(default=0, verbose_name="失败数")),
                ("diagnostics", models.JSONField(blank=True, default=dict, verbose_name="回填诊断")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="错误信息")),
                ("requested_by", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="missing_merge_dts_backfill_tasks", to="core.user", verbose_name="发起人")),
                ("sys_creator", models.ForeignKey(blank=True, db_constraint=False, help_text="创建人", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to="core.user")),
                ("sys_modifier", models.ForeignKey(blank=True, db_constraint=False, help_text="修改人", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_modified", to="core.user")),
            ],
            options={
                "verbose_name": "漏合风险DTS回填任务",
                "verbose_name_plural": "漏合风险DTS回填任务",
                "db_table": "compliance_missing_merge_dts_backfill_task",
                "ordering": ("-sys_create_datetime",),
                "indexes": [models.Index(fields=["status", "sys_create_datetime"], name="cc_mm_dts_task_status_idx")],
            },
        ),
    ]
