# Generated by Django 5.2.7 on 2026-01-01 23:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_user_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('name', models.CharField(max_length=255, verbose_name='项目名')),
                ('domain', models.CharField(max_length=255, verbose_name='项目领域')),
                ('type', models.CharField(max_length=255, verbose_name='项目类型')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='项目编码')),
                ('is_closed', models.BooleanField(default=False, verbose_name='是否结项')),
                ('repo_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='制品仓号/地址')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('enable_milestone', models.BooleanField(default=True, verbose_name='是否统计里程碑')),
                ('enable_iteration', models.BooleanField(default=True, verbose_name='是否统计迭代数据')),
                ('enable_quality', models.BooleanField(default=True, verbose_name='是否统计代码质量')),
                ('managers', models.ManyToManyField(related_name='managed_projects', to='core.user', verbose_name='项目经理')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '项目管理',
                'verbose_name_plural': '项目管理',
                'db_table': 'pm_project',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('qg1_date', models.DateField(blank=True, null=True, verbose_name='QG1时间')),
                ('qg2_date', models.DateField(blank=True, null=True, verbose_name='QG2时间')),
                ('qg3_date', models.DateField(blank=True, null=True, verbose_name='QG3时间')),
                ('qg4_date', models.DateField(blank=True, null=True, verbose_name='QG4时间')),
                ('qg5_date', models.DateField(blank=True, null=True, verbose_name='QG5时间')),
                ('qg6_date', models.DateField(blank=True, null=True, verbose_name='QG6时间')),
                ('qg7_date', models.DateField(blank=True, null=True, verbose_name='QG7时间')),
                ('qg8_date', models.DateField(blank=True, null=True, verbose_name='QG8时间')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='milestone', to='project_manager.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '里程碑',
                'verbose_name_plural': '里程碑',
                'db_table': 'pm_milestone',
            },
        ),
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('name', models.CharField(max_length=255, verbose_name='迭代名称')),
                ('code', models.CharField(max_length=255, verbose_name='迭代编号')),
                ('start_date', models.DateField(verbose_name='开始时间')),
                ('end_date', models.DateField(verbose_name='结束时间')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否当前迭代')),
                ('is_healthy', models.BooleanField(default=True, verbose_name='是否健康')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='project_manager.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '迭代',
                'verbose_name_plural': '迭代',
                'db_table': 'pm_iteration',
            },
        ),
        migrations.CreateModel(
            name='CodeModule',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('name', models.CharField(max_length=255, verbose_name='模块名')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_code_modules', to='core.user', verbose_name='模块责任人')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_modules', to='project_manager.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '代码质量模块',
                'verbose_name_plural': '代码质量模块',
                'db_table': 'pm_code_module',
            },
        ),
        migrations.CreateModel(
            name='CodeMetric',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('loc', models.IntegerField(verbose_name='代码行数')),
                ('function_count', models.IntegerField(verbose_name='函数个数')),
                ('dangerous_func_count', models.IntegerField(verbose_name='危险函数个数')),
                ('duplication_rate', models.FloatField(verbose_name='重复率')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='project_manager.codemodule', verbose_name='所属模块')),
            ],
            options={
                'verbose_name': '代码质量数据',
                'verbose_name_plural': '代码质量数据',
                'db_table': 'pm_code_metric',
                'unique_together': {('module', 'record_date')},
            },
        ),
        migrations.CreateModel(
            name='IterationMetric',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('req_decomposition_rate', models.FloatField(verbose_name='需求分解率')),
                ('req_drift_rate', models.FloatField(verbose_name='需求游离率')),
                ('req_completion_rate', models.FloatField(verbose_name='需求完成率')),
                ('req_workload', models.FloatField(verbose_name='需求工作量')),
                ('completed_workload', models.FloatField(verbose_name='已完成工作量')),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='project_manager.iteration', verbose_name='所属迭代')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '迭代指标',
                'verbose_name_plural': '迭代指标',
                'db_table': 'pm_iteration_metric',
                'unique_together': {('iteration', 'record_date')},
            },
        ),
    ]
