# Generated by Django 5.2.7 on 2026-01-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='design_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='迭代中台配置 id'),
        ),
        migrations.AddField(
            model_name='project',
            name='sub_teams',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='迭代责任团队'),
        ),
    ]
