# Generated by Django 5.2.7 on 2026-01-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_manager'),
        ('project_manager', '0002_project_design_id_project_sub_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codemodule',
            name='owner',
        ),
        migrations.AddField(
            model_name='codemodule',
            name='owners',
            field=models.ManyToManyField(related_name='owned_code_modules', to='core.user', verbose_name='模块责任人'),
        ),
    ]
