# Generated by Django 5.2.7 on 2026-01-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0003_remove_codemodule_owner_codemodule_owners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codemodule',
            old_name='name',
            new_name='module',
        ),
        migrations.AddField(
            model_name='codemodule',
            name='oem_name',
            field=models.CharField(default='', max_length=255, verbose_name='oem名称'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='codemodule',
            unique_together={('oem_name', 'module')},
        ),
    ]
