# Generated by Django 5.2.7 on 2026-01-07 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0004_rename_name_codemodule_module_codemodule_oem_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='codemodule',
            unique_together={('project', 'oem_name', 'module')},
        ),
    ]
