# Generated by Django 5.2.7 on 2026-01-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0005_alter_codemodule_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='codemetric',
            name='is_clean_code',
            field=models.BooleanField(default=False, verbose_name='是否符合CleanCode标准'),
        ),
    ]
