# Generated by Django 5.2.7 on 2026-01-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_manager'),
        ('project_manager', '0006_codemetric_is_clean_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_projects', to='core.user', verbose_name='收藏该项目的用户'),
        ),
    ]
