# Generated by Django 5.2.7 on 2026-01-12 22:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_manager'),
        ('project_manager', '0007_project_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='di_teams',
            field=models.JSONField(blank=True, null=True, verbose_name='问题单责任团队'),
        ),
        migrations.AddField(
            model_name='project',
            name='enable_dts',
            field=models.BooleanField(default=False, verbose_name='是否统计问题单'),
        ),
        migrations.AddField(
            model_name='project',
            name='ws_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='数据中台配置ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='design_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='设计平台ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='enable_quality',
            field=models.BooleanField(default=False, verbose_name='是否统计代码质量'),
        ),
        migrations.CreateModel(
            name='DtsTeam',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('team_name', models.CharField(max_length=255, verbose_name='责任团队名称')),
                ('parent_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='project_manager.dtsteam', verbose_name='父责任团队')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dts_teams', to='project_manager.project', verbose_name='所属项目')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '问题单责任团队',
                'verbose_name_plural': '问题单责任团队',
                'db_table': 'pm_dts_team',
                'unique_together': {('project', 'team_name')},
            },
        ),
        migrations.CreateModel(
            name='DtsData',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('di', models.FloatField(verbose_name='DI值')),
                ('target_di', models.FloatField(verbose_name='目标DI值')),
                ('today_in_di', models.FloatField(verbose_name='今日流入DI')),
                ('today_out_di', models.FloatField(verbose_name='今日流出DI')),
                ('solve_rate', models.CharField(max_length=20, verbose_name='问题单解决率')),
                ('critical_solve_rate', models.CharField(max_length=20, verbose_name='严重问题单解决率')),
                ('suggestion_num', models.IntegerField(verbose_name='建议问题单个数')),
                ('minor_num', models.IntegerField(verbose_name='提示单个数')),
                ('major_num', models.IntegerField(verbose_name='严重个数')),
                ('fatal_num', models.IntegerField(verbose_name='关键单个数')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='project_manager.dtsteam', verbose_name='所属团队')),
            ],
            options={
                'verbose_name': '问题单数据',
                'verbose_name_plural': '问题单数据',
                'db_table': 'pm_dts_data',
                'unique_together': {('team', 'record_date')},
            },
        ),
    ]
