# Generated by Django 5.2.7 on 2026-01-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0008_project_di_teams_project_enable_dts_project_ws_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iterationmetric',
            name='completed_workload',
        ),
        migrations.RemoveField(
            model_name='iterationmetric',
            name='req_completion_rate',
        ),
        migrations.RemoveField(
            model_name='iterationmetric',
            name='req_decomposition_rate',
        ),
        migrations.RemoveField(
            model_name='iterationmetric',
            name='req_drift_rate',
        ),
        migrations.RemoveField(
            model_name='iterationmetric',
            name='req_workload',
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='a_state_ar_num',
            field=models.IntegerField(default=0, verbose_name='当前置I的ar需求，accept'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='a_state_dr_num',
            field=models.IntegerField(default=0, verbose_name='当前置I的dr需求，accept'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='ar_num',
            field=models.IntegerField(default=0, verbose_name='ar需求数'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='c_state_ar_num',
            field=models.IntegerField(default=0, verbose_name='当前置I的ar需求，complete'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='c_state_dr_num',
            field=models.IntegerField(default=0, verbose_name='当前置I的dr需求，complete'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='d_state_ar_num',
            field=models.IntegerField(default=0, verbose_name='当前置I的ar需求，defined'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='d_state_dr_num',
            field=models.IntegerField(default=0, verbose_name='当前置I的dr需求，defined'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='dr_num',
            field=models.IntegerField(default=0, verbose_name='dr需求数'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='i_state_ar_num',
            field=models.IntegerField(default=0, verbose_name='当前置I的ar需求，Initial'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='i_state_dr_num',
            field=models.IntegerField(default=0, verbose_name='当前置I的dr需求，Initial'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='need_break_but_un_break_dr_num',
            field=models.IntegerField(default=0, verbose_name='需要分解但是未被分解的 dr 数'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='need_break_but_un_break_sr_num',
            field=models.IntegerField(default=0, verbose_name='需要分解但是未被分解的 sr 数'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='need_break_dr_num',
            field=models.IntegerField(default=0, verbose_name='需要分解的 dr 数'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='need_break_sr_num',
            field=models.IntegerField(default=0, verbose_name='需要分解的 sr 数'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='p_state_ar_num',
            field=models.IntegerField(default=0, verbose_name='当前置I的ar需求，processing'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='p_state_dr_num',
            field=models.IntegerField(default=0, verbose_name='当前置I的dr需求，processing'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='sr_num',
            field=models.IntegerField(default=0, verbose_name='sr需求数'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='workload_loc_ar_count',
            field=models.IntegerField(default=0, verbose_name='填写了工作量代码量的 ar 数'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='workload_loc_dr_count',
            field=models.IntegerField(default=0, verbose_name='填写了工作量代码量的 dr 数'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='workload_man_ar_count',
            field=models.IntegerField(default=0, verbose_name='填写了工作量人力信息的 ar 数'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='workload_man_dr_count',
            field=models.IntegerField(default=0, verbose_name='填写了工作量人力信息的 dr 数'),
        ),
    ]
