# Generated by Django 5.2.7 on 2026-01-16 00:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_manager'),
        ('project_manager', '0009_remove_iterationmetric_completed_workload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneQGConfig',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('qg_name', models.CharField(max_length=32, verbose_name='QG点名称')),
                ('target_di', models.FloatField(blank=True, null=True, verbose_name='目标DI值')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qg_configs', to='project_manager.milestone', verbose_name='所属里程碑')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '里程碑QG配置',
                'verbose_name_plural': '里程碑QG配置',
                'db_table': 'pm_milestone_qg_config',
                'unique_together': {('milestone', 'qg_name')},
            },
        ),
        migrations.CreateModel(
            name='MilestoneRiskItem',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('risk_type', models.CharField(choices=[('dts', 'DTS问题单'), ('di', 'DI值超标')], max_length=16, verbose_name='风险类型')),
                ('description', models.TextField(verbose_name='风险描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('confirmed', '已确认'), ('closed', '已关闭')], default='pending', max_length=16, verbose_name='状态')),
                ('manager_confirm_note', models.TextField(blank=True, default='', verbose_name='经理确认备注')),
                ('manager_confirm_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='project_manager.milestoneqgconfig', verbose_name='所属配置')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_risks', to='core.user', verbose_name='确认人')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '里程碑QG风险项',
                'verbose_name_plural': '里程碑QG风险项',
                'db_table': 'pm_milestone_risk_item',
            },
        ),
        migrations.CreateModel(
            name='MilestoneRiskLog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('confirm', '确认'), ('close', '关闭')], max_length=16, verbose_name='操作类型')),
                ('note', models.TextField(blank=True, default='', verbose_name='操作备注')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user', verbose_name='操作人')),
                ('risk_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='project_manager.milestoneriskitem', verbose_name='所属风险项')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '里程碑QG风险日志',
                'verbose_name_plural': '里程碑QG风险日志',
                'db_table': 'pm_milestone_risk_log',
            },
        ),
    ]
