# Generated by Django 5.2.7 on 2026-01-20 22:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_manager'),
        ('project_manager', '0010_milestoneqgconfig_milestoneriskitem_milestonerisklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('project_id', models.CharField(db_index=True, max_length=64, verbose_name='项目ID')),
                ('sync_type', models.CharField(choices=[('iteration', '迭代数据'), ('dts', 'DTS问题单'), ('code_quality', '代码质量'), ('milestone', '里程碑'), ('project', '项目信息')], max_length=32, verbose_name='同步类型')),
                ('status', models.CharField(choices=[('pending', '进行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=16, verbose_name='状态')),
                ('result_summary', models.TextField(blank=True, null=True, verbose_name='结果摘要')),
                ('detail_log', models.TextField(blank=True, null=True, verbose_name='详细日志')),
                ('duration', models.FloatField(default=0.0, verbose_name='耗时(秒)')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '同步日志',
                'verbose_name_plural': '同步日志',
                'db_table': 'pm_sync_log',
                'ordering': ['-sys_create_datetime'],
            },
        ),
    ]
