# Generated by Django 5.2.7 on 2026-02-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0011_synclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestoneqgconfig',
            name='is_delayed',
            field=models.BooleanField(default=False, verbose_name='是否延期'),
        ),
    ]
