# Generated by Django 5.2.7 on 2026-02-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0012_milestoneqgconfig_is_delayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='iterationmetric',
            name='bug_fix_rate',
            field=models.FloatField(default=0.0, verbose_name='缺陷修复率'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='code_coverage_rate',
            field=models.FloatField(default=0.0, verbose_name='代码覆盖率'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='code_review_rate',
            field=models.FloatField(default=0.0, verbose_name='代码评审率'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='test_automation_rate',
            field=models.FloatField(default=0.0, verbose_name='迭代测试自动化率'),
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='test_case_execution_rate',
            field=models.FloatField(default=0.0, verbose_name='用例执行率'),
        ),
    ]
