# Generated by Django 5.2.7 on 2026-02-20 00:00

from django.db import migrations


def ensure_hardware_tables(apps, schema_editor):
    existing_tables = set(schema_editor.connection.introspection.table_names())
    for model_name in ("CdcPlatform", "SmartScreenVersion", "ProjectPhaseConfig"):
        model = apps.get_model("project_manager", model_name)
        table_name = model._meta.db_table
        if table_name not in existing_tables:
            schema_editor.create_model(model)
            existing_tables.add(table_name)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("project_manager", "0014_hardware_config_and_point"),
    ]

    operations = [
        migrations.RunPython(ensure_hardware_tables, migrations.RunPython.noop),
    ]
