# Generated by Django 5.2.7 on 2026-02-26 22:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_announcement_usermessage'),
        ('project_manager', '0016_viuplatform_project_viu_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='codemetric',
            name='clean_code_rate',
            field=models.FloatField(default=0.0, verbose_name='CleanCode达成率'),
        ),
        migrations.AddField(
            model_name='codemetric',
            name='clean_code_total',
            field=models.IntegerField(default=11, verbose_name='CleanCode考核指标总数'),
        ),
        migrations.AddField(
            model_name='codemetric',
            name='raw_tree',
            field=models.JSONField(blank=True, default=dict, verbose_name='原始树数据'),
        ),
        migrations.AddField(
            model_name='codemetric',
            name='summary_metrics',
            field=models.JSONField(blank=True, default=dict, verbose_name='根节点指标汇总'),
        ),
        migrations.AddField(
            model_name='codemetric',
            name='total_node_count',
            field=models.IntegerField(default=0, verbose_name='树节点总数'),
        ),
        migrations.AddField(
            model_name='codemetric',
            name='unachieved_clean_code',
            field=models.JSONField(blank=True, default=list, verbose_name='未达标CleanCode项'),
        ),
        migrations.AddField(
            model_name='codemetric',
            name='version_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='根节点版本名'),
        ),
        migrations.AddField(
            model_name='codemetric',
            name='warning_count',
            field=models.IntegerField(default=0, verbose_name='预警指标数'),
        ),
        migrations.AddField(
            model_name='codemetric',
            name='warning_metrics',
            field=models.JSONField(blank=True, default=list, verbose_name='预警指标列表'),
        ),
        migrations.AddField(
            model_name='codemetric',
            name='warning_node_count',
            field=models.IntegerField(default=0, verbose_name='预警节点数'),
        ),
        migrations.CreateModel(
            name='CodeMetricNode',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('node_key', models.CharField(max_length=512, verbose_name='节点路径键')),
                ('version_name', models.CharField(max_length=255, verbose_name='节点版本名')),
                ('depth', models.IntegerField(default=0, verbose_name='树深度')),
                ('order_index', models.IntegerField(default=0, verbose_name='同层顺序')),
                ('metric_values', models.JSONField(blank=True, default=dict, verbose_name='节点指标值')),
                ('warning_metrics', models.JSONField(blank=True, default=list, verbose_name='预警指标列表')),
                ('warning_count', models.IntegerField(default=0, verbose_name='预警指标数')),
                ('clean_code_rate', models.FloatField(default=0.0, verbose_name='CleanCode达成率')),
                ('clean_code_total', models.IntegerField(default=11, verbose_name='CleanCode考核指标总数')),
                ('unachieved_clean_code', models.JSONField(blank=True, default=list, verbose_name='未达标CleanCode项')),
                ('is_clean_code', models.BooleanField(default=False, verbose_name='是否符合CleanCode标准')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='节点原始数据')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='project_manager.codemetric', verbose_name='所属模块指标快照')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='project_manager.codemetricnode', verbose_name='父节点')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '代码质量树节点',
                'verbose_name_plural': '代码质量树节点',
                'db_table': 'pm_code_metric_node',
                'indexes': [models.Index(fields=['metric', 'depth'], name='idx_pm_cq_node_metric_depth'), models.Index(fields=['metric', 'parent'], name='idx_pm_cq_node_metric_parent')],
                'unique_together': {('metric', 'node_key')},
            },
        ),
    ]
