# Generated by Django 5.2.7 on 2026-02-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0017_codemetric_clean_code_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enable_iteration_quality_metrics',
            field=models.BooleanField(default=False, verbose_name='是否启用迭代代码质量出口指标'),
        ),
        migrations.AddField(
            model_name='project',
            name='iteration_quality_module',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='迭代代码质量模块名'),
        ),
        migrations.AddField(
            model_name='project',
            name='iteration_quality_oem_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='迭代代码质量OEM名称'),
        ),
    ]
