# Generated by Django 5.2.7 on 2026-02-27 19:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_announcement_usermessage"),
        ("project_manager", "0018_project_iteration_quality_metrics"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeNodeOwnerConfig",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="创建时间",
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="更新时间",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="是否删除（软删除标识）",
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="排序（数字越大越靠前）",
                    ),
                ),
                ("node_key", models.CharField(max_length=512, verbose_name="节点路径键")),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_owner_configs",
                        to="project_manager.codemodule",
                        verbose_name="所属模块",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        related_name="owned_code_metric_nodes",
                        to="core.user",
                        verbose_name="节点责任人",
                    ),
                ),
            ],
            options={
                "verbose_name": "代码质量节点责任人配置",
                "verbose_name_plural": "代码质量节点责任人配置",
                "db_table": "pm_code_node_owner_config",
                "indexes": [
                    models.Index(
                        fields=["module"],
                        name="idx_pm_cq_node_owner_module",
                    )
                ],
                "unique_together": {("module", "node_key")},
            },
        ),
    ]
