# Generated by Django 5.2.7 on 2026-03-03 23:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_announcement_usermessage'),
        ('project_manager', '0019_codenodeownerconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viuplatform',
            options={'verbose_name': 'VIU硬件平台', 'verbose_name_plural': 'VIU硬件平台'},
        ),
        migrations.AddField(
            model_name='viuplatform',
            name='configs',
            field=models.JSONField(blank=True, default=list, verbose_name='典配列表'),
        ),
        migrations.AlterField(
            model_name='project',
            name='viu_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='project_manager.viuplatform', verbose_name='VIU硬件平台'),
        ),
        migrations.AlterField(
            model_name='viuplatform',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='VIU硬件平台'),
        ),
        migrations.CreateModel(
            name='IdvpPlatform',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='IDVP软件平台')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': 'IDVP软件平台',
                'verbose_name_plural': 'IDVP软件平台',
                'db_table': 'pm_idvp_platform',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='idvp_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='project_manager.idvpplatform', verbose_name='IDVP软件平台'),
        ),
    ]
