# Generated by Django 5.2.7 on 2026-03-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0020_alter_viuplatform_options_viuplatform_configs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectphaseconfig",
            name="smart_screen_version_ids",
            field=models.JSONField(blank=True, default=list, verbose_name="智慧屏版本ID列表"),
        ),
    ]
