# Generated by Django 5.2.7 on 2026-03-05 04:05

from django.db import migrations, models


def _migrate_smart_screen_versions(apps, schema_editor):
    ProjectPhaseConfig = apps.get_model("project_manager", "ProjectPhaseConfig")
    SmartScreenVersion = apps.get_model("project_manager", "SmartScreenVersion")

    valid_ids = set(
        SmartScreenVersion.objects.filter(is_deleted=False).values_list("id", flat=True),
    )

    for phase in ProjectPhaseConfig.objects.all().iterator():
        normalized_ids: list[str] = []
        seen: set[str] = set()

        for raw_id in (phase.smart_screen_version_ids or []):
            version_id = str(raw_id or "").strip()
            if not version_id or version_id in seen:
                continue
            seen.add(version_id)
            normalized_ids.append(version_id)

        legacy_id = str(phase.smart_screen_version_id or "").strip()
        if legacy_id and legacy_id not in seen:
            normalized_ids.insert(0, legacy_id)
            seen.add(legacy_id)

        target_ids = [item for item in normalized_ids if item in valid_ids]
        if target_ids:
            phase.smart_screen_versions.add(*target_ids)


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0021_projectphaseconfig_smart_screen_version_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectphaseconfig",
            name="smart_screen_versions",
            field=models.ManyToManyField(
                blank=True,
                related_name="phase_configs_v2",
                to="project_manager.smartscreenversion",
                verbose_name="智慧屏版本",
            ),
        ),
        migrations.RunPython(_migrate_smart_screen_versions, _noop_reverse),
        migrations.RemoveField(
            model_name="projectphaseconfig",
            name="smart_screen_version_ids",
        ),
        migrations.RemoveField(
            model_name="projectphaseconfig",
            name="smart_screen_version",
        ),
        migrations.AlterField(
            model_name="projectphaseconfig",
            name="smart_screen_versions",
            field=models.ManyToManyField(
                blank=True,
                related_name="phase_configs",
                to="project_manager.smartscreenversion",
                verbose_name="智慧屏版本",
            ),
        ),
    ]
