# Generated by Django 5.2.7 on 2026-03-16 08:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_plgroup'),
        ('project_manager', '0022_projectphaseconfig_smart_screen_versions_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='version_c',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DTS版本号'),
        ),
        migrations.CreateModel(
            name='DtsExtension',
            fields=[
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('defect_no', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='DTS单号')),
                ('qa_category', models.CharField(blank=True, max_length=64, null=True, verbose_name='问题大类')),
                ('is_downstream', models.CharField(blank=True, max_length=8, null=True, verbose_name='是否下游产品质量问题')),
                ('process_quality_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='产品过程质量问题分类')),
                ('need_dev_analyze', models.CharField(blank=True, max_length=8, null=True, verbose_name='是否需要开发分析引入原因')),
                ('need_test_analyze', models.CharField(blank=True, max_length=8, null=True, verbose_name='是否需要测试分析漏测')),
                ('is_dev_analyzed', models.CharField(blank=True, max_length=8, null=True, verbose_name='开发分析是否完成')),
                ('is_test_analyzed', models.CharField(blank=True, max_length=8, null=True, verbose_name='测试分析是否完成')),
                ('qa_remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('dev_sub_category', models.JSONField(blank=True, default=list, verbose_name='问题小类')),
                ('dev_reason', models.TextField(blank=True, null=True, verbose_name='问题原因')),
                ('dev_intro_reason', models.TextField(blank=True, null=True, verbose_name='引入原因')),
                ('dev_improvements', models.JSONField(blank=True, default=list, verbose_name='开发改进措施')),
                ('dev_non_base_desc', models.CharField(blank=True, max_length=128, null=True, verbose_name='非底软问题说明')),
                ('dev_asset_link', models.CharField(blank=True, max_length=512, null=True, verbose_name='落地资产链接(开发)')),
                ('dev_status', models.CharField(blank=True, max_length=32, null=True, verbose_name='开发改进措施状态')),
                ('test_feature', models.CharField(blank=True, max_length=255, null=True, verbose_name='特效/功能')),
                ('test_miss_reason', models.JSONField(blank=True, default=list, verbose_name='漏测原因')),
                ('test_standard_desc', models.TextField(blank=True, null=True, verbose_name='规范问题描述')),
                ('test_improvements', models.JSONField(blank=True, default=list, verbose_name='测试改进措施')),
                ('test_non_test_desc', models.TextField(blank=True, null=True, verbose_name='非测试问题说明')),
                ('test_asset_link', models.CharField(blank=True, max_length=512, null=True, verbose_name='落地资产链接(测试)')),
                ('test_status', models.CharField(blank=True, max_length=32, null=True, verbose_name='漏测改进措施状态')),
                ('dev_owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dts_dev_extensions', to='core.user', verbose_name='开发责任人')),
                ('pl_group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dts_extensions', to='core.plgroup', verbose_name='责任PL组')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
                ('test_owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dts_test_extensions', to='core.user', verbose_name='测试责任人')),
            ],
            options={
                'verbose_name': 'DTS拓展数据',
                'verbose_name_plural': 'DTS拓展数据',
                'db_table': 'pm_dts_extension',
            },
        ),
        migrations.CreateModel(
            name='DtsDefectProjectLink',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('defect_no', models.CharField(db_index=True, max_length=64, verbose_name='DTS单号')),
                ('team_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='命中团队')),
                ('version_c', models.CharField(blank=True, max_length=255, null=True, verbose_name='命中版本')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最近命中时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dts_defect_links', to='project_manager.project', verbose_name='项目')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': 'DTS问题单项目关联',
                'verbose_name_plural': 'DTS问题单项目关联',
                'db_table': 'pm_dts_defect_project_link',
                'indexes': [models.Index(fields=['defect_no'], name='pm_dts_defe_defect__05b0d2_idx'), models.Index(fields=['project', 'last_seen_at'], name='pm_dts_defe_project_11efd1_idx')],
                'constraints': [models.UniqueConstraint(fields=('defect_no', 'project'), name='uniq_pm_dts_defect_project')],
            },
        ),
    ]
