# Generated by Django 5.2.7 on 2026-03-17

from django.db import migrations


def seed_dts_dicts(apps, schema_editor):
    Dict = apps.get_model("core", "Dict")
    DictItem = apps.get_model("core", "DictItem")

    dict_groups = [
        {
            "name": "是否",
            "code": "yes_no",
            "remark": "通用字典-是否",
            "items": ["是", "否"],
        },
        {
            "name": "DTS-QA问题大类",
            "code": "dts_qa_category",
            "remark": "DTS统计模块-QA问题大类",
            "items": [
                "需求理解偏差",
                "技术方案问题",
                "设计实现问题",
                "代码质量问题",
                "联调集成问题",
                "测试遗漏",
                "配置环境问题",
                "数据问题",
                "三方依赖问题",
                "其他",
            ],
        },
        {
            "name": "DTS-过程质量分类",
            "code": "dts_process_quality_type",
            "remark": "DTS统计模块-过程质量分类",
            "items": [
                "需求评审不足",
                "技术方案缺失",
                "设计评审不足",
                "开发自测不足",
                "测试用例覆盖不足",
                "回归验证不足",
                "变更影响分析不足",
                "发布流程问题",
                "配置管理问题",
                "其他",
            ],
        },
        {
            "name": "DTS-开发问题小类",
            "code": "dts_dev_sub_category",
            "remark": "DTS统计模块-开发问题小类",
            "items": [
                "空指针/异常处理",
                "边界条件遗漏",
                "状态机/时序问题",
                "并发/竞态问题",
                "配置错误",
                "接口兼容性问题",
                "数据处理错误",
                "资源释放/泄漏",
                "容错性不足",
                "日志/监控缺失",
                "其他",
            ],
        },
        {
            "name": "DTS-漏测原因",
            "code": "dts_test_miss_reason",
            "remark": "DTS统计模块-漏测原因",
            "items": [
                "用例未覆盖",
                "场景遗漏",
                "边界值遗漏",
                "组合场景遗漏",
                "回归范围不足",
                "环境限制未覆盖",
                "数据构造不足",
                "自动化缺失",
                "执行遗漏",
                "其他",
            ],
        },
        {
            "name": "DTS-改进状态",
            "code": "dts_action_status",
            "remark": "DTS统计模块-改进状态（开发/测试共用）",
            "items": [
                "待分析",
                "分析中",
                "待实施",
                "实施中",
                "待验证",
                "已完成",
                "长期跟踪",
                "不适用",
            ],
        },
    ]

    for group in dict_groups:
        dict_obj, _ = Dict.objects.update_or_create(
            code=group["code"],
            defaults={
                "name": group["name"],
                "status": True,
                "remark": group["remark"],
            },
        )

        items = group.get("items") or []
        total = len(items)
        for index, item_label in enumerate(items):
            label = str(item_label or "").strip()
            if not label:
                continue
            sort_value = (total - index) * 10
            DictItem.objects.update_or_create(
                dict=dict_obj,
                value=label,
                defaults={
                    "label": label,
                    "status": True,
                    "sort": sort_value,
                    "remark": f"{group['name']}选项",
                },
            )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_plgroup"),
        ("project_manager", "0023_project_version_c_dtsextension_dtsdefectprojectlink"),
    ]

    operations = [
        migrations.RunPython(seed_dts_dicts, migrations.RunPython.noop),
    ]

