# Generated by Django 5.2.7 on 2026-03-17

from django.db import migrations, models


def migrate_dev_non_base_desc_to_list(apps, schema_editor):
    """
    dev_non_base_desc: varchar -> json(list)

    历史数据兼容：将非空字符串迁移为 ["<old_value>"]，空/NULL 迁移为 []。
    """

    DtsExtension = apps.get_model("project_manager", "DtsExtension")
    for item in DtsExtension.objects.all().only("defect_no", "dev_non_base_desc"):
        raw = getattr(item, "dev_non_base_desc", None)
        text = str(raw or "").strip()
        item.dev_non_base_desc_v2 = [text] if text else []
        item.save(update_fields=["dev_non_base_desc_v2"])


def seed_dts_extension_dicts(apps, schema_editor):
    Dict = apps.get_model("core", "Dict")
    DictItem = apps.get_model("core", "DictItem")

    dict_groups = [
        {
            "name": "DTS-非底软问题说明",
            "code": "dts_dev_non_base_desc",
            "remark": "DTS统计模块-非底软问题说明（开发填报，多选）",
            "items": [
                "硬件/平台原因",
                "三方依赖原因",
                "配置/环境原因",
                "需求/产品原因",
                "数据原因",
                "其他",
            ],
        },
    ]

    for group in dict_groups:
        dict_obj, _ = Dict.objects.update_or_create(
            code=group["code"],
            defaults={
                "name": group["name"],
                "status": True,
                "remark": group["remark"],
            },
        )

        items = group.get("items") or []
        total = len(items)
        for index, item_label in enumerate(items):
            label = str(item_label or "").strip()
            if not label:
                continue
            sort_value = (total - index) * 10
            DictItem.objects.update_or_create(
                dict=dict_obj,
                value=label,
                defaults={
                    "label": label,
                    "status": True,
                    "sort": sort_value,
                    "remark": f"{group['name']}选项",
                },
            )

    # dev_status / test_status: open / close only.
    action_dict, _ = Dict.objects.update_or_create(
        code="dts_action_status",
        defaults={
            "name": "DTS-改进状态",
            "status": True,
            "remark": "DTS统计模块-改进状态（开发/测试共用，open/close）",
        },
    )

    desired_values = ["open", "close"]
    for idx, value in enumerate(desired_values):
        sort_value = (len(desired_values) - idx) * 10
        DictItem.objects.update_or_create(
            dict=action_dict,
            value=value,
            defaults={
                "label": value,
                "status": True,
                "sort": sort_value,
                "remark": "DTS-改进状态选项",
            },
        )

    DictItem.objects.filter(dict=action_dict).exclude(value__in=desired_values).update(
        status=False
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_plgroup"),
        ("project_manager", "0024_seed_dts_dicts"),
    ]

    operations = [
        migrations.AddField(
            model_name="dtsextension",
            name="dev_non_base_desc_v2",
            field=models.JSONField(blank=True, default=list, verbose_name="非底软问题说明"),
        ),
        migrations.RunPython(
            migrate_dev_non_base_desc_to_list, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="dtsextension",
            name="dev_non_base_desc",
        ),
        migrations.RenameField(
            model_name="dtsextension",
            old_name="dev_non_base_desc_v2",
            new_name="dev_non_base_desc",
        ),
        migrations.RunPython(seed_dts_extension_dicts, migrations.RunPython.noop),
    ]

