# Generated by Django 5.2.7 on 2026-03-19 22:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_plgroup'),
        ('project_manager', '0025_dts_extension_dev_non_base_desc_dicts'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementWorkspaceSnapshot',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='快照日期')),
                ('scope', models.CharField(db_index=True, max_length=64, verbose_name='统计范围')),
                ('generated_at', models.DateTimeField(db_index=True, verbose_name='生成时间')),
                ('project_count', models.IntegerField(default=0, verbose_name='项目数')),
                ('requirement_count', models.IntegerField(default=0, verbose_name='需求数')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='快照载荷')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '工作台需求交付快照',
                'verbose_name_plural': '工作台需求交付快照',
                'db_table': 'pm_requirement_workspace_snapshot',
                'indexes': [models.Index(fields=['scope', 'snapshot_date'], name='pm_requirem_scope_004538_idx'), models.Index(fields=['scope', 'generated_at'], name='pm_requirem_scope_caeccc_idx')],
                'constraints': [models.UniqueConstraint(fields=('snapshot_date', 'scope'), name='uniq_pm_requirement_workspace_snapshot_scope_date')],
            },
        ),
    ]
