# Generated by Django 5.2.7 on 2026-03-20 07:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_plgroup'),
        ('project_manager', '0026_requirementworkspacesnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementBoardFilterPreference',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='筛选条件')),
                ('last_applied_at', models.DateTimeField(db_index=True, verbose_name='最后应用时间')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_board_filter_preferences', to='core.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '需求看板筛选偏好',
                'verbose_name_plural': '需求看板筛选偏好',
                'db_table': 'pm_requirement_board_filter_preference',
                'constraints': [models.UniqueConstraint(fields=('user',), name='uniq_pm_requirement_board_filter_preference_user')],
            },
        ),
    ]
