# Generated by Django 5.2.7 on 2026-03-21 05:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_plgroup'),
        ('project_manager', '0027_requirementboardfilterpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementBoardQueryTask',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, verbose_name='查询指纹')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='筛选条件')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], db_index=True, default='pending', max_length=16, verbose_name='状态')),
                ('message', models.CharField(blank=True, default='', max_length=255, verbose_name='任务提示')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('progress', models.IntegerField(default=0, verbose_name='进度')),
                ('scanned_pages', models.IntegerField(default=0, verbose_name='已扫描页数')),
                ('total_pages', models.IntegerField(default=0, verbose_name='总页数')),
                ('matched_count', models.IntegerField(default=0, verbose_name='匹配需求数')),
                ('result_cache_key', models.CharField(blank=True, default='', max_length=255, verbose_name='结果缓存键')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='结束时间')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_board_query_tasks', to='core.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '需求看板查询准备任务',
                'verbose_name_plural': '需求看板查询准备任务',
                'db_table': 'pm_requirement_board_query_task',
                'indexes': [models.Index(fields=['user', 'fingerprint', 'status'], name='pm_requirem_user_id_7deb78_idx'), models.Index(fields=['user', 'sys_create_datetime'], name='pm_requirem_user_id_ed6008_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequirementWorkspaceRefreshTask',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('scope', models.CharField(db_index=True, max_length=64, verbose_name='统计范围')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], db_index=True, default='pending', max_length=16, verbose_name='状态')),
                ('message', models.CharField(blank=True, default='', max_length=255, verbose_name='任务提示')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='结束时间')),
                ('snapshot_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='快照日期')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirement_workspace_refresh_tasks', to='core.user', verbose_name='发起人')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refresh_tasks', to='project_manager.requirementworkspacesnapshot', verbose_name='关联快照')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '工作台需求交付刷新任务',
                'verbose_name_plural': '工作台需求交付刷新任务',
                'db_table': 'pm_requirement_workspace_refresh_task',
                'indexes': [models.Index(fields=['scope', 'status', 'sys_create_datetime'], name='pm_requirem_scope_6ea54d_idx'), models.Index(fields=['requested_by', 'sys_create_datetime'], name='pm_requirem_request_a8b7c9_idx')],
            },
        ),
    ]
