# Generated by Django 5.2.7 on 2026-03-24 02:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_plgroup"),
        ("project_manager", "0028_requirementboardquerytask_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailureMode",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                (
                    "brief",
                    models.CharField(max_length=255, verbose_name="故障模式简述"),
                ),
                (
                    "subsystem",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="子系统"
                    ),
                ),
                (
                    "module_name",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="模块"
                    ),
                ),
                (
                    "chips",
                    models.JSONField(blank=True, default=list, verbose_name="芯片"),
                ),
                (
                    "fault_categories",
                    models.JSONField(blank=True, default=list, verbose_name="故障类别"),
                ),
                (
                    "symptoms",
                    models.JSONField(blank=True, default=list, verbose_name="故障现象"),
                ),
                (
                    "effect_html",
                    models.TextField(blank=True, default="", verbose_name="故障影响"),
                ),
                (
                    "root_cause_html",
                    models.TextField(blank=True, default="", verbose_name="故障根因"),
                ),
                (
                    "functional_safety_level",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="功能安全等级",
                    ),
                ),
                (
                    "occurrence_frequency",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="故障发生频度",
                    ),
                ),
                (
                    "detectability",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="故障可探测度",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="严重程度"
                    ),
                ),
                (
                    "related_dts_nos",
                    models.JSONField(
                        blank=True, default=list, verbose_name="关联问题单"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="状态"
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="failure_modes",
                        to="core.user",
                        verbose_name="作者",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "故障模式",
                "verbose_name_plural": "故障模式",
                "db_table": "pm_failure_mode",
            },
        ),
        migrations.CreateModel(
            name="HandlingMeasure",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                (
                    "measure_category",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="措施类别"
                    ),
                ),
                ("measure", models.CharField(max_length=255, verbose_name="处理措施")),
                (
                    "measure_detail_html",
                    models.TextField(
                        blank=True, default="", verbose_name="处理措施详情"
                    ),
                ),
                (
                    "measure_effect",
                    models.TextField(blank=True, default="", verbose_name="措施影响"),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="failure_handling_measures",
                        to="core.user",
                        verbose_name="设计责任人",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "故障处理措施",
                "verbose_name_plural": "故障处理措施",
                "db_table": "pm_failure_handling_measure",
            },
        ),
        migrations.CreateModel(
            name="FailureModeHandlingMeasureRel",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                ("order_index", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "failure_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handling_measure_relations",
                        to="project_manager.failuremode",
                        verbose_name="故障模式",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
                (
                    "handling_measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failure_mode_relations",
                        to="project_manager.handlingmeasure",
                        verbose_name="故障处理措施",
                    ),
                ),
            ],
            options={
                "verbose_name": "故障模式-故障处理措施关联",
                "verbose_name_plural": "故障模式-故障处理措施关联",
                "db_table": "pm_failure_mode_measure_rel",
            },
        ),
        migrations.CreateModel(
            name="HuatuoDiagnosis",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                ("description", models.TextField(verbose_name="诊断方案描述")),
                (
                    "owners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="failure_huatuo_diagnoses",
                        to="core.user",
                        verbose_name="设计责任人",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "华佗诊断方案",
                "verbose_name_plural": "华佗诊断方案",
                "db_table": "pm_failure_huatuo_diagnosis",
            },
        ),
        migrations.CreateModel(
            name="FailureModeHuatuoDiagnosisRel",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                ("order_index", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "failure_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="huatuo_diagnosis_relations",
                        to="project_manager.failuremode",
                        verbose_name="故障模式",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
                (
                    "huatuo_diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failure_mode_relations",
                        to="project_manager.huatuodiagnosis",
                        verbose_name="华佗诊断方案",
                    ),
                ),
            ],
            options={
                "verbose_name": "故障模式-华佗诊断方案关联",
                "verbose_name_plural": "故障模式-华佗诊断方案关联",
                "db_table": "pm_failure_mode_huatuo_rel",
            },
        ),
        migrations.CreateModel(
            name="InterceptionStrategy",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                (
                    "interception_item",
                    models.CharField(max_length=255, verbose_name="产线拦截项"),
                ),
                (
                    "version_detection_html",
                    models.TextField(
                        blank=True, default="", verbose_name="产线版本检测方案"
                    ),
                ),
                (
                    "station",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="工位"
                    ),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="failure_interception_strategies",
                        to="core.user",
                        verbose_name="设计责任人",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "产线拦截策略",
                "verbose_name_plural": "产线拦截策略",
                "db_table": "pm_failure_interception_strategy",
            },
        ),
        migrations.CreateModel(
            name="FailureModeInterceptionStrategyRel",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                ("order_index", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "failure_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interception_relations",
                        to="project_manager.failuremode",
                        verbose_name="故障模式",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
                (
                    "interception_strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failure_mode_relations",
                        to="project_manager.interceptionstrategy",
                        verbose_name="产线拦截策略",
                    ),
                ),
            ],
            options={
                "verbose_name": "故障模式-产线拦截策略关联",
                "verbose_name_plural": "故障模式-产线拦截策略关联",
                "db_table": "pm_failure_mode_interception_rel",
            },
        ),
        migrations.CreateModel(
            name="ObservationMethod",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                (
                    "monitor_type",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="维测类型"
                    ),
                ),
                (
                    "log_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="日志ID"
                    ),
                ),
                (
                    "log_keyword",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="日志关键词"
                    ),
                ),
                (
                    "log_path",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="日志获取路径",
                    ),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="failure_observation_methods",
                        to="core.user",
                        verbose_name="设计责任人",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "维测手段",
                "verbose_name_plural": "维测手段",
                "db_table": "pm_failure_observation_method",
            },
        ),
        migrations.CreateModel(
            name="FailureModeObservationMethodRel",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                ("order_index", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "failure_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observation_method_relations",
                        to="project_manager.failuremode",
                        verbose_name="故障模式",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
                (
                    "observation_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failure_mode_relations",
                        to="project_manager.observationmethod",
                        verbose_name="维测手段",
                    ),
                ),
            ],
            options={
                "verbose_name": "故障模式-维测手段关联",
                "verbose_name_plural": "故障模式-维测手段关联",
                "db_table": "pm_failure_mode_observation_rel",
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                (
                    "brief",
                    models.CharField(max_length=255, verbose_name="测试用例简述"),
                ),
                (
                    "detail_html",
                    models.TextField(
                        blank=True, default="", verbose_name="测试用例详情"
                    ),
                ),
                (
                    "cida_link",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="CIDA链接"
                    ),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="failure_test_cases",
                        to="core.user",
                        verbose_name="设计责任人",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试用例",
                "verbose_name_plural": "测试用例",
                "db_table": "pm_failure_test_case",
            },
        ),
        migrations.CreateModel(
            name="HandlingMeasureTestCaseRel",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                ("order_index", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "handling_measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_case_relations",
                        to="project_manager.handlingmeasure",
                        verbose_name="故障处理措施",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handling_measure_relations",
                        to="project_manager.testcase",
                        verbose_name="测试用例",
                    ),
                ),
            ],
            options={
                "verbose_name": "故障处理措施-测试用例关联",
                "verbose_name_plural": "故障处理措施-测试用例关联",
                "db_table": "pm_failure_measure_test_case_rel",
            },
        ),
        migrations.AddIndex(
            model_name="failuremode",
            index=models.Index(fields=["brief"], name="idx_pm_fm_brief"),
        ),
        migrations.AddIndex(
            model_name="failuremode",
            index=models.Index(
                fields=["subsystem", "status"], name="idx_pm_fm_sub_status"
            ),
        ),
        migrations.AddIndex(
            model_name="failuremode",
            index=models.Index(fields=["module_name"], name="idx_pm_fm_module"),
        ),
        migrations.AddIndex(
            model_name="handlingmeasure",
            index=models.Index(fields=["measure"], name="idx_pm_fm_measure"),
        ),
        migrations.AddIndex(
            model_name="failuremodehandlingmeasurerel",
            index=models.Index(
                fields=["failure_mode", "order_index"], name="idx_pm_fm_measure_rel"
            ),
        ),
        migrations.AddConstraint(
            model_name="failuremodehandlingmeasurerel",
            constraint=models.UniqueConstraint(
                fields=("failure_mode", "handling_measure"),
                name="uniq_pm_fm_measure_rel",
            ),
        ),
        migrations.AddIndex(
            model_name="failuremodehuatuodiagnosisrel",
            index=models.Index(
                fields=["failure_mode", "order_index"], name="idx_pm_fm_huatuo_rel"
            ),
        ),
        migrations.AddConstraint(
            model_name="failuremodehuatuodiagnosisrel",
            constraint=models.UniqueConstraint(
                fields=("failure_mode", "huatuo_diagnosis"),
                name="uniq_pm_fm_huatuo_rel",
            ),
        ),
        migrations.AddIndex(
            model_name="interceptionstrategy",
            index=models.Index(
                fields=["interception_item"], name="idx_pm_fm_inter_item"
            ),
        ),
        migrations.AddIndex(
            model_name="failuremodeinterceptionstrategyrel",
            index=models.Index(
                fields=["failure_mode", "order_index"], name="idx_pm_fm_inter_rel"
            ),
        ),
        migrations.AddConstraint(
            model_name="failuremodeinterceptionstrategyrel",
            constraint=models.UniqueConstraint(
                fields=("failure_mode", "interception_strategy"),
                name="uniq_pm_fm_inter_rel",
            ),
        ),
        migrations.AddIndex(
            model_name="observationmethod",
            index=models.Index(fields=["monitor_type"], name="idx_pm_fm_monitor_type"),
        ),
        migrations.AddIndex(
            model_name="observationmethod",
            index=models.Index(fields=["log_id"], name="idx_pm_fm_log_id"),
        ),
        migrations.AddIndex(
            model_name="failuremodeobservationmethodrel",
            index=models.Index(
                fields=["failure_mode", "order_index"], name="idx_pm_fm_observe_rel"
            ),
        ),
        migrations.AddConstraint(
            model_name="failuremodeobservationmethodrel",
            constraint=models.UniqueConstraint(
                fields=("failure_mode", "observation_method"),
                name="uniq_pm_fm_observation_rel",
            ),
        ),
        migrations.AddIndex(
            model_name="testcase",
            index=models.Index(fields=["brief"], name="idx_pm_fm_test_case"),
        ),
        migrations.AddIndex(
            model_name="handlingmeasuretestcaserel",
            index=models.Index(
                fields=["handling_measure", "order_index"], name="idx_pm_fm_test_rel"
            ),
        ),
        migrations.AddConstraint(
            model_name="handlingmeasuretestcaserel",
            constraint=models.UniqueConstraint(
                fields=("handling_measure", "test_case"),
                name="uniq_pm_fm_test_case_rel",
            ),
        ),
    ]
