# Generated by Django 5.2.7 on 2026-03-24

from django.db import migrations


DICT_GROUPS = [
    {
        'name': '故障模式-子系统',
        'code': 'failure_mode_subsystem',
        'remark': '故障模式模块-子系统字典',
        'items': [],
    },
    {
        'name': '故障模式-模块',
        'code': 'failure_mode_module',
        'remark': '故障模式模块-模块字典',
        'items': [],
    },
    {
        'name': '故障模式-芯片',
        'code': 'failure_mode_chip',
        'remark': '故障模式模块-芯片字典',
        'items': [],
    },
    {
        'name': '故障模式-故障类别',
        'code': 'failure_mode_fault_category',
        'remark': '故障模式模块-故障类别字典',
        'items': [],
    },
    {
        'name': '故障模式-功能安全等级',
        'code': 'failure_mode_functional_safety_level',
        'remark': '故障模式模块-功能安全等级字典',
        'items': [],
    },
    {
        'name': '故障模式-故障发生频度',
        'code': 'failure_mode_occurrence_frequency',
        'remark': '故障模式模块-故障发生频度字典',
        'items': [str(index) for index in range(1, 11)],
    },
    {
        'name': '故障模式-故障可探测度',
        'code': 'failure_mode_detectability',
        'remark': '故障模式模块-故障可探测度字典',
        'items': [str(index) for index in range(1, 11)],
    },
    {
        'name': '故障模式-严重程度',
        'code': 'failure_mode_severity',
        'remark': '故障模式模块-严重程度字典',
        'items': [str(index) for index in range(1, 11)],
    },
    {
        'name': '故障模式-状态',
        'code': 'failure_mode_status',
        'remark': '故障模式模块-状态字典',
        'items': [],
    },
    {
        'name': '故障模式-措施类别',
        'code': 'failure_mode_measure_category',
        'remark': '故障模式模块-措施类别字典',
        'items': [],
    },
    {
        'name': '故障模式-维测类型',
        'code': 'failure_mode_monitor_type',
        'remark': '故障模式模块-维测类型字典',
        'items': [],
    },
]


def seed_failure_mode_dicts(apps, schema_editor):
    Dict = apps.get_model('core', 'Dict')
    DictItem = apps.get_model('core', 'DictItem')

    for group in DICT_GROUPS:
        dict_obj, _ = Dict.objects.update_or_create(
            code=group['code'],
            defaults={
                'name': group['name'],
                'status': True,
                'remark': group['remark'],
            },
        )

        items = group.get('items') or []
        total = len(items)
        for index, item_label in enumerate(items):
            label = str(item_label or '').strip()
            if not label:
                continue
            sort_value = (total - index) * 10
            DictItem.objects.update_or_create(
                dict=dict_obj,
                value=label,
                defaults={
                    'label': label,
                    'status': True,
                    'sort': sort_value,
                    'remark': f"{group['name']}选项",
                },
            )


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_plgroup'),
        ('project_manager', '0029_failuremode_handlingmeasure_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_failure_mode_dicts, migrations.RunPython.noop),
    ]
