# Generated by Django 5.2.7 on 2026-03-28 00:01

import django.db.models.deletion
import uuid
from collections import defaultdict

from django.db import migrations, models


FIXED_HANDLING_MEASURE_CATEGORIES = ['检测', '预防', '自愈']
FIXED_OBSERVATION_METHOD_TYPES = ['流水日志', 'DMD 点位', 'FMP 点位']
DICT_GROUPS = {
    'failure_mode_measure_category': {
        'name': '故障模式-措施类别',
        'remark': '故障模式模块-措施类别字典',
        'items': FIXED_HANDLING_MEASURE_CATEGORIES,
    },
    'failure_mode_monitor_type': {
        'name': '故障模式-维测类型',
        'remark': '故障模式模块-维测类型字典',
        'items': FIXED_OBSERVATION_METHOD_TYPES,
    },
}


def _normalize_text(value):
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _normalize_text_list(values):
    if values is None:
        return []
    raw_values = values if isinstance(values, list) else [values]
    result = []
    seen = set()
    for item in raw_values:
        text = _normalize_text(item)
        if not text or text in seen:
            continue
        seen.add(text)
        result.append(text)
    return result


def _append_unique(target, seen, value):
    text = _normalize_text(value)
    if not text or text in seen:
        return
    seen.add(text)
    target.append(text)


def _seed_controlled_dict_items(apps):
    Dict = apps.get_model('core', 'Dict')
    DictItem = apps.get_model('core', 'DictItem')

    for code, config in DICT_GROUPS.items():
        dict_obj, _ = Dict.objects.update_or_create(
            code=code,
            defaults={
                'name': config['name'],
                'status': True,
                'remark': config['remark'],
            },
        )
        items = config.get('items') or []
        total = len(items)
        for index, label in enumerate(items):
            value = _normalize_text(label)
            if not value:
                continue
            DictItem.objects.update_or_create(
                dict=dict_obj,
                value=value,
                defaults={
                    'label': value,
                    'status': True,
                    'sort': (total - index) * 10,
                    'remark': f"{config['name']}选项",
                },
            )


def _backfill_failure_mode_requirements(apps):
    FailureMode = apps.get_model('project_manager', 'FailureMode')
    FailureModeInterceptionStrategyRel = apps.get_model('project_manager', 'FailureModeInterceptionStrategyRel')
    FailureModeHuatuoDiagnosisRel = apps.get_model('project_manager', 'FailureModeHuatuoDiagnosisRel')
    FailureModeHandlingMeasureRel = apps.get_model('project_manager', 'FailureModeHandlingMeasureRel')
    FailureModeObservationMethodRel = apps.get_model('project_manager', 'FailureModeObservationMethodRel')

    interception_ids = set(
        FailureModeInterceptionStrategyRel.objects.values_list('failure_mode_id', flat=True),
    )
    huatuo_ids = set(
        FailureModeHuatuoDiagnosisRel.objects.values_list('failure_mode_id', flat=True),
    )

    handling_map = defaultdict(set)
    for relation in FailureModeHandlingMeasureRel.objects.select_related('handling_measure').all():
        category = _normalize_text(getattr(relation.handling_measure, 'measure_category', None))
        if category in FIXED_HANDLING_MEASURE_CATEGORIES:
            handling_map[relation.failure_mode_id].add(category)

    observation_map = defaultdict(set)
    for relation in FailureModeObservationMethodRel.objects.select_related('observation_method').all():
        monitor_type = _normalize_text(getattr(relation.observation_method, 'monitor_type', None))
        if monitor_type in FIXED_OBSERVATION_METHOD_TYPES:
            observation_map[relation.failure_mode_id].add(monitor_type)

    for failure_mode in FailureMode.objects.all():
        handling_categories = [
            item for item in FIXED_HANDLING_MEASURE_CATEGORIES
            if item in handling_map.get(failure_mode.id, set())
        ]
        observation_types = [
            item for item in FIXED_OBSERVATION_METHOD_TYPES
            if item in observation_map.get(failure_mode.id, set())
        ]
        failure_mode.interception_required = failure_mode.id in interception_ids
        failure_mode.huatuo_required = failure_mode.id in huatuo_ids
        failure_mode.required_handling_measure_categories = handling_categories
        failure_mode.required_observation_method_types = observation_types
        failure_mode.save(
            update_fields=[
                'interception_required',
                'huatuo_required',
                'required_handling_measure_categories',
                'required_observation_method_types',
                'sys_update_datetime',
            ]
        )


def _seed_subsystem_configs(apps):
    FailureMode = apps.get_model('project_manager', 'FailureMode')
    FailureModeSubsystemConfig = apps.get_model('project_manager', 'FailureModeSubsystemConfig')
    DictItem = apps.get_model('core', 'DictItem')
    User = apps.get_model('core', 'User')

    operator = User.objects.filter(is_superuser=True).order_by('sys_create_datetime').first()

    dict_values = {
        'subsystem': [],
        'module': [],
        'chip': [],
    }
    dict_seen = {key: set() for key in dict_values.keys()}

    dict_rows = (
        DictItem.objects.select_related('dict')
        .filter(
            dict__code__in=['failure_mode_subsystem', 'failure_mode_module', 'failure_mode_chip'],
            dict__status=True,
            dict__is_deleted=False,
            status=True,
            is_deleted=False,
        )
        .order_by('dict__code', '-sort', 'sys_create_datetime')
    )

    reverse_map = {
        'failure_mode_subsystem': 'subsystem',
        'failure_mode_module': 'module',
        'failure_mode_chip': 'chip',
    }
    for item in dict_rows:
        dict_code = _normalize_text(getattr(getattr(item, 'dict', None), 'code', None))
        field = reverse_map.get(dict_code)
        if not field:
            continue
        label = _normalize_text(getattr(item, 'label', None) or getattr(item, 'value', None))
        if not label or label in dict_seen[field]:
            continue
        dict_seen[field].add(label)
        dict_values[field].append(label)

    observed = {}
    global_modules = []
    global_module_seen = set()
    global_chips = []
    global_chip_seen = set()

    for failure_mode in FailureMode.objects.all().only('subsystem', 'module_name', 'chips'):
        subsystem = _normalize_text(getattr(failure_mode, 'subsystem', None))
        module_name = _normalize_text(getattr(failure_mode, 'module_name', None))
        chips = _normalize_text_list(getattr(failure_mode, 'chips', []))

        _append_unique(global_modules, global_module_seen, module_name)
        for chip in chips:
            _append_unique(global_chips, global_chip_seen, chip)

        if not subsystem:
            continue
        item = observed.setdefault(
            subsystem,
            {
                'module_options': [],
                'chip_options': [],
                '_module_seen': set(),
                '_chip_seen': set(),
            },
        )
        _append_unique(item['module_options'], item['_module_seen'], module_name)
        for chip in chips:
            _append_unique(item['chip_options'], item['_chip_seen'], chip)

    for value in dict_values['module']:
        _append_unique(global_modules, global_module_seen, value)
    for value in dict_values['chip']:
        _append_unique(global_chips, global_chip_seen, value)

    subsystem_list = []
    subsystem_seen = set()
    for subsystem in dict_values['subsystem'] + list(observed.keys()):
        if subsystem in subsystem_seen:
            continue
        subsystem_seen.add(subsystem)
        subsystem_list.append(subsystem)

    for subsystem in subsystem_list:
        item = observed.get(
            subsystem,
            {
                'module_options': [],
                'chip_options': [],
            },
        )
        module_options = _normalize_text_list(item.get('module_options'))
        chip_options = _normalize_text_list(item.get('chip_options'))
        if subsystem in dict_values['subsystem'] and not module_options:
            module_options = list(global_modules)
        if subsystem in dict_values['subsystem'] and not chip_options:
            chip_options = list(global_chips)

        FailureModeSubsystemConfig.objects.update_or_create(
            subsystem=subsystem,
            defaults={
                'module_options': module_options,
                'chip_options': chip_options,
                'sys_creator': operator,
                'sys_modifier': operator,
                'is_deleted': False,
            },
        )


def seed_failure_mode_statistics_fields(apps, schema_editor):
    _seed_controlled_dict_items(apps)
    _backfill_failure_mode_requirements(apps)
    _seed_subsystem_configs(apps)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_plgroup'),
        ('project_manager', '0030_seed_failure_mode_dicts'),
    ]

    operations = [
        migrations.AddField(
            model_name='failuremode',
            name='huatuo_required',
            field=models.BooleanField(default=False, verbose_name='需要华佗诊断方案'),
        ),
        migrations.AddField(
            model_name='failuremode',
            name='interception_required',
            field=models.BooleanField(default=False, verbose_name='需要产线拦截策略'),
        ),
        migrations.AddField(
            model_name='failuremode',
            name='required_handling_measure_categories',
            field=models.JSONField(blank=True, default=list, verbose_name='必配故障处理措施类别'),
        ),
        migrations.AddField(
            model_name='failuremode',
            name='required_observation_method_types',
            field=models.JSONField(blank=True, default=list, verbose_name='必配维测手段类型'),
        ),
        migrations.CreateModel(
            name='FailureModeSubsystemConfig',
            fields=[
                (
                    'id',
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text='主键ID',
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'sys_create_datetime',
                    models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间'),
                ),
                (
                    'sys_update_datetime',
                    models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间'),
                ),
                (
                    'is_deleted',
                    models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）'),
                ),
                (
                    'sort',
                    models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）'),
                ),
                ('subsystem', models.CharField(max_length=128, unique=True, verbose_name='子系统')),
                ('module_options', models.JSONField(blank=True, default=list, verbose_name='模块选项')),
                ('chip_options', models.JSONField(blank=True, default=list, verbose_name='芯片选项')),
                (
                    'sys_creator',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text='创建人',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_created',
                        to='core.user',
                    ),
                ),
                (
                    'sys_modifier',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text='修改人',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modified',
                        to='core.user',
                    ),
                ),
            ],
            options={
                'verbose_name': '故障模式子系统联动配置',
                'verbose_name_plural': '故障模式子系统联动配置',
                'db_table': 'pm_failure_mode_subsystem_config',
                'indexes': [models.Index(fields=['subsystem'], name='idx_pm_fm_sub_cfg_subsystem')],
            },
        ),
        migrations.RunPython(seed_failure_mode_statistics_fields, migrations.RunPython.noop),
    ]
