# Generated by Django 5.2.7 on 2026-03-30 22:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_plgroup"),
        ("project_manager", "0031_failuremode_huatuo_required_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailureModeProduct",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_failure_mode_products",
                        to="core.user",
                        verbose_name="产品归属人(版本SE)",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failure_mode_product",
                        to="project_manager.project",
                        verbose_name="关联产品(项目)",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品故障模式配置",
                "verbose_name_plural": "产品故障模式配置",
                "db_table": "pm_failure_mode_product",
            },
        ),
        migrations.CreateModel(
            name="FailureModeTask",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="任务名称")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "创建"),
                            ("REVISE", "修订"),
                            ("DELETE", "删除"),
                        ],
                        max_length=32,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ANALYZING", "梳理中"),
                            ("REVIEWING", "评审中"),
                            ("CLOSED", "已关闭"),
                        ],
                        default="ANALYZING",
                        max_length=32,
                        verbose_name="任务状态",
                    ),
                ),
                ("subsystem", models.CharField(max_length=128, verbose_name="子系统")),
                (
                    "review_minutes",
                    models.TextField(
                        blank=True, default="", verbose_name="评审会议纪要"
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_fm_tasks",
                        to="core.user",
                        verbose_name="责任人(特性SE)",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_fm_tasks",
                        to="core.user",
                        verbose_name="创建人(版本SE)",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="project_manager.failuremodeproduct",
                        verbose_name="关联产品",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "故障模式梳理任务",
                "verbose_name_plural": "故障模式梳理任务",
                "db_table": "pm_failure_mode_task",
            },
        ),
        migrations.CreateModel(
            name="ProductFailureMode",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                ("subsystem", models.CharField(max_length=128, verbose_name="子系统")),
                (
                    "failure_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_bindings",
                        to="project_manager.failuremode",
                        verbose_name="故障模式",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bound_failure_modes",
                        to="project_manager.failuremodeproduct",
                        verbose_name="所属产品",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品故障模式基线",
                "verbose_name_plural": "产品故障模式基线",
                "db_table": "pm_product_failure_mode",
            },
        ),
        migrations.CreateModel(
            name="TaskFailureMode",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                (
                    "failure_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_bindings",
                        to="project_manager.failuremode",
                        verbose_name="故障模式",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_failure_modes",
                        to="project_manager.failuremodetask",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务关联故障模式",
                "verbose_name_plural": "任务关联故障模式",
                "db_table": "pm_task_failure_mode",
            },
        ),
        migrations.AddIndex(
            model_name="failuremodetask",
            index=models.Index(fields=["status"], name="idx_pm_fm_task_status"),
        ),
        migrations.AddIndex(
            model_name="failuremodetask",
            index=models.Index(
                fields=["assignee", "status"], name="idx_pm_fm_task_assignee"
            ),
        ),
        migrations.AddIndex(
            model_name="productfailuremode",
            index=models.Index(
                fields=["product", "subsystem"], name="idx_pm_prod_fm_subsys"
            ),
        ),
        migrations.AddConstraint(
            model_name="productfailuremode",
            constraint=models.UniqueConstraint(
                fields=("product", "subsystem", "failure_mode"),
                name="uniq_pm_product_fm",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskfailuremode",
            constraint=models.UniqueConstraint(
                fields=("task", "failure_mode"), name="uniq_pm_task_fm"
            ),
        ),
    ]
