# Generated by Django 5.2.7 on 2026-03-31 08:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


def forwards_fill_failure_mode_workflow_data(apps, schema_editor):
    FailureModeProduct = apps.get_model("project_manager", "FailureModeProduct")
    FailureModeRoleAssignment = apps.get_model("project_manager", "FailureModeRoleAssignment")
    FailureModeTask = apps.get_model("project_manager", "FailureModeTask")

    for product in FailureModeProduct.objects.exclude(owner_id__isnull=True):
        FailureModeRoleAssignment.objects.get_or_create(
            user_id=product.owner_id,
            product_id=product.id,
            role="version_se",
            subsystem="",
            defaults={
                "is_active": True,
                "sys_creator_id": product.sys_creator_id,
                "sys_modifier_id": product.sys_modifier_id,
            },
        )

    for task in FailureModeTask.objects.all():
        legacy_status = task.status
        if legacy_status == "ANALYZING":
            task.status = "PROCESSING"
            task.accepted_at = task.sys_create_datetime
        elif legacy_status == "REVIEWING":
            task.status = "REVIEWING"
            task.accepted_at = task.accepted_at or task.sys_create_datetime
            task.submitted_at = task.submitted_at or task.sys_update_datetime or task.sys_create_datetime
        elif legacy_status == "CLOSED":
            task.status = "CLOSED"
            task.accepted_at = task.accepted_at or task.sys_create_datetime
            task.submitted_at = task.submitted_at or task.sys_update_datetime or task.sys_create_datetime
            task.reviewed_at = task.reviewed_at or task.sys_update_datetime or task.sys_create_datetime
            task.closed_at = task.closed_at or task.reviewed_at
            task.review_result = task.review_result or "approved"
        else:
            task.status = "CREATED"

        if not task.task_no:
            task.task_no = f"FMT{task.sys_create_datetime.strftime('%Y%m%d%H%M%S')}{str(task.id).replace('-', '')[:6]}"
        task.review_minutes_html = task.review_minutes_html or getattr(task, "review_minutes", "") or ""
        task.save(
            update_fields=[
                "status",
                "accepted_at",
                "submitted_at",
                "reviewed_at",
                "closed_at",
                "review_result",
                "review_minutes_html",
                "task_no",
                "sys_update_datetime",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_plgroup"),
        ("project_manager", "0032_failuremodeproduct_failuremodetask_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="failuremodetask",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="接收时间"),
        ),
        migrations.AddField(
            model_name="failuremodetask",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="关闭时间"),
        ),
        migrations.AddField(
            model_name="failuremodetask",
            name="review_attachment_ids",
            field=models.JSONField(blank=True, default=list, verbose_name="评审附件"),
        ),
        migrations.AddField(
            model_name="failuremodetask",
            name="review_minutes_html",
            field=models.TextField(blank=True, default="", verbose_name="评审会议纪要"),
        ),
        migrations.AddField(
            model_name="failuremodetask",
            name="review_result",
            field=models.CharField(
                blank=True,
                choices=[("approved", "通过"), ("rejected", "驳回")],
                default="",
                max_length=32,
                verbose_name="评审结果",
            ),
        ),
        migrations.AddField(
            model_name="failuremodetask",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="评审完成时间"
            ),
        ),
        migrations.AddField(
            model_name="failuremodetask",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="提交评审时间"
            ),
        ),
        migrations.AddField(
            model_name="failuremodetask",
            name="task_no",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
                verbose_name="任务编号",
            ),
        ),
        migrations.AlterField(
            model_name="failuremodetask",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "创建"),
                    ("PROCESSING", "梳理/修订中"),
                    ("REVIEWING", "评审中"),
                    ("CLOSED", "已关闭"),
                ],
                default="CREATED",
                max_length=32,
                verbose_name="任务状态",
            ),
        ),
        migrations.CreateModel(
            name="FailureModeRoleAssignment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("fm_admin", "管理员"),
                            ("version_se", "版本SE"),
                            ("feature_se", "特性SE"),
                            ("member", "普通成员"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="角色",
                    ),
                ),
                (
                    "subsystem",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="子系统"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="project_manager.failuremodeproduct",
                        verbose_name="关联产品",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failure_mode_role_assignments",
                        to="core.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "故障模式角色授权",
                "verbose_name_plural": "故障模式角色授权",
                "db_table": "pm_failure_mode_role_assignment",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="idx_pm_fm_role_user_active"
                    ),
                    models.Index(
                        fields=["product", "role", "subsystem"],
                        name="idx_pm_fm_role_scope",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "role", "product", "subsystem"),
                        name="uniq_pm_fm_role_assignment",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FailureModeTaskLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "创建任务"),
                            ("accept", "接收任务"),
                            ("bind_failure_modes", "绑定故障模式"),
                            ("quick_create_failure_mode", "快速新增故障模式"),
                            ("submit", "提交评审"),
                            ("close", "评审关闭"),
                            ("reassign", "改派责任人"),
                        ],
                        db_index=True,
                        max_length=64,
                        verbose_name="动作",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="原状态"
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="新状态"
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展数据"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failure_mode_task_logs",
                        to="core.user",
                        verbose_name="操作人",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="project_manager.failuremodetask",
                        verbose_name="任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "故障模式任务日志",
                "verbose_name_plural": "故障模式任务日志",
                "db_table": "pm_failure_mode_task_log",
                "indexes": [
                    models.Index(
                        fields=["task", "sys_create_datetime"],
                        name="idx_pm_fm_task_log_time",
                    ),
                    models.Index(
                        fields=["action", "sys_create_datetime"],
                        name="idx_pm_fm_task_log_action",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            forwards_fill_failure_mode_workflow_data,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="failuremodetask",
            name="review_minutes",
        ),
    ]
