# Generated by Django 5.2.7 on 2026-03-31 23:14

import django.db.models.deletion
from django.db import migrations, models


STATUS_ITEMS = ['待梳理', '梳理中', '待评审', '已基线']


def seed_failure_mode_workflow_status_items(apps, schema_editor):
    Dict = apps.get_model('core', 'Dict')
    DictItem = apps.get_model('core', 'DictItem')

    dict_obj = Dict.objects.filter(code='failure_mode_status').first()
    if dict_obj is None:
        return

    total = len(STATUS_ITEMS)
    for index, item_label in enumerate(STATUS_ITEMS):
        sort_value = (total - index) * 10
        DictItem.objects.update_or_create(
            dict=dict_obj,
            value=item_label,
            defaults={
                'label': item_label,
                'status': True,
                'sort': sort_value,
                'remark': '故障模式工作流状态',
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_plgroup"),
        ("project_manager", "0033_remove_failuremodetask_review_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="failuremode",
            name="source_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_failure_modes",
                to="project_manager.failuremodetask",
                verbose_name="来源任务",
            ),
        ),
        migrations.AddField(
            model_name="failuremode",
            name="source_type",
            field=models.CharField(
                choices=[("manual", "手工维护"), ("task_quick_create", "任务快速新增")],
                db_index=True,
                default="manual",
                max_length=32,
                verbose_name="来源类型",
            ),
        ),
        migrations.AddIndex(
            model_name="failuremode",
            index=models.Index(
                fields=["source_type", "source_task"], name="idx_pm_fm_source_task"
            ),
        ),
        migrations.RunPython(
            seed_failure_mode_workflow_status_items,
            migrations.RunPython.noop,
        ),
    ]
