# Generated by Django 5.2.7 on 2026-04-01 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_plgroup"),
        (
            "project_manager",
            "0034_failuremode_source_task_failuremode_source_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="failuremodetask",
            name="baseline_snapshot_ids",
            field=models.JSONField(
                blank=True, default=list, verbose_name="任务创建时基线快照"
            ),
        ),
        migrations.AlterField(
            model_name="failuremodetasklog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "创建任务"),
                    ("accept", "接收任务"),
                    ("bind_failure_modes", "绑定故障模式"),
                    ("quick_create_failure_mode", "快速新增故障模式"),
                    ("save_draft", "保存修订草稿"),
                    ("delete_draft", "撤销修订草稿"),
                    ("submit", "提交评审"),
                    ("close", "评审关闭"),
                    ("reassign", "改派责任人"),
                ],
                db_index=True,
                max_length=64,
                verbose_name="动作",
            ),
        ),
        migrations.CreateModel(
            name="FailureModeTaskDraft",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                (
                    "draft_payload_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="任务修订草稿"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="是否生效"
                    ),
                ),
                (
                    "failure_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_drafts",
                        to="project_manager.failuremode",
                        verbose_name="故障模式",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="project_manager.failuremodetask",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "故障模式任务修订草稿",
                "verbose_name_plural": "故障模式任务修订草稿",
                "db_table": "pm_failure_mode_task_draft",
                "indexes": [
                    models.Index(
                        fields=["task", "is_active"], name="idx_pm_fm_task_draft_task"
                    ),
                    models.Index(
                        fields=["failure_mode", "is_active"],
                        name="idx_pm_fm_task_draft_fm",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "failure_mode"),
                        name="uniq_pm_task_failure_mode_draft",
                    )
                ],
            },
        ),
    ]
