# Generated by Django 5.2.7 on 2026-04-01 22:43

import django.db.models.deletion
from django.db import migrations, models


def populate_current_processor(apps, schema_editor):
    FailureModeTask = apps.get_model("project_manager", "FailureModeTask")
    FailureModeTask.objects.filter(status__in=["CREATED", "PROCESSING"]).update(
        current_processor=models.F("assignee")
    )
    FailureModeTask.objects.filter(status="REVIEWING").update(
        current_processor=models.F("creator")
    )
    FailureModeTask.objects.filter(status="CLOSED").update(current_processor=None)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_plgroup"),
        ("project_manager", "0035_failuremodetask_baseline_snapshot_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="failuremodetask",
            name="current_processor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_processing_fm_tasks",
                to="core.user",
                verbose_name="当前待办归属人",
            ),
        ),
        migrations.RunPython(populate_current_processor, noop_reverse),
        migrations.AlterField(
            model_name="failuremode",
            name="source_type",
            field=models.CharField(
                choices=[("manual", "手动维护"), ("task_quick_create", "任务新增")],
                db_index=True,
                default="manual",
                max_length=32,
                verbose_name="来源类型",
            ),
        ),
        migrations.AlterField(
            model_name="failuremodetasklog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "创建任务"),
                    ("accept", "接收任务"),
                    ("bind_failure_modes", "绑定故障模式"),
                    ("quick_create_failure_mode", "快速新增故障模式"),
                    ("save_draft", "保存修订草稿"),
                    ("delete_draft", "撤销修订草稿"),
                    ("submit", "提交评审"),
                    ("recall", "撤回评审"),
                    ("reject", "驳回任务"),
                    ("close", "评审关闭"),
                    ("reassign", "改派责任人"),
                ],
                db_index=True,
                max_length=64,
                verbose_name="动作",
            ),
        ),
        migrations.AddIndex(
            model_name="failuremodetask",
            index=models.Index(
                fields=["current_processor", "status"], name="idx_pm_fm_task_processor"
            ),
        ),
    ]
