# Generated by Django 5.2.7 on 2026-04-10

import django.db.models.deletion
import uuid
from collections import defaultdict

from django.db import migrations, models


def backfill_product_failure_mode_landings(apps, schema_editor):
    ProductFailureMode = apps.get_model("project_manager", "ProductFailureMode")
    FailureModeInterceptionStrategyRel = apps.get_model(
        "project_manager",
        "FailureModeInterceptionStrategyRel",
    )
    FailureModeHandlingMeasureRel = apps.get_model(
        "project_manager",
        "FailureModeHandlingMeasureRel",
    )
    FailureModeObservationMethodRel = apps.get_model(
        "project_manager",
        "FailureModeObservationMethodRel",
    )
    FailureModeHuatuoDiagnosisRel = apps.get_model(
        "project_manager",
        "FailureModeHuatuoDiagnosisRel",
    )
    ProductFailureModeInterceptionLanding = apps.get_model(
        "project_manager",
        "ProductFailureModeInterceptionLanding",
    )
    ProductFailureModeHandlingLanding = apps.get_model(
        "project_manager",
        "ProductFailureModeHandlingLanding",
    )
    ProductFailureModeObservationLanding = apps.get_model(
        "project_manager",
        "ProductFailureModeObservationLanding",
    )
    ProductFailureModeHuatuoLanding = apps.get_model(
        "project_manager",
        "ProductFailureModeHuatuoLanding",
    )

    ProductFailureMode.objects.filter(is_deleted=False).update(is_landed=True)
    product_failure_modes = list(
        ProductFailureMode.objects.filter(is_deleted=False).only("id", "failure_mode_id"),
    )
    if not product_failure_modes:
        return

    failure_mode_ids = [item.failure_mode_id for item in product_failure_modes if item.failure_mode_id]
    if not failure_mode_ids:
        return

    relation_maps = {
        "interception": defaultdict(list),
        "handling": defaultdict(list),
        "observation": defaultdict(list),
        "huatuo": defaultdict(list),
    }

    for relation in FailureModeInterceptionStrategyRel.objects.filter(
        is_deleted=False,
        failure_mode_id__in=failure_mode_ids,
    ).only("failure_mode_id", "interception_strategy_id"):
        relation_maps["interception"][relation.failure_mode_id].append(
            relation.interception_strategy_id,
        )

    for relation in FailureModeHandlingMeasureRel.objects.filter(
        is_deleted=False,
        failure_mode_id__in=failure_mode_ids,
    ).only("failure_mode_id", "handling_measure_id"):
        relation_maps["handling"][relation.failure_mode_id].append(
            relation.handling_measure_id,
        )

    for relation in FailureModeObservationMethodRel.objects.filter(
        is_deleted=False,
        failure_mode_id__in=failure_mode_ids,
    ).only("failure_mode_id", "observation_method_id"):
        relation_maps["observation"][relation.failure_mode_id].append(
            relation.observation_method_id,
        )

    for relation in FailureModeHuatuoDiagnosisRel.objects.filter(
        is_deleted=False,
        failure_mode_id__in=failure_mode_ids,
    ).only("failure_mode_id", "huatuo_diagnosis_id"):
        relation_maps["huatuo"][relation.failure_mode_id].append(
            relation.huatuo_diagnosis_id,
        )

    interception_rows = []
    handling_rows = []
    observation_rows = []
    huatuo_rows = []

    for product_failure_mode in product_failure_modes:
        for resource_id in relation_maps["interception"].get(
            product_failure_mode.failure_mode_id,
            [],
        ):
            interception_rows.append(
                ProductFailureModeInterceptionLanding(
                    product_failure_mode_id=product_failure_mode.id,
                    interception_strategy_id=resource_id,
                    is_landed=True,
                ),
            )
        for resource_id in relation_maps["handling"].get(
            product_failure_mode.failure_mode_id,
            [],
        ):
            handling_rows.append(
                ProductFailureModeHandlingLanding(
                    product_failure_mode_id=product_failure_mode.id,
                    handling_measure_id=resource_id,
                    is_landed=True,
                ),
            )
        for resource_id in relation_maps["observation"].get(
            product_failure_mode.failure_mode_id,
            [],
        ):
            observation_rows.append(
                ProductFailureModeObservationLanding(
                    product_failure_mode_id=product_failure_mode.id,
                    observation_method_id=resource_id,
                    is_landed=True,
                ),
            )
        for resource_id in relation_maps["huatuo"].get(
            product_failure_mode.failure_mode_id,
            [],
        ):
            huatuo_rows.append(
                ProductFailureModeHuatuoLanding(
                    product_failure_mode_id=product_failure_mode.id,
                    huatuo_diagnosis_id=resource_id,
                    is_landed=True,
                ),
            )

    ProductFailureModeInterceptionLanding.objects.bulk_create(
        interception_rows,
        batch_size=500,
        ignore_conflicts=True,
    )
    ProductFailureModeHandlingLanding.objects.bulk_create(
        handling_rows,
        batch_size=500,
        ignore_conflicts=True,
    )
    ProductFailureModeObservationLanding.objects.bulk_create(
        observation_rows,
        batch_size=500,
        ignore_conflicts=True,
    )
    ProductFailureModeHuatuoLanding.objects.bulk_create(
        huatuo_rows,
        batch_size=500,
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_plgroup"),
        ("project_manager", "0037_dts_statistics_async_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="productfailuremode",
            name="is_landed",
            field=models.BooleanField(default=False, verbose_name="故障模式是否已落地"),
        ),
        migrations.AddField(
            model_name="taskfailuremode",
            name="landing_payload_json",
            field=models.JSONField(blank=True, default=dict, verbose_name="任务内落地草稿"),
        ),
        migrations.AlterField(
            model_name="failuremodetasklog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "创建任务"),
                    ("accept", "接收任务"),
                    ("bind_failure_modes", "绑定故障模式"),
                    ("quick_create_failure_mode", "快速新增故障模式"),
                    ("edit_failure_mode", "编辑任务内故障模式"),
                    ("save_landing", "保存落地配置"),
                    ("save_draft", "保存修订草稿"),
                    ("delete_draft", "撤销修订草稿"),
                    ("submit", "提交评审"),
                    ("recall", "撤回评审"),
                    ("reject", "驳回任务"),
                    ("close", "评审关闭"),
                    ("reassign", "改派责任人"),
                ],
                db_index=True,
                max_length=64,
                verbose_name="动作",
            ),
        ),
        migrations.CreateModel(
            name="ProductFailureModeInterceptionLanding",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(auto_now_add=True, db_index=True, help_text="创建时间"),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(auto_now=True, db_index=True, help_text="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, help_text="是否删除（软删除标识）"),
                ),
                (
                    "sort",
                    models.IntegerField(db_index=True, default=0, help_text="排序（数字越大越靠前）"),
                ),
                ("is_landed", models.BooleanField(default=False, verbose_name="是否已落地")),
                (
                    "interception_strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_failure_mode_landings",
                        to="project_manager.interceptionstrategy",
                        verbose_name="产线拦截策略",
                    ),
                ),
                (
                    "product_failure_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interception_landings",
                        to="project_manager.productfailuremode",
                        verbose_name="产品故障模式基线",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品故障模式-产线拦截策略落地",
                "verbose_name_plural": "产品故障模式-产线拦截策略落地",
                "db_table": "pm_product_fm_interception_landing",
                "indexes": [
                    models.Index(
                        fields=["product_failure_mode"],
                        name="idx_pfmil_pfm",
                    ),
                    models.Index(
                        fields=["interception_strategy"],
                        name="idx_pfmil_item",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product_failure_mode", "interception_strategy"),
                        name="uniq_pm_prod_fm_inter_landing",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductFailureModeHandlingLanding",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(auto_now_add=True, db_index=True, help_text="创建时间"),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(auto_now=True, db_index=True, help_text="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, help_text="是否删除（软删除标识）"),
                ),
                (
                    "sort",
                    models.IntegerField(db_index=True, default=0, help_text="排序（数字越大越靠前）"),
                ),
                ("is_landed", models.BooleanField(default=False, verbose_name="是否已落地")),
                (
                    "handling_measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_failure_mode_landings",
                        to="project_manager.handlingmeasure",
                        verbose_name="故障处理措施",
                    ),
                ),
                (
                    "product_failure_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handling_landings",
                        to="project_manager.productfailuremode",
                        verbose_name="产品故障模式基线",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品故障模式-故障处理措施落地",
                "verbose_name_plural": "产品故障模式-故障处理措施落地",
                "db_table": "pm_product_fm_handling_landing",
                "indexes": [
                    models.Index(
                        fields=["product_failure_mode"],
                        name="idx_pfmhl_pfm",
                    ),
                    models.Index(
                        fields=["handling_measure"],
                        name="idx_pfmhl_item",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product_failure_mode", "handling_measure"),
                        name="uniq_pm_prod_fm_handling_landing",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductFailureModeObservationLanding",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(auto_now_add=True, db_index=True, help_text="创建时间"),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(auto_now=True, db_index=True, help_text="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, help_text="是否删除（软删除标识）"),
                ),
                (
                    "sort",
                    models.IntegerField(db_index=True, default=0, help_text="排序（数字越大越靠前）"),
                ),
                ("is_landed", models.BooleanField(default=False, verbose_name="是否已落地")),
                (
                    "observation_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_failure_mode_landings",
                        to="project_manager.observationmethod",
                        verbose_name="维测手段",
                    ),
                ),
                (
                    "product_failure_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observation_landings",
                        to="project_manager.productfailuremode",
                        verbose_name="产品故障模式基线",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品故障模式-维测手段落地",
                "verbose_name_plural": "产品故障模式-维测手段落地",
                "db_table": "pm_product_fm_observation_landing",
                "indexes": [
                    models.Index(
                        fields=["product_failure_mode"],
                        name="idx_pfmol_pfm",
                    ),
                    models.Index(
                        fields=["observation_method"],
                        name="idx_pfmol_item",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product_failure_mode", "observation_method"),
                        name="uniq_pm_prod_fm_observation_landing",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductFailureModeHuatuoLanding",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(auto_now_add=True, db_index=True, help_text="创建时间"),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(auto_now=True, db_index=True, help_text="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, help_text="是否删除（软删除标识）"),
                ),
                (
                    "sort",
                    models.IntegerField(db_index=True, default=0, help_text="排序（数字越大越靠前）"),
                ),
                ("is_landed", models.BooleanField(default=False, verbose_name="是否已落地")),
                (
                    "huatuo_diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_failure_mode_landings",
                        to="project_manager.huatuodiagnosis",
                        verbose_name="华佗诊断方案",
                    ),
                ),
                (
                    "product_failure_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="huatuo_landings",
                        to="project_manager.productfailuremode",
                        verbose_name="产品故障模式基线",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品故障模式-华佗诊断方案落地",
                "verbose_name_plural": "产品故障模式-华佗诊断方案落地",
                "db_table": "pm_product_fm_huatuo_landing",
                "indexes": [
                    models.Index(
                        fields=["product_failure_mode"],
                        name="idx_pfmul_pfm",
                    ),
                    models.Index(
                        fields=["huatuo_diagnosis"],
                        name="idx_pfmul_item",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product_failure_mode", "huatuo_diagnosis"),
                        name="uniq_pm_prod_fm_huatuo_landing",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            backfill_product_failure_mode_landings,
            migrations.RunPython.noop,
        ),
    ]
