# Generated by Django 5.2.7 on 2026-04-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0039_recalculate_product_failure_mode_landing_cache'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dtsstatisticsexporttask',
            new_name='pm_dts_stat_user_id_0f0803_idx',
            old_name='pm_dts_et_u_f_s_idx',
        ),
        migrations.RenameIndex(
            model_name='dtsstatisticsexporttask',
            new_name='pm_dts_stat_user_id_d48ab3_idx',
            old_name='pm_dts_et_u_c_idx',
        ),
        migrations.RenameIndex(
            model_name='dtsstatisticsquerytask',
            new_name='pm_dts_stat_user_id_8010bd_idx',
            old_name='pm_dts_qt_u_f_s_idx',
        ),
        migrations.RenameIndex(
            model_name='dtsstatisticsquerytask',
            new_name='pm_dts_stat_user_id_b580fb_idx',
            old_name='pm_dts_qt_u_c_idx',
        ),
    ]
