# Generated by Codex on 2026-04-15

from django.db import migrations, models


def seed_dts_governance_refactor_dicts(apps, schema_editor):
    Dict = apps.get_model("core", "Dict")
    DictItem = apps.get_model("core", "DictItem")

    dict_groups = [
        {
            "name": "DTS-问题引入阶段",
            "code": "dts_issue_intro_stage",
            "remark": "DTS统计模块-问题引入阶段",
            "items": [
                "需求分析",
                "技术方案",
                "设计实现",
                "开发自测",
                "联调集成",
                "测试回归",
                "发布变更",
                "配置运维",
                "其他",
            ],
        },
        {
            "name": "DTS-问题引入点",
            "code": "dts_dev_issue_intro_point",
            "remark": "DTS统计模块-开发填报-问题引入点",
            "items": [
                "需求澄清不足",
                "技术方案遗漏",
                "接口设计不合理",
                "状态时序处理",
                "边界条件遗漏",
                "配置变更影响",
                "三方依赖兼容",
                "数据处理异常",
                "回归改动引入",
                "其他",
            ],
        },
        {
            "name": "DTS-问题概率",
            "code": "dts_dev_issue_probability",
            "remark": "DTS统计模块-开发填报-问题概率",
            "items": [
                "偶发",
                "低频",
                "中频",
                "高频",
                "必现",
                "其他",
            ],
        },
        {
            "name": "DTS-是否共性问题",
            "code": "dts_dev_common_issue_type",
            "remark": "DTS统计模块-开发填报-是否共性问题",
            "items": [
                "非共性问题",
                "单模块共性",
                "跨模块共性",
                "跨项目共性",
                "其他",
            ],
        },
        {
            "name": "DTS-开发控制点",
            "code": "dts_dev_control_point",
            "remark": "DTS统计模块-开发填报-需要补强的开发控制点",
            "items": [
                "需求评审补强",
                "技术方案评审补强",
                "设计评审补强",
                "代码评审补强",
                "静态检查补强",
                "单元测试补强",
                "集成测试补强",
                "回归测试补强",
                "发布检查补强",
                "监控告警补强",
                "其他",
            ],
        },
    ]

    for group in dict_groups:
        dict_obj, _ = Dict.objects.update_or_create(
            code=group["code"],
            defaults={
                "name": group["name"],
                "status": True,
                "remark": group["remark"],
            },
        )
        items = group.get("items") or []
        total = len(items)
        for index, item_label in enumerate(items):
            label = str(item_label or "").strip()
            if not label:
                continue
            sort_value = (total - index) * 10
            DictItem.objects.update_or_create(
                dict=dict_obj,
                value=label,
                defaults={
                    "label": label,
                    "status": True,
                    "sort": sort_value,
                    "remark": f"{group['name']}选项",
                },
            )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_plgroup"),
        ("project_manager", "0040_rename_pm_dts_et_u_f_s_idx_pm_dts_stat_user_id_0f0803_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dtsextension",
            name="qa_category",
        ),
        migrations.RemoveField(
            model_name="dtsextension",
            name="pl_group",
        ),
        migrations.AddField(
            model_name="dtsextension",
            name="issue_intro_stage",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="问题引入阶段"),
        ),
        migrations.AddField(
            model_name="dtsextension",
            name="need_aar",
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name="是否需要AAR"),
        ),
        migrations.AddField(
            model_name="dtsextension",
            name="dev_issue_intro_point",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="问题引入点"),
        ),
        migrations.AddField(
            model_name="dtsextension",
            name="dev_issue_probability",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="问题概率"),
        ),
        migrations.AddField(
            model_name="dtsextension",
            name="dev_common_issue_type",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="是否共性问题"),
        ),
        migrations.AddField(
            model_name="dtsextension",
            name="dev_control_points",
            field=models.JSONField(blank=True, default=list, verbose_name="需要补强的开发控制点"),
        ),
        migrations.AddField(
            model_name="dtsextension",
            name="dev_intro_point_analysis",
            field=models.TextField(blank=True, null=True, verbose_name="引入点分析"),
        ),
        migrations.AddField(
            model_name="dtsextension",
            name="dev_aar_link",
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name="AAR链接"),
        ),
        migrations.RenameField(
            model_name="dtsextension",
            old_name="test_feature",
            new_name="dev_feature",
        ),
        migrations.RunPython(seed_dts_governance_refactor_dicts, migrations.RunPython.noop),
    ]
