# Generated by Django 5.2.7 on 2026-04-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0041_dts_extension_governance_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtsextension',
            name='dev_feature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='特性/功能'),
        ),
    ]
