# Generated by Codex on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_manager", "0042_alter_dtsextension_dev_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="dtsextension",
            name="dev_remark",
            field=models.TextField(blank=True, null=True, verbose_name="开发备注"),
        ),
        migrations.AddField(
            model_name="dtsextension",
            name="test_remark",
            field=models.TextField(blank=True, null=True, verbose_name="测试备注"),
        ),
    ]
