# Generated by Codex on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_manager", "0043_dtsextension_dev_test_remark"),
    ]

    operations = [
        migrations.AddField(
            model_name="dtsextension",
            name="is_base_soft_issue",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                verbose_name="是否底软问题",
            ),
        ),
        migrations.AddField(
            model_name="dtsextension",
            name="is_duplicate_issue",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                verbose_name="是否重复问题",
            ),
        ),
        migrations.AddField(
            model_name="dtsextension",
            name="duplicate_issue_no",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="重复问题单号",
            ),
        ),
    ]
