# Generated by Codex on 2026-04-21

from django.db import migrations, models


def seed_dts_dev_asset_type_dict(apps, schema_editor):
    Dict = apps.get_model("core", "Dict")
    DictItem = apps.get_model("core", "DictItem")

    dict_group = {
        "name": "DTS-落地资产类型",
        "code": "dts_dev_asset_type",
        "remark": "DTS统计模块-开发填报-落地资产类型（多选）",
        "items": [
            "文档",
            "脚本",
            "工具",
            "组件",
            "平台能力",
            "规范",
            "知识库",
            "其他",
        ],
    }

    dict_obj, _ = Dict.objects.update_or_create(
        code=dict_group["code"],
        defaults={
            "name": dict_group["name"],
            "status": True,
            "remark": dict_group["remark"],
        },
    )

    items = dict_group.get("items") or []
    total = len(items)
    for index, item_label in enumerate(items):
        label = str(item_label or "").strip()
        if not label:
            continue
        sort_value = (total - index) * 10
        DictItem.objects.update_or_create(
            dict=dict_obj,
            value=label,
            defaults={
                "label": label,
                "status": True,
                "sort": sort_value,
                "remark": f"{dict_group['name']}选项",
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_plgroup"),
        ("project_manager", "0044_dts_extension_dev_duplicate_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="dtsextension",
            name="dev_asset_type",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="落地资产类型(开发)",
            ),
        ),
        migrations.RunPython(seed_dts_dev_asset_type_dict, migrations.RunPython.noop),
    ]
