# Generated by Django 5.2.7 on 2026-05-20 22:35

import django.db.models.deletion
import uuid
from collections import defaultdict
from typing import Any

from django.db import migrations, models


def backfill_failure_mode_scope_bindings(apps, schema_editor):
    FailureMode = apps.get_model('project_manager', 'FailureMode')
    ProductFailureMode = apps.get_model('project_manager', 'ProductFailureMode')

    bindings_by_failure_mode: dict[str, list[dict[str, str]]] = defaultdict(list)
    seen_pairs: dict[str, set[tuple[str, str]]] = defaultdict(set)

    queryset = (
        ProductFailureMode.objects.filter(is_deleted=False)
        .exclude(failure_mode_id__isnull=True)
        .exclude(subsystem__isnull=True)
        .exclude(subsystem='')
        .values('failure_mode_id', 'product_id', 'subsystem')
        .order_by('failure_mode_id', 'product_id', 'subsystem', 'sys_create_datetime', 'id')
    )
    for row in queryset:
        failure_mode_id = str(row['failure_mode_id'])
        product_id = str(row['product_id'])
        subsystem = str(row['subsystem'] or '').strip()
        if not product_id or not subsystem:
            continue
        pair = (product_id, subsystem)
        if pair in seen_pairs[failure_mode_id]:
            continue
        seen_pairs[failure_mode_id].add(pair)
        bindings_by_failure_mode[failure_mode_id].append(
            {
                'product_id': product_id,
                'subsystem': subsystem,
            },
        )

    for failure_mode_id in FailureMode.objects.filter(is_deleted=False).values_list('id', flat=True):
        FailureMode.objects.filter(id=failure_mode_id).update(
            scope_bindings=bindings_by_failure_mode.get(str(failure_mode_id), []),
        )


def backfill_product_failure_mode_relations(apps, schema_editor):
    ProductFailureMode = apps.get_model('project_manager', 'ProductFailureMode')

    relation_specs = [
        (
            'FailureModeInterceptionStrategyRel',
            'ProductFailureModeInterceptionStrategyRel',
            'interception_strategy_id',
        ),
        (
            'FailureModeHandlingMeasureRel',
            'ProductFailureModeHandlingMeasureRel',
            'handling_measure_id',
        ),
        (
            'FailureModeObservationMethodRel',
            'ProductFailureModeObservationMethodRel',
            'observation_method_id',
        ),
        (
            'FailureModeHuatuoDiagnosisRel',
            'ProductFailureModeHuatuoDiagnosisRel',
            'huatuo_diagnosis_id',
        ),
    ]

    product_failure_modes = list(
        ProductFailureMode.objects.filter(is_deleted=False)
        .exclude(failure_mode_id__isnull=True)
        .only('id', 'failure_mode_id')
    )
    if not product_failure_modes:
        return

    failure_mode_ids = [str(item.failure_mode_id) for item in product_failure_modes if item.failure_mode_id]
    if not failure_mode_ids:
        return

    for source_model_name, target_model_name, target_field_name in relation_specs:
        SourceRelation = apps.get_model('project_manager', source_model_name)
        TargetRelation = apps.get_model('project_manager', target_model_name)

        grouped_sources: dict[str, list[Any]] = defaultdict(list)
        for source_item in (
            SourceRelation.objects.filter(is_deleted=False, failure_mode_id__in=failure_mode_ids)
            .select_related('failure_mode')
            .order_by('failure_mode_id', 'order_index', 'sys_create_datetime', 'id')
        ):
            grouped_sources[str(source_item.failure_mode_id)].append(source_item)

        target_rows = []
        for product_failure_mode in product_failure_modes:
            source_items = grouped_sources.get(str(product_failure_mode.failure_mode_id), [])
            for source_item in source_items:
                target_id = getattr(source_item, target_field_name, None)
                if not target_id:
                    continue
                target_rows.append(
                    TargetRelation(
                        product_failure_mode_id=product_failure_mode.id,
                        **{
                            target_field_name: target_id,
                            'order_index': source_item.order_index,
                            'sys_creator_id': source_item.sys_creator_id,
                            'sys_modifier_id': source_item.sys_modifier_id,
                        },
                    ),
                )

        if target_rows:
            TargetRelation.objects.bulk_create(target_rows, batch_size=500, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_permission_code"),
        ("project_manager", "0045_dts_extension_dev_asset_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="failuremode",
            name="scope_bindings",
            field=models.JSONField(
                blank=True, default=list, verbose_name="产品范围绑定"
            ),
        ),
        migrations.AlterField(
            model_name="failuremodetask",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="project_manager.failuremodeproduct",
                verbose_name="关联产品",
            ),
        ),
        migrations.AlterField(
            model_name="failuremodetask",
            name="subsystem",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="子系统"
            ),
        ),
        migrations.AlterField(
            model_name="failuremodetasklog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "创建任务"),
                    ("accept", "接收任务"),
                    ("bind_failure_modes", "绑定故障模式"),
                    ("quick_create_failure_mode", "快速新增故障模式"),
                    ("edit_failure_mode", "编辑任务内故障模式"),
                    ("save_landing", "保存落地配置"),
                    ("save_draft", "保存修订草稿"),
                    ("delete_draft", "撤销修订草稿"),
                    ("update_scope", "补齐工作范围"),
                    ("submit", "提交评审"),
                    ("recall", "撤回评审"),
                    ("reject", "驳回任务"),
                    ("close", "评审关闭"),
                    ("reassign", "改派责任人"),
                ],
                db_index=True,
                max_length=64,
                verbose_name="动作",
            ),
        ),
        migrations.CreateModel(
            name="ProductFailureModeHandlingMeasureRel",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                ("order_index", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "handling_measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_failure_mode_relations",
                        to="project_manager.handlingmeasure",
                        verbose_name="故障处理措施",
                    ),
                ),
                (
                    "product_failure_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handling_measure_relations",
                        to="project_manager.productfailuremode",
                        verbose_name="产品故障模式基线",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品故障模式-故障处理措施关联",
                "verbose_name_plural": "产品故障模式-故障处理措施关联",
                "db_table": "pm_product_fm_measure_rel",
                "indexes": [
                    models.Index(
                        fields=["product_failure_mode", "order_index"],
                        name="idx_pm_prod_fm_measure_rel",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product_failure_mode", "handling_measure"),
                        name="uniq_pm_prod_fm_measure_rel",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductFailureModeHuatuoDiagnosisRel",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                ("order_index", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "huatuo_diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_failure_mode_relations",
                        to="project_manager.huatuodiagnosis",
                        verbose_name="华佗诊断方案",
                    ),
                ),
                (
                    "product_failure_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="huatuo_diagnosis_relations",
                        to="project_manager.productfailuremode",
                        verbose_name="产品故障模式基线",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品故障模式-华佗诊断方案关联",
                "verbose_name_plural": "产品故障模式-华佗诊断方案关联",
                "db_table": "pm_product_fm_huatuo_rel",
                "indexes": [
                    models.Index(
                        fields=["product_failure_mode", "order_index"],
                        name="idx_pm_prod_fm_huatuo_rel",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product_failure_mode", "huatuo_diagnosis"),
                        name="uniq_pm_prod_fm_huatuo_rel",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductFailureModeInterceptionStrategyRel",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                ("order_index", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "interception_strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_failure_mode_relations",
                        to="project_manager.interceptionstrategy",
                        verbose_name="产线拦截策略",
                    ),
                ),
                (
                    "product_failure_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interception_relations",
                        to="project_manager.productfailuremode",
                        verbose_name="产品故障模式基线",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品故障模式-产线拦截策略关联",
                "verbose_name_plural": "产品故障模式-产线拦截策略关联",
                "db_table": "pm_product_fm_interception_rel",
                "indexes": [
                    models.Index(
                        fields=["product_failure_mode", "order_index"],
                        name="idx_pm_prod_fm_inter_rel",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product_failure_mode", "interception_strategy"),
                        name="uniq_pm_prod_fm_inter_rel",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductFailureModeObservationMethodRel",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                ("order_index", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "observation_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_failure_mode_relations",
                        to="project_manager.observationmethod",
                        verbose_name="维测手段",
                    ),
                ),
                (
                    "product_failure_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observation_method_relations",
                        to="project_manager.productfailuremode",
                        verbose_name="产品故障模式基线",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品故障模式-维测手段关联",
                "verbose_name_plural": "产品故障模式-维测手段关联",
                "db_table": "pm_product_fm_observation_rel",
                "indexes": [
                    models.Index(
                        fields=["product_failure_mode", "order_index"],
                        name="idx_pm_prod_fm_observe_rel",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product_failure_mode", "observation_method"),
                        name="uniq_pm_prod_fm_observation_rel",
                    )
                ],
            },
        ),
        migrations.RunPython(
            backfill_failure_mode_scope_bindings,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            backfill_product_failure_mode_relations,
            migrations.RunPython.noop,
        ),
    ]
