# Generated by Codex on 2026-05-22.

from django.db import migrations, models


LANDING_STATUS_LANDED = '已落地'
LANDING_STATUS_NOT_LANDED = '未落地'


def backfill_landing_status(apps, schema_editor):
    landing_models = [
        ('ProductFailureModeInterceptionLanding', 'is_landed'),
        ('ProductFailureModeHandlingLanding', 'is_landed'),
        ('ProductFailureModeObservationLanding', 'is_landed'),
        ('ProductFailureModeHuatuoLanding', 'is_landed'),
    ]
    for model_name, bool_field_name in landing_models:
        model = apps.get_model('project_manager', model_name)
        for row in model.objects.all().only('id', bool_field_name):
            status = LANDING_STATUS_LANDED if getattr(row, bool_field_name) else LANDING_STATUS_NOT_LANDED
            model.objects.filter(id=row.id).update(landing_status=status)


def reverse_backfill_landing_status(apps, schema_editor):
    landing_models = [
        'ProductFailureModeInterceptionLanding',
        'ProductFailureModeHandlingLanding',
        'ProductFailureModeObservationLanding',
        'ProductFailureModeHuatuoLanding',
    ]
    for model_name in landing_models:
        model = apps.get_model('project_manager', model_name)
        for row in model.objects.all().only('id', 'landing_status'):
            is_landed = getattr(row, 'landing_status', '') == LANDING_STATUS_LANDED
            model.objects.filter(id=row.id).update(is_landed=is_landed)


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0046_failuremode_scope_bindings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfailuremodeinterceptionlanding',
            name='landing_status',
            field=models.CharField(
                choices=[
                    ('已落地', '已落地'),
                    ('未落地', '未落地'),
                    ('不涉及', '不涉及'),
                ],
                default='未落地',
                max_length=32,
                verbose_name='落地状态',
            ),
        ),
        migrations.AddField(
            model_name='productfailuremodehandlinglanding',
            name='landing_status',
            field=models.CharField(
                choices=[
                    ('已落地', '已落地'),
                    ('未落地', '未落地'),
                    ('不涉及', '不涉及'),
                ],
                default='未落地',
                max_length=32,
                verbose_name='落地状态',
            ),
        ),
        migrations.AddField(
            model_name='productfailuremodeobservationlanding',
            name='landing_status',
            field=models.CharField(
                choices=[
                    ('已落地', '已落地'),
                    ('未落地', '未落地'),
                    ('不涉及', '不涉及'),
                ],
                default='未落地',
                max_length=32,
                verbose_name='落地状态',
            ),
        ),
        migrations.AddField(
            model_name='productfailuremodehuatuolanding',
            name='landing_status',
            field=models.CharField(
                choices=[
                    ('已落地', '已落地'),
                    ('未落地', '未落地'),
                    ('不涉及', '不涉及'),
                ],
                default='未落地',
                max_length=32,
                verbose_name='落地状态',
            ),
        ),
        migrations.RunPython(backfill_landing_status, reverse_backfill_landing_status),
    ]
