# Generated by Codex on 2026-05-25.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0047_productfailuremode_landing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="hardware_software_interface_doc",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="软硬件接口文档",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="power_info_link",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="用电信息表链接",
            ),
        ),
    ]
