# Generated by Codex on 2026-05-28.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0048_project_vehicle_optional_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfailuremodeinterceptionlanding',
            name='tengwu_requirement_numbers',
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name='腾雾需求号',
            ),
        ),
        migrations.AddField(
            model_name='productfailuremodehandlinglanding',
            name='tengwu_requirement_numbers',
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name='腾雾需求号',
            ),
        ),
        migrations.AddField(
            model_name='productfailuremodeobservationlanding',
            name='tengwu_requirement_numbers',
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name='腾雾需求号',
            ),
        ),
        migrations.AddField(
            model_name='productfailuremodehuatuolanding',
            name='tengwu_requirement_numbers',
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name='腾雾需求号',
            ),
        ),
    ]
