# Generated by Codex on 2026-07-06.

from django.db import migrations, models


def normalize_vehicle_link_value(value):
    if value is None:
        return []
    if isinstance(value, list):
        normalized = []
        for item in value:
            if isinstance(item, dict):
                chip_name = str(item.get("chip_name") or "").strip()
                url = str(item.get("url") or "").strip()
                if chip_name or url:
                    normalized.append({"chip_name": chip_name, "url": url})
            elif isinstance(item, str):
                url = item.strip()
                if url:
                    normalized.append({"chip_name": "", "url": url})
        return normalized
    text = str(value or "").strip()
    return [{"chip_name": "", "url": text}] if text else []


def copy_project_vehicle_links(apps, schema_editor):
    Project = apps.get_model("project_manager", "Project")
    for project in Project.objects.all().only(
        "id",
        "power_info_link",
        "hardware_software_interface_doc",
    ):
        Project.objects.filter(id=project.id).update(
            power_info_link_json=normalize_vehicle_link_value(
                project.power_info_link,
            ),
            hardware_software_interface_doc_json=normalize_vehicle_link_value(
                project.hardware_software_interface_doc,
            ),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0049_product_failure_mode_landing_tengwu_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="hardware_software_interface_doc_json",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="软硬件接口文档",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="power_info_link_json",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="用电信息表链接",
            ),
        ),
        migrations.RunPython(copy_project_vehicle_links, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="project",
            name="hardware_software_interface_doc",
        ),
        migrations.RemoveField(
            model_name="project",
            name="power_info_link",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="hardware_software_interface_doc_json",
            new_name="hardware_software_interface_doc",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="power_info_link_json",
            new_name="power_info_link",
        ),
    ]
