# Generated by Codex on 2026-07-08.

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0050_project_vehicle_links_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectReleasePlan",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(auto_now_add=True, db_index=True, help_text="创建时间"),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(auto_now=True, db_index=True, help_text="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, help_text="是否删除（软删除标识）"),
                ),
                (
                    "sort",
                    models.IntegerField(db_index=True, default=0, help_text="排序（数字越大越靠前）"),
                ),
                ("branch_name", models.CharField(db_index=True, max_length=255, verbose_name="分支名")),
                ("release_date", models.DateField(db_index=True, verbose_name="发布日期")),
                (
                    "version_type",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        verbose_name="版本类型",
                    ),
                ),
                (
                    "scenario",
                    models.CharField(
                        choices=[("vehicle", "车控"), ("cockpit", "座舱")],
                        db_index=True,
                        max_length=20,
                        verbose_name="发布场景",
                    ),
                ),
                ("release_vehicles", models.JSONField(blank=True, default=list, verbose_name="发布车型")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "cdc_platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="release_plans",
                        to="project_manager.cdcplatform",
                        verbose_name="CDC平台",
                    ),
                ),
                (
                    "idvp_platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="release_plans",
                        to="project_manager.idvpplatform",
                        verbose_name="IDVP平台",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_plans",
                        to="project_manager.project",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目发布计划",
                "verbose_name_plural": "项目发布计划",
                "db_table": "pm_project_release_plan",
            },
        ),
        migrations.AddIndex(
            model_name="projectreleaseplan",
            index=models.Index(fields=["project", "branch_name"], name="pm_rel_project_branch_idx"),
        ),
        migrations.AddIndex(
            model_name="projectreleaseplan",
            index=models.Index(fields=["release_date", "version_type"], name="pm_rel_date_version_idx"),
        ),
    ]
