# Generated by Codex on 2026-08-31

from django.db import migrations


def seed_dts_test_miss_reason_outer_domain(apps, schema_editor):
    Dict = apps.get_model("core", "Dict")
    DictItem = apps.get_model("core", "DictItem")

    dict_obj, _ = Dict.objects.update_or_create(
        code="dts_test_miss_reason",
        defaults={
            "name": "DTS-漏测原因",
            "status": True,
            "remark": "DTS统计模块-漏测原因",
        },
    )
    DictItem.objects.update_or_create(
        dict=dict_obj,
        value="外领域未按处理建议关单",
        defaults={
            "label": "外领域未按处理建议关单",
            "status": True,
            "sort": 5,
            "remark": "DTS-漏测原因选项",
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("project_manager", "0051_project_release_plan"),
    ]

    operations = [
        migrations.RunPython(
            seed_dts_test_miss_reason_outer_domain,
            migrations.RunPython.noop,
        ),
    ]
