# Generated by Django 5.2.7 on 2026-04-07 20:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0009_alter_permission_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="McuPlatform",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="平台名称"
                    ),
                ),
                (
                    "version_code",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="版本标识"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCU平台",
                "verbose_name_plural": "MCU平台",
                "db_table": "atr_mcu_platform",
            },
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="车型名称")),
                (
                    "vehicle_code",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="车型编号"
                    ),
                ),
                (
                    "cdc_platform",
                    models.CharField(max_length=128, verbose_name="CDC平台"),
                ),
                (
                    "execution_machine",
                    models.CharField(max_length=255, verbose_name="执行机器"),
                ),
                (
                    "report_token",
                    models.CharField(max_length=128, verbose_name="上报令牌"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="auto_test_report.mcuplatform",
                        verbose_name="MCU平台",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "车型",
                "verbose_name_plural": "车型",
                "db_table": "atr_vehicle_model",
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                ("case_no", models.CharField(max_length=128, verbose_name="用例编号")),
                (
                    "case_name",
                    models.CharField(max_length=255, verbose_name="用例名称"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="auto_test_report.vehiclemodel",
                        verbose_name="车型",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试用例",
                "verbose_name_plural": "测试用例",
                "db_table": "atr_test_case",
            },
        ),
        migrations.CreateModel(
            name="DailyExecutionResult",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                ("execute_date", models.DateField(verbose_name="执行日期")),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                (
                    "duration_seconds",
                    models.IntegerField(default=0, verbose_name="执行时长(秒)"),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("timeout", "超时"),
                        ],
                        max_length=16,
                        verbose_name="执行结果",
                    ),
                ),
                (
                    "log_url",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="运行日志URL",
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(auto_now=True, verbose_name="上报时间"),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_results",
                        to="auto_test_report.testcase",
                        verbose_name="测试用例",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_results",
                        to="auto_test_report.vehiclemodel",
                        verbose_name="车型",
                    ),
                ),
            ],
            options={
                "verbose_name": "每日执行结果",
                "verbose_name_plural": "每日执行结果",
                "db_table": "atr_daily_execution_result",
            },
        ),
        migrations.CreateModel(
            name="DailyExecutionBatch",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                ("execute_date", models.DateField(verbose_name="执行日期")),
                (
                    "total_count",
                    models.IntegerField(default=0, verbose_name="总用例数"),
                ),
                (
                    "success_count",
                    models.IntegerField(default=0, verbose_name="成功数"),
                ),
                ("failed_count", models.IntegerField(default=0, verbose_name="失败数")),
                (
                    "timeout_count",
                    models.IntegerField(default=0, verbose_name="超时数"),
                ),
                ("skip_count", models.IntegerField(default=0, verbose_name="跳过数")),
                (
                    "total_duration_seconds",
                    models.IntegerField(default=0, verbose_name="总时长(秒)"),
                ),
                (
                    "last_report_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近上报时间"
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_batches",
                        to="auto_test_report.vehiclemodel",
                        verbose_name="车型",
                    ),
                ),
            ],
            options={
                "verbose_name": "每日执行批次",
                "verbose_name_plural": "每日执行批次",
                "db_table": "atr_daily_execution_batch",
            },
        ),
        migrations.AddConstraint(
            model_name="vehiclemodel",
            constraint=models.UniqueConstraint(
                fields=("platform", "name"), name="uniq_atr_platform_vehicle_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="testcase",
            constraint=models.UniqueConstraint(
                fields=("vehicle", "case_no"), name="uniq_atr_vehicle_case_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyexecutionresult",
            constraint=models.UniqueConstraint(
                fields=("vehicle", "execute_date", "test_case"),
                name="uniq_atr_vehicle_date_case",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyexecutionbatch",
            constraint=models.UniqueConstraint(
                fields=("vehicle", "execute_date"), name="uniq_atr_vehicle_execute_date"
            ),
        ),
    ]
