# Generated by Django 5.2.7 on 2026-04-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auto_test_report", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehiclemodel",
            name="report_token",
        ),
    ]
