# Generated by Django 5.2.7 on 2026-04-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test_report', '0003_dailyexecutionresult_history_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
