# Generated by Codex on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_test_report', '0007_alter_dailyexecutionresult_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexecutionresult',
            name='failure_category',
            field=models.CharField(
                blank=True,
                choices=[
                    ('version', '版本问题'),
                    ('environment', '环境问题'),
                    ('case', '用例问题'),
                ],
                db_index=True,
                max_length=32,
                null=True,
                verbose_name='失败根因大类',
            ),
        ),
    ]
