# Generated by Django 5.2.7 on 2026-07-01 22:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_test_report", "0008_dailyexecutionresult_failure_category"),
        ("core", "0009_alter_permission_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownstreamCommit",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                (
                    "commit_id",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Commit ID"
                    ),
                ),
                (
                    "first_uploaded_at",
                    models.DateTimeField(verbose_name="首次上传时间"),
                ),
                ("last_uploaded_at", models.DateTimeField(verbose_name="最近上传时间")),
                (
                    "upload_count",
                    models.IntegerField(default=1, verbose_name="上传次数"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="来源"
                    ),
                ),
                (
                    "build_url",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="构建链接"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近使用时间"
                    ),
                ),
                ("use_count", models.IntegerField(default=0, verbose_name="使用次数")),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "下游Commit",
                "verbose_name_plural": "下游Commit",
                "db_table": "atr_downstream_commit",
            },
        ),
        migrations.CreateModel(
            name="DownstreamCommitUsage",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                ("execute_date", models.DateField(verbose_name="执行日期")),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[("manual", "人工触发"), ("scheduled", "定时触发")],
                        max_length=16,
                        verbose_name="触发方式",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(default=False, verbose_name="是否成功"),
                ),
                (
                    "dry_run",
                    models.BooleanField(default=True, verbose_name="是否占位调用"),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="触发消息"),
                ),
                ("used_at", models.DateTimeField(verbose_name="使用时间")),
                (
                    "commit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="auto_test_report.downstreamcommit",
                        verbose_name="Commit记录",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
                (
                    "trigger_user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auto_test_report_downstream_commit_usages",
                        to="core.user",
                        verbose_name="触发人",
                    ),
                ),
            ],
            options={
                "verbose_name": "下游Commit使用记录",
                "verbose_name_plural": "下游Commit使用记录",
                "db_table": "atr_downstream_commit_usage",
            },
        ),
        migrations.AddIndex(
            model_name="downstreamcommit",
            index=models.Index(
                fields=["last_uploaded_at"], name="idx_atr_commit_uploaded"
            ),
        ),
        migrations.AddIndex(
            model_name="downstreamcommit",
            index=models.Index(
                fields=["use_count", "last_uploaded_at"], name="idx_atr_commit_unused"
            ),
        ),
        migrations.AddIndex(
            model_name="downstreamcommitusage",
            index=models.Index(
                fields=["commit", "used_at"], name="idx_atr_commit_usage_commit"
            ),
        ),
        migrations.AddIndex(
            model_name="downstreamcommitusage",
            index=models.Index(
                fields=["execute_date", "trigger_type"],
                name="idx_atr_commit_usage_date",
            ),
        ),
    ]
