# Generated by Django 5.2.7 on 2026-01-12 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_user_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='项目描述')),
                ('project_category', models.CharField(blank=True, max_length=50, null=True, verbose_name='项目分类')),
                ('project_owner', models.CharField(blank=True, max_length=50, null=True, verbose_name='项目责任人')),
                ('codecheck_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='CodeCheck ID')),
                ('binscope_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='BinScope ID')),
                ('cooddy_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cooddy ID')),
                ('compiletion_check_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Compilation Check ID')),
                ('build_check_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Build Check ID')),
                ('build_project_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Build Project ID')),
                ('codecov_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='CodeCov ID')),
                ('fossbot_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='FossBot ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目配置',
                'verbose_name_plural': '项目配置',
                'db_table': 'ci_project_config',
            },
        ),
        migrations.CreateModel(
            name='ProjectDailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='数据日期')),
                ('test_cases_count', models.IntegerField(default=0, verbose_name='测试用例数')),
                ('test_cases_passed', models.IntegerField(default=0, verbose_name='用例通过数')),
                ('compile_standard_options', models.JSONField(blank=True, default=dict, verbose_name='编译规范选项')),
                ('build_standard_options', models.JSONField(blank=True, default=dict, verbose_name='构建规范选项')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='其他数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='采集时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='ci_daily_report.projectconfig', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目每日数据',
                'verbose_name_plural': '项目每日数据',
                'db_table': 'ci_project_daily_data',
                'ordering': ['-date'],
                'unique_together': {('project', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='订阅时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='ci_daily_report.projectconfig', verbose_name='订阅项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.user', verbose_name='订阅用户')),
            ],
            options={
                'verbose_name': '用户订阅',
                'verbose_name_plural': '用户订阅',
                'db_table': 'ci_subscription',
                'unique_together': {('user', 'project')},
            },
        ),
    ]
