# Generated by Django 5.2.7 on 2026-06-17 13:00

import json

import django.db.models.deletion
import uuid
from django.db import migrations, models


def migrate_legacy_environment_text(apps, schema_editor):
    TestEnvironment = apps.get_model('environment_management', 'TestEnvironment')
    for env in TestEnvironment.objects.all():
        config = getattr(env, 'config', None) or {}
        legacy_parts = []
        device_material = (getattr(env, 'device_material', '') or '').strip()
        asset_number = (getattr(env, 'asset_number', '') or '').strip()
        if device_material:
            legacy_parts.append(f'历史测试设备：{device_material}')
        if asset_number:
            legacy_parts.append(f'历史资产编号：{asset_number}')
        env.config_description = json.dumps(config, ensure_ascii=False) if config else ''
        env.remark = '\n'.join(legacy_parts)
        env.save(update_fields=['config_description', 'remark'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_permission_code'),
        ('environment_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testenvironment',
            name='config_description',
            field=models.TextField(blank=True, default='', verbose_name='配置情况'),
        ),
        migrations.AddField(
            model_name='testenvironment',
            name='remark',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
        migrations.RunPython(migrate_legacy_environment_text, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='testenvironment',
            name='asset_number',
        ),
        migrations.RemoveField(
            model_name='testenvironment',
            name='config',
        ),
        migrations.RemoveField(
            model_name='testenvironment',
            name='device_material',
        ),
        migrations.CreateModel(
            name='EnvironmentDeviceType',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('name', models.CharField(max_length=100, verbose_name='类型名称')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='environment_management.environmentdevicetype', verbose_name='父级类型')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '测试设备类型',
                'verbose_name_plural': '测试设备类型',
                'db_table': 'environment_management_device_type',
                'ordering': ['sort', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentTestDevice',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='environment_management.environmentdevicetype', verbose_name='设备类型')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '测试设备',
                'verbose_name_plural': '测试设备',
                'db_table': 'environment_management_test_device',
                'ordering': ['device_type__sort', 'sort', 'name'],
            },
        ),
        migrations.AddField(
            model_name='testenvironment',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='environments', to='environment_management.environmenttestdevice', verbose_name='测试设备'),
        ),
        migrations.AddIndex(
            model_name='environmentdevicetype',
            index=models.Index(fields=['parent', 'is_active'], name='environment_parent__5c91d9_idx'),
        ),
        migrations.AddIndex(
            model_name='environmentdevicetype',
            index=models.Index(fields=['name'], name='environment_name_212c30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='environmentdevicetype',
            unique_together={('parent', 'name')},
        ),
        migrations.AddIndex(
            model_name='environmenttestdevice',
            index=models.Index(fields=['device_type', 'is_active'], name='environment_device__9abfbf_idx'),
        ),
        migrations.AddIndex(
            model_name='environmenttestdevice',
            index=models.Index(fields=['name'], name='environment_name_102784_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='environmenttestdevice',
            unique_together={('device_type', 'name')},
        ),
    ]
