# Generated by Codex on 2026-06-17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_permission_code'),
        ('environment_management', '0002_remove_testenvironment_asset_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentAnnouncement',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='公告标题')),
                ('content_html', models.TextField(blank=True, default='', verbose_name='公告内容')),
                ('enabled', models.BooleanField(db_index=True, default=False, verbose_name='是否启用')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '环境操作公告',
                'verbose_name_plural': '环境操作公告',
                'db_table': 'environment_management_announcement',
            },
        ),
    ]
