# Generated by Django 5.2.7 on 2026-01-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_matrix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydomain',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='projectcomponent',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
