# Generated by Django 5.2.7 on 2026-02-08 22:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_manager'),
        ('delivery_matrix', '0002_deliverydomain_remark_projectcomponent_remark_and_more'),
        ('project_manager', '0012_milestoneqgconfig_is_delayed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectgroup',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='projectcomponent',
            name='group',
        ),
        migrations.RemoveField(
            model_name='projectcomponent',
            name='linked_project',
        ),
        migrations.RemoveField(
            model_name='projectcomponent',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='projectcomponent',
            name='sys_creator',
        ),
        migrations.RemoveField(
            model_name='projectcomponent',
            name='sys_modifier',
        ),
        migrations.RemoveField(
            model_name='projectgroup',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='projectgroup',
            name='sys_creator',
        ),
        migrations.RemoveField(
            model_name='projectgroup',
            name='sys_modifier',
        ),
        migrations.CreateModel(
            name='OrganizationNode',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='编码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('linked_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_nodes', to='project_manager.project', verbose_name='关联项目')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='delivery_matrix.organizationnode', verbose_name='父节点')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '组织节点',
                'verbose_name_plural': '组织节点',
                'db_table': 'dm_org_node',
                'ordering': ['sort_order', 'sys_create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='PositionStaff',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('name', models.CharField(max_length=100, verbose_name='岗位名称')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='delivery_matrix.organizationnode', verbose_name='所属节点')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
                ('users', models.ManyToManyField(blank=True, related_name='delivery_positions', to='core.user', verbose_name='关联人员')),
            ],
            options={
                'verbose_name': '岗位人员',
                'verbose_name_plural': '岗位人员',
                'db_table': 'dm_position_staff',
                'unique_together': {('node', 'name')},
            },
        ),
        migrations.DeleteModel(
            name='DeliveryDomain',
        ),
        migrations.DeleteModel(
            name='ProjectComponent',
        ),
        migrations.DeleteModel(
            name='ProjectGroup',
        ),
    ]
