# Generated by Django 5.2.7 on 2026-02-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_matrix', '0003_remove_projectgroup_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionstaff',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='岗位描述'),
        ),
    ]
