# Generated by Django 5.2.7 on 2026-02-09 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_matrix', '0004_positionstaff_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionstaff',
            name='description',
        ),
    ]
