# Generated by Django 5.2.7 on 2026-01-14 00:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_user_manager'),
        ('project_manager', '0009_remove_iterationmetric_completed_workload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationEmailDelivery',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('record_date', models.DateField(verbose_name='数据日期')),
                ('to_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='收件邮箱')),
                ('subject', models.CharField(max_length=255, verbose_name='邮件主题')),
                ('status', models.CharField(default='pending', max_length=16, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_deliveries', to='core.user', verbose_name='收件人')),
            ],
            options={
                'verbose_name': '每日集成报告邮件投递',
                'verbose_name_plural': '每日集成报告邮件投递',
                'db_table': 'ir_email_delivery',
            },
        ),
        migrations.CreateModel(
            name='IntegrationMetricDefinition',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('group', models.CharField(max_length=64, verbose_name='分组')),
                ('key', models.CharField(max_length=128, unique=True, verbose_name='指标Key')),
                ('name', models.CharField(max_length=128, verbose_name='指标名称')),
                ('value_type', models.CharField(default='number', max_length=32, verbose_name='值类型')),
                ('unit', models.CharField(blank=True, default='', max_length=16, verbose_name='单位')),
                ('warn_operator', models.CharField(blank=True, default='', max_length=8, verbose_name='预警操作符')),
                ('warn_value', models.FloatField(blank=True, null=True, verbose_name='预警阈值')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '每日集成报告指标定义',
                'verbose_name_plural': '每日集成报告指标定义',
                'db_table': 'ir_metric_definition',
            },
        ),
        migrations.CreateModel(
            name='IntegrationProjectConfig',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('code_check_task_id', models.CharField(blank=True, default='', max_length=128, verbose_name='代码检测任务ID')),
                ('bin_scope_task_id', models.CharField(blank=True, default='', max_length=128, verbose_name='二进制范围任务ID')),
                ('build_check_task_id', models.CharField(blank=True, default='', max_length=128, verbose_name='构建检测任务ID')),
                ('compile_check_task_id', models.CharField(blank=True, default='', max_length=128, verbose_name='编译检测任务ID')),
                ('dt_project_id', models.CharField(blank=True, default='', max_length=128, verbose_name='DT项目ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration_report_config', to='project_manager.project', verbose_name='项目')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '每日集成报告项目配置',
                'verbose_name_plural': '每日集成报告项目配置',
                'db_table': 'ir_project_config',
            },
        ),
        migrations.CreateModel(
            name='IntegrationEmailSubscription',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_subscriptions', to='project_manager.project', verbose_name='订阅项目')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_subscriptions', to='core.user', verbose_name='订阅人')),
            ],
            options={
                'verbose_name': '每日集成报告邮件订阅',
                'verbose_name_plural': '每日集成报告邮件订阅',
                'db_table': 'ir_email_subscription',
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationProjectMetricValue',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('value_number', models.FloatField(blank=True, null=True, verbose_name='数值')),
                ('value_text', models.CharField(blank=True, default='', max_length=255, verbose_name='文本值')),
                ('detail_url', models.CharField(blank=True, default='', max_length=512, verbose_name='详情URL')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='integration_report.integrationmetricdefinition', verbose_name='指标')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_metrics', to='project_manager.project', verbose_name='项目')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '每日集成报告项目指标值',
                'verbose_name_plural': '每日集成报告项目指标值',
                'db_table': 'ir_project_metric_value',
                'unique_together': {('project', 'record_date', 'metric')},
            },
        ),
    ]
