# Generated by Django 5.2.7 on 2026-03-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integration_report", "0003_integrationprojectconfig_code_scan_project_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationprojectconfig",
            name="valgrind_sub_modules",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="Valgrind子模块列表",
            ),
        ),
    ]
