# Generated by Django 5.2.7 on 2026-04-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integration_report", "0004_integrationprojectconfig_valgrind_sub_modules"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationprojectconfig",
            name="cooddy_check_task_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                verbose_name="Cooddy Check任务ID",
            ),
        ),
        migrations.AddField(
            model_name="integrationprojectconfig",
            name="dt_bin_task_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                verbose_name="DT_Bin任务ID",
            ),
        ),
    ]
