# Generated by Django 5.2.7 on 2026-07-21 00:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0009_alter_permission_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="CmcContributionDailyRecord",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                (
                    "statistic_date",
                    models.DateField(db_index=True, verbose_name="统计日期"),
                ),
                (
                    "user_name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="人员姓名"
                    ),
                ),
                (
                    "cnt_total",
                    models.IntegerField(default=0, verbose_name="合入MR总数"),
                ),
                (
                    "major_comments_cnt",
                    models.IntegerField(default=0, verbose_name="严重检视意见数"),
                ),
                (
                    "fatal_comments_cnt",
                    models.IntegerField(default=0, verbose_name="致命检视意见数"),
                ),
                (
                    "minor_comments_cnt",
                    models.IntegerField(default=0, verbose_name="一般检视意见数"),
                ),
                (
                    "sugge_comments_cnt",
                    models.IntegerField(default=0, verbose_name="建议检视意见数"),
                ),
                (
                    "cmt_issue",
                    models.IntegerField(default=0, verbose_name="提交Issue总数"),
                ),
                (
                    "checked_mr_lines",
                    models.IntegerField(default=0, verbose_name="检视代码行数"),
                ),
                (
                    "cmt_lines",
                    models.IntegerField(default=0, verbose_name="提交MR代码量"),
                ),
                (
                    "not_0_comment_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=7,
                        verbose_name="零检视MR比例",
                    ),
                ),
                (
                    "zero_comment_mr_count",
                    models.IntegerField(default=0, verbose_name="零检视MR数"),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="上游原始行"
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "cmc_contribution_daily_record",
                "ordering": ("-statistic_date", "user_name"),
                "indexes": [
                    models.Index(
                        fields=["statistic_date", "user_name"],
                        name="cmc_contrib_day_user_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("statistic_date", "user_name"),
                        name="cmc_contribution_daily_user_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CmcContributionSyncTask",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[("scheduled", "定时"), ("manual", "手动")],
                        db_index=True,
                        max_length=16,
                        verbose_name="触发方式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="任务状态",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                (
                    "requested_dates",
                    models.JSONField(blank=True, default=list, verbose_name="请求日期"),
                ),
                (
                    "fetched_pages",
                    models.IntegerField(default=0, verbose_name="拉取页数"),
                ),
                (
                    "fetched_rows",
                    models.IntegerField(default=0, verbose_name="拉取行数"),
                ),
                (
                    "synced_dates",
                    models.JSONField(blank=True, default=list, verbose_name="成功日期"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cmc_contribution_sync_tasks",
                        to="core.user",
                        verbose_name="发起用户",
                    ),
                ),
            ],
            options={
                "db_table": "cmc_contribution_sync_task",
                "ordering": ("-sys_create_datetime",),
                "indexes": [
                    models.Index(
                        fields=["status", "trigger_type"],
                        name="cmc_contrib_task_status_idx",
                    )
                ],
            },
        ),
    ]
