# Generated by Django 5.2.7 on 2026-07-26 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmc_contribution", "0001_cmc_contribution_initial"),
        ("core", "0009_alter_permission_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmccontributiondailyrecord",
            name="merged_login",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=150,
                verbose_name="数据湖登录名",
            ),
        ),
        migrations.AddField(
            model_name="cmccontributiondailyrecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cmc_contribution_daily_records",
                to="core.user",
                verbose_name="系统用户",
            ),
        ),
    ]
