# Generated by Django 5.2.7 on 2026-07-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmc_contribution", "0002_link_core_user"),
        ("core", "0009_alter_permission_code"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cmccontributiondailyrecord",
            name="cmc_contribution_daily_user_uniq",
        ),
        migrations.RemoveIndex(
            model_name="cmccontributiondailyrecord",
            name="cmc_contrib_day_user_idx",
        ),
        migrations.AddIndex(
            model_name="cmccontributiondailyrecord",
            index=models.Index(
                fields=["statistic_date", "user"], name="cmc_contrib_day_user_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cmccontributiondailyrecord",
            constraint=models.UniqueConstraint(
                fields=("statistic_date", "user"),
                name="cmc_contribution_daily_user_uniq",
            ),
        ),
    ]
