# Generated by Django 5.2.7 on 2026-01-11 23:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_user_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubscriptionConfig',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('name', models.CharField(help_text='项目名称', max_length=100, unique=True)),
                ('codecheck_id', models.CharField(blank=True, help_text='CodeCheck ID', max_length=100, null=True)),
                ('binscope_id', models.CharField(blank=True, help_text='BinScope ID', max_length=100, null=True)),
                ('cooddy_id', models.CharField(blank=True, help_text='Cooddy ID', max_length=100, null=True)),
                ('compiletion_check_id', models.CharField(blank=True, help_text='Compilation Check ID', max_length=100, null=True)),
                ('build_check_id', models.CharField(blank=True, help_text='Build Check ID', max_length=100, null=True)),
                ('build_project_id', models.CharField(blank=True, help_text='Build Project ID', max_length=100, null=True)),
                ('codecov_id', models.CharField(blank=True, help_text='CodeCov ID', max_length=100, null=True)),
                ('fossbot_id', models.CharField(blank=True, help_text='Fossbot ID', max_length=100, null=True)),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '项目订阅配置',
                'verbose_name_plural': '项目订阅配置',
                'db_table': 'mail_project_config',
            },
        ),
        migrations.CreateModel(
            name='ProjectDailyData',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('date', models.DateField(db_index=True, help_text='数据日期')),
                ('test_cases_count', models.IntegerField(default=0, help_text='测试用例数')),
                ('test_cases_passed', models.IntegerField(default=0, help_text='用例通过数')),
                ('build_norm_options', models.JSONField(blank=True, default=dict, help_text='构建规范选项数据')),
                ('compile_norm_options', models.JSONField(blank=True, default=dict, help_text='编译规范选项数据')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='原始数据')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
                ('project', models.ForeignKey(db_constraint=False, help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='mail_subscription.projectsubscriptionconfig')),
            ],
            options={
                'verbose_name': '项目每日数据',
                'verbose_name_plural': '项目每日数据',
                'db_table': 'mail_project_daily_data',
                'ordering': ['-date'],
                'unique_together': {('project', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('project', models.ForeignKey(db_constraint=False, help_text='订阅项目', on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='mail_subscription.projectsubscriptionconfig')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
                ('user', models.ForeignKey(db_constraint=False, help_text='订阅用户', on_delete=django.db.models.deletion.CASCADE, related_name='project_subscriptions', to='core.user')),
            ],
            options={
                'verbose_name': '用户项目订阅',
                'verbose_name_plural': '用户项目订阅',
                'db_table': 'mail_user_subscription',
                'unique_together': {('user', 'project')},
            },
        ),
    ]
