// 兼容旧 import：新代码请统一使用 `@/shared/constants`
export {
  PROJECT_DETAIL_REQUEST_TIMEOUT_MS as REQUEST_TIMEOUT_MS,
  PROJECT_DETAIL_ISSUES_MAX_TASKS as ISSUES_MAX_TASKS,
  PROJECT_DETAIL_ISSUES_FETCH_CONCURRENCY as ISSUES_FETCH_CONCURRENCY,
} from "@/shared/constants";


