# Generated by Django 5.2.7 on 2026-02-04 00:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_user_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='TScanProject',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('name', models.CharField(help_text='项目名称', max_length=100, verbose_name='项目名称')),
                ('repo_url', models.CharField(help_text='代码仓地址', max_length=255, verbose_name='代码仓地址')),
                ('branch', models.CharField(default='master', help_text='分支', max_length=100, verbose_name='分支')),
                ('build_cmd', models.TextField(help_text='编译命令，例如: make -j4', verbose_name='编译命令')),
                ('docker_image', models.CharField(help_text='用于编译和扫描的Docker镜像', max_length=255, verbose_name='Docker镜像')),
                ('description', models.TextField(blank=True, help_text='项目描述', null=True, verbose_name='描述')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': 'TScan项目',
                'verbose_name_plural': 'TScan项目',
                'db_table': 'tscan_project',
                'ordering': ['-sys_create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='TScanResult',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('line_number', models.IntegerField(verbose_name='行号')),
                ('defect_type', models.CharField(max_length=100, verbose_name='缺陷类型')),
                ('severity', models.CharField(choices=[('High', '高'), ('Medium', '中'), ('Low', '低')], max_length=20, verbose_name='严重程度')),
                ('description', models.TextField(verbose_name='缺陷描述')),
                ('fingerprint', models.CharField(db_index=True, max_length=255, verbose_name='缺陷指纹')),
                ('shield_status', models.CharField(choices=[('Normal', '正常'), ('Pending', '屏蔽申请中'), ('Shielded', '已屏蔽'), ('Rejected', '已驳回')], default='Normal', max_length=20, verbose_name='屏蔽状态')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': 'TScan结果',
                'verbose_name_plural': 'TScan结果',
                'db_table': 'tscan_result',
                'ordering': ['-severity', 'file_path'],
            },
        ),
        migrations.CreateModel(
            name='TScanShieldApplication',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('reason', models.TextField(verbose_name='屏蔽理由')),
                ('status', models.CharField(choices=[('Pending', '待审批'), ('Approved', '已通过'), ('Rejected', '已驳回')], default='Pending', max_length=20, verbose_name='申请状态')),
                ('audit_comment', models.TextField(blank=True, null=True, verbose_name='审批意见')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tscan_applications', to='core.user', verbose_name='申请人')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tscan_audits', to='core.user', verbose_name='审批人')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shield_applications', to='tscan.tscanresult', verbose_name='关联结果')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': 'TScan屏蔽申请',
                'verbose_name_plural': 'TScan屏蔽申请',
                'db_table': 'tscan_shield_application',
                'ordering': ['-sys_create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='TScanTask',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('log', models.TextField(blank=True, null=True, verbose_name='执行日志')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tscan.tscanproject', verbose_name='项目')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
                ('trigger_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user', verbose_name='触发人')),
            ],
            options={
                'verbose_name': 'TScan任务',
                'verbose_name_plural': 'TScan任务',
                'db_table': 'tscan_task',
                'ordering': ['-sys_create_datetime'],
            },
        ),
        migrations.AddField(
            model_name='tscanresult',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tscan.tscantask', verbose_name='任务'),
        ),
    ]
