# Generated by Django 5.2.7 on 2026-09-05 00:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0009_alter_permission_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernanceProject",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="项目名称")),
                (
                    "code",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="项目编码"
                    ),
                ),
                (
                    "repository",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="仓库地址"
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True,
                        default="master",
                        max_length=160,
                        verbose_name="默认分支",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "agent_tools_governance_project",
                "ordering": ["is_deleted", "-sort", "name"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceProjectResponsibility",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="关联备注"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsibility_links",
                        to="code_quality_governance.governanceproject",
                        verbose_name="项目",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "agent_tools_governance_project_responsibility",
                "ordering": [
                    "is_deleted",
                    "-sort",
                    "project__name",
                    "responsibility__name",
                ],
            },
        ),
        migrations.CreateModel(
            name="GovernanceFinding",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                (
                    "identity_key",
                    models.CharField(max_length=512, verbose_name="平台稳定身份"),
                ),
                (
                    "issue_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="工具 issue_key",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True, default="", max_length=512, verbose_name="指纹"
                    ),
                ),
                (
                    "rule_id",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="规则 ID"
                    ),
                ),
                (
                    "rule_version",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="规则版本"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", max_length=160, verbose_name="问题类别"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("blocker", "Blocker"),
                            ("critical", "Critical"),
                            ("major", "Major"),
                            ("minor", "Minor"),
                            ("info", "Info"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=20,
                        verbose_name="严重级别",
                    ),
                ),
                (
                    "shield_status",
                    models.CharField(
                        choices=[
                            ("Normal", "正常"),
                            ("Pending", "屏蔽申请中"),
                            ("Shielded", "已屏蔽"),
                            ("Rejected", "已驳回"),
                        ],
                        db_index=True,
                        default="Normal",
                        max_length=20,
                        verbose_name="屏蔽状态",
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="首次发现时间",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="最近发现时间",
                    ),
                ),
                (
                    "latest_tool_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="最近扫描工具",
                    ),
                ),
                (
                    "latest_file_path",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="最近文件路径",
                    ),
                ),
                (
                    "latest_line",
                    models.PositiveIntegerField(default=0, verbose_name="最近行号"),
                ),
                (
                    "latest_message",
                    models.TextField(
                        blank=True, default="", verbose_name="最近问题描述"
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
                (
                    "project_responsibility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="code_quality_governance.governanceprojectresponsibility",
                        verbose_name="项目责任田",
                    ),
                ),
            ],
            options={
                "db_table": "agent_tools_governance_finding",
                "ordering": ["severity", "-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceResponsibility",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="责任田名称")),
                (
                    "code",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="责任田编码"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "approvers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="governance_responsibility_approvers",
                        to="core.user",
                        verbose_name="审批人员",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="governance_responsibility_owned",
                        to="core.user",
                        verbose_name="负责人",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "agent_tools_governance_responsibility",
                "ordering": ["is_deleted", "-sort", "name"],
            },
        ),
        migrations.AddField(
            model_name="governanceprojectresponsibility",
            name="responsibility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_links",
                to="code_quality_governance.governanceresponsibility",
                verbose_name="责任田",
            ),
        ),
        migrations.CreateModel(
            name="GovernanceScanReport",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                (
                    "repository",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="报告仓库"
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(max_length=120, verbose_name="扫描工具"),
                ),
                (
                    "complete",
                    models.BooleanField(default=True, verbose_name="扫描是否完成"),
                ),
                (
                    "raw_created_at",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=80,
                        verbose_name="原始创建时间",
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(default=dict, verbose_name="原始 JSON"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "解析中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="processing",
                        max_length=20,
                        verbose_name="解析状态",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("upload", "页面上传"), ("api", "接口接入")],
                        default="api",
                        max_length=20,
                        verbose_name="接入来源",
                    ),
                ),
                (
                    "finding_count",
                    models.PositiveIntegerField(default=0, verbose_name="问题数"),
                ),
                (
                    "blocker_count",
                    models.PositiveIntegerField(default=0, verbose_name="Blocker 数"),
                ),
                (
                    "critical_count",
                    models.PositiveIntegerField(default=0, verbose_name="Critical 数"),
                ),
                (
                    "major_count",
                    models.PositiveIntegerField(default=0, verbose_name="Major 数"),
                ),
                (
                    "minor_count",
                    models.PositiveIntegerField(default=0, verbose_name="Minor 数"),
                ),
                (
                    "info_count",
                    models.PositiveIntegerField(default=0, verbose_name="Info 数"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解析完成时间"
                    ),
                ),
                (
                    "project_responsibility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="code_quality_governance.governanceprojectresponsibility",
                        verbose_name="项目责任田",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "agent_tools_governance_scan_report",
                "ordering": ["-sys_create_datetime"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceFindingOccurrence",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="文件路径"
                    ),
                ),
                (
                    "start_line",
                    models.PositiveIntegerField(default=0, verbose_name="起始行"),
                ),
                (
                    "end_line",
                    models.PositiveIntegerField(default=0, verbose_name="结束行"),
                ),
                (
                    "message",
                    models.TextField(blank=True, default="", verbose_name="问题描述"),
                ),
                ("evidence", models.JSONField(default=list, verbose_name="证据")),
                ("identity", models.JSONField(default=dict, verbose_name="身份数据")),
                (
                    "legacy_fingerprints",
                    models.JSONField(default=list, verbose_name="历史指纹"),
                ),
                (
                    "confidence",
                    models.FloatField(blank=True, null=True, verbose_name="置信度"),
                ),
                (
                    "raw_finding",
                    models.JSONField(default=dict, verbose_name="原始 finding"),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrences",
                        to="code_quality_governance.governancefinding",
                        verbose_name="稳定问题",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrences",
                        to="code_quality_governance.governancescanreport",
                        verbose_name="扫描报告",
                    ),
                ),
            ],
            options={
                "db_table": "agent_tools_governance_finding_occurrence",
                "ordering": ["-sys_create_datetime"],
            },
        ),
        migrations.AddField(
            model_name="governancefinding",
            name="first_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="first_findings",
                to="code_quality_governance.governancescanreport",
                verbose_name="首次扫描报告",
            ),
        ),
        migrations.AddField(
            model_name="governancefinding",
            name="last_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_findings",
                to="code_quality_governance.governancescanreport",
                verbose_name="最近扫描报告",
            ),
        ),
        migrations.CreateModel(
            name="GovernanceShieldApplication",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                ("reason", models.TextField(verbose_name="屏蔽理由")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "待审批"),
                            ("Approved", "已通过"),
                            ("Rejected", "已驳回"),
                        ],
                        db_index=True,
                        default="Pending",
                        max_length=20,
                        verbose_name="申请状态",
                    ),
                ),
                (
                    "audit_comment",
                    models.TextField(blank=True, default="", verbose_name="审批意见"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="governance_applications",
                        to="core.user",
                        verbose_name="申请人",
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="governance_approvals",
                        to="core.user",
                        verbose_name="指定审批人",
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shield_applications",
                        to="code_quality_governance.governancefinding",
                        verbose_name="稳定问题",
                    ),
                ),
                (
                    "project_responsibility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shield_applications",
                        to="code_quality_governance.governanceprojectresponsibility",
                        verbose_name="项目责任田",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "agent_tools_governance_shield_application",
                "ordering": ["-sys_create_datetime"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceShieldAuditLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="主键ID",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sys_create_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="创建时间"
                    ),
                ),
                (
                    "sys_update_datetime",
                    models.DateTimeField(
                        auto_now=True, db_index=True, help_text="更新时间"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="是否删除（软删除标识）"
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(
                        db_index=True, default=0, help_text="排序（数字越大越靠前）"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "提交申请"),
                            ("approve", "审批通过"),
                            ("reject", "审批驳回"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="原状态"
                    ),
                ),
                ("to_status", models.CharField(max_length=20, verbose_name="新状态")),
                (
                    "comment",
                    models.TextField(blank=True, default="", verbose_name="操作说明"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="code_quality_governance.governanceshieldapplication",
                        verbose_name="申请单",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="governance_audit_logs",
                        to="core.user",
                        verbose_name="操作人",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to="core.user",
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "agent_tools_governance_shield_audit_log",
                "ordering": ["sys_create_datetime"],
            },
        ),
        migrations.AddConstraint(
            model_name="governanceprojectresponsibility",
            constraint=models.UniqueConstraint(
                fields=("project", "responsibility"),
                name="governance_project_resp_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="governancescanreport",
            index=models.Index(
                fields=["project_responsibility", "-sys_create_datetime"],
                name="governance_report_scope_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="governancescanreport",
            index=models.Index(
                fields=["status", "-sys_create_datetime"],
                name="governance_report_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="governancefindingoccurrence",
            index=models.Index(
                fields=["report", "finding"], name="gov_occ_report_find_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="governancefindingoccurrence",
            index=models.Index(
                fields=["file_path", "start_line"], name="gov_occ_location_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="governancefinding",
            index=models.Index(
                fields=["project_responsibility", "shield_status"],
                name="governance_finding_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="governancefinding",
            index=models.Index(
                fields=["project_responsibility", "-last_seen_at"],
                name="governance_finding_seen_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="governancefinding",
            constraint=models.UniqueConstraint(
                fields=("project_responsibility", "identity_key"),
                name="governance_scope_identity_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="governanceshieldapplication",
            index=models.Index(
                fields=["approver", "status"], name="gov_app_approver_st_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="governanceshieldapplication",
            index=models.Index(
                fields=["finding", "status"], name="gov_app_finding_st_idx"
            ),
        ),
    ]
