# Generated by Django 5.2.7 on 2026-03-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepaudit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditissue',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='兼容消息'),
        ),
    ]
