# Generated by Django 5.2.7 on 2026-03-30 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_plgroup"),
        ("deepaudit", "0003_agentcheckpoint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agentcheckpoint",
            options={
                "verbose_name": "DeepAudit Agent 检查点",
                "verbose_name_plural": "DeepAudit Agent 检查点",
            },
        ),
        migrations.RenameIndex(
            model_name="agentcheckpoint",
            new_name="deepaudit_a_task_id_66c73e_idx",
            old_name="deepaudit_a_task_id_96a1b2_idx",
        ),
        migrations.RenameIndex(
            model_name="agentcheckpoint",
            new_name="deepaudit_a_task_id_c706c0_idx",
            old_name="deepaudit_a_task_id_35ef0e_idx",
        ),
        migrations.RenameIndex(
            model_name="agentcheckpoint",
            new_name="deepaudit_a_task_id_1aab6a_idx",
            old_name="deepaudit_a_task_id_4ee2b5_idx",
        ),
        migrations.AlterField(
            model_name="agentcheckpoint",
            name="sys_creator",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="创建人",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to="core.user",
            ),
        ),
        migrations.AlterField(
            model_name="agentcheckpoint",
            name="sys_modifier",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="修改人",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_modified",
                to="core.user",
            ),
        ),
    ]
