# Generated by Codex on 2026-05-12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepaudit', '0006_task_repository_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditScenarioProfile',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('scenario_key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='场景键')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='场景名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='场景描述')),
                ('objective_type', models.CharField(choices=[('audit', '漏洞审计'), ('inventory', '代码梳理')], db_index=True, default='audit', max_length=20, verbose_name='输出目标')),
                ('knowledge_modules', models.JSONField(blank=True, default=list, verbose_name='知识模块')),
                ('tool_policy', models.JSONField(blank=True, default=dict, verbose_name='工具策略')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='默认场景')),
                ('is_system', models.BooleanField(db_index=True, default=False, verbose_name='系统场景')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deepaudit_scenarios', to='core.user', verbose_name='创建人')),
                ('prompt_template', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deepaudit_scenarios', to='deepaudit.prompttemplate', verbose_name='提示词模板')),
                ('rule_set', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deepaudit_scenarios', to='deepaudit.auditruleset', verbose_name='规则集')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': 'DeepAudit 场景',
                'verbose_name_plural': 'DeepAudit 场景',
                'db_table': 'deepaudit_scenario_profile',
            },
        ),
    ]
