# Generated by Django 5.2.7 on 2026-07-16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepaudit', '0007_auditscenarioprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditGlobalEmbeddingConfig',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('config_key', models.CharField(default='default', max_length=64, unique=True, verbose_name='配置键')),
                ('provider', models.CharField(blank=True, default='', max_length=64, verbose_name='Embedding Provider')),
                ('model', models.CharField(blank=True, default='', max_length=255, verbose_name='Embedding 模型')),
                ('base_url', models.CharField(blank=True, default='', max_length=1024, verbose_name='Embedding 服务地址')),
                ('api_key_encrypted', models.TextField(blank=True, default='', verbose_name='加密后的 API Key')),
                ('dimensions', models.PositiveIntegerField(blank=True, null=True, verbose_name='向量维度')),
                ('batch_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='批处理大小')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': 'DeepAudit 全局 Embedding 配置',
                'verbose_name_plural': 'DeepAudit 全局 Embedding 配置',
                'db_table': 'deepaudit_global_embedding_config',
            },
        ),
    ]
