# Generated by Django 5.2.7 on 2026-02-04 23:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_user_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanProject',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('name', models.CharField(help_text='项目名称', max_length=100, verbose_name='项目名称')),
                ('repo_url', models.CharField(help_text='代码仓地址', max_length=255, verbose_name='代码仓地址')),
                ('branch', models.CharField(default='master', help_text='分支', max_length=100, verbose_name='分支')),
                ('project_key', models.CharField(default=uuid.uuid4, help_text='用于流水线认证的唯一标识', max_length=64, unique=True, verbose_name='项目标识')),
                ('description', models.TextField(blank=True, help_text='项目描述', null=True, verbose_name='描述')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '代码扫描项目',
                'verbose_name_plural': '代码扫描项目',
                'db_table': 'scan_project',
                'ordering': ['-sys_create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('tool_name', models.CharField(default='tscan', help_text='如: tscan, cppcheck', max_length=50, verbose_name='扫描工具')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '解析中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('source', models.CharField(choices=[('pipeline', '流水线上传'), ('manual', '手动触发')], default='manual', max_length=20, verbose_name='来源')),
                ('report_file', models.CharField(blank=True, max_length=500, null=True, verbose_name='报告文件路径')),
                ('log', models.TextField(blank=True, null=True, verbose_name='处理日志')),
                ('scan_time', models.DateTimeField(blank=True, null=True, verbose_name='扫描时间')),
                ('processed_time', models.DateTimeField(blank=True, null=True, verbose_name='解析完成时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='code_scan.scanproject', verbose_name='项目')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '扫描任务',
                'verbose_name_plural': '扫描任务',
                'db_table': 'scan_task',
                'ordering': ['-sys_create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('line_number', models.IntegerField(verbose_name='行号')),
                ('defect_type', models.CharField(max_length=100, verbose_name='缺陷类型')),
                ('severity', models.CharField(choices=[('High', '高'), ('Medium', '中'), ('Low', '低')], max_length=20, verbose_name='严重程度')),
                ('description', models.TextField(verbose_name='缺陷描述')),
                ('fingerprint', models.CharField(db_index=True, max_length=255, verbose_name='缺陷指纹')),
                ('shield_status', models.CharField(choices=[('Normal', '正常'), ('Pending', '屏蔽申请中'), ('Shielded', '已屏蔽'), ('Rejected', '已驳回')], default='Normal', max_length=20, verbose_name='屏蔽状态')),
                ('help_info', models.TextField(blank=True, null=True, verbose_name='修复建议')),
                ('code_snippet', models.TextField(blank=True, null=True, verbose_name='代码片段')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='code_scan.scantask', verbose_name='任务')),
            ],
            options={
                'verbose_name': '扫描结果',
                'verbose_name_plural': '扫描结果',
                'db_table': 'scan_result',
                'ordering': ['-severity', 'file_path'],
            },
        ),
        migrations.CreateModel(
            name='ShieldApplication',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('reason', models.TextField(verbose_name='屏蔽理由')),
                ('status', models.CharField(choices=[('Pending', '待审批'), ('Approved', '已通过'), ('Rejected', '已驳回')], default='Pending', max_length=20, verbose_name='申请状态')),
                ('audit_comment', models.TextField(blank=True, null=True, verbose_name='审批意见')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_applications', to='core.user', verbose_name='申请人')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_audits', to='core.user', verbose_name='审批人')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shield_applications', to='code_scan.scanresult', verbose_name='关联结果')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '屏蔽申请',
                'verbose_name_plural': '屏蔽申请',
                'db_table': 'scan_shield_application',
                'ordering': ['-sys_create_datetime'],
            },
        ),
    ]
