# Generated by Django 5.2.7 on 2026-02-06 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_scan', '0001_initial'),
        ('core', '0006_alter_user_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanproject',
            name='caretaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_projects', to='core.user', verbose_name='数据看护责任人'),
        ),
    ]
