# Generated by Django 5.2.7 on 2026-02-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_scan", "0002_scanproject_caretaker"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanproject",
            name="path_shield_prefixes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="按文件路径前缀自动屏蔽",
                verbose_name="路径前缀屏蔽规则",
            ),
        ),
    ]
