# Generated by Django 5.2.7 on 2026-03-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_scan", "0003_scanproject_path_shield_prefixes"),
    ]

    operations = [
        migrations.AddField(
            model_name="scantask",
            name="sub_module",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                verbose_name="子模块",
            ),
        ),
    ]
