# Generated by Django 5.2.7 on 2026-06-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_scan', '0005_normalized_scan_results'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scanfinding',
            new_name='scan_find_proj_status_idx',
            old_name='scan_find_project_status_idx',
        ),
        migrations.RenameIndex(
            model_name='scanfinding',
            new_name='scan_find_proj_last_seen_idx',
            old_name='scan_find_project_last_seen_idx',
        ),
    ]
