# Generated by Django 5.0.1 on 2026-03-04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Requirement",
            fields=[
                ("id", models.CharField(default=uuid.uuid4, editable=False, help_text="主键ID", max_length=36, primary_key=True, serialize=False)),
                ("sys_create_datetime", models.DateTimeField(auto_now_add=True, db_index=True, help_text="创建时间")),
                ("sys_update_datetime", models.DateTimeField(auto_now=True, db_index=True, help_text="更新时间")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, help_text="是否删除（软删除标识）")),
                ("sort", models.IntegerField(db_index=True, default=0, help_text="排序（数字越大越靠前）")),
                ("title", models.CharField(db_index=True, max_length=255, verbose_name="需求标题")),
                ("description", models.TextField(blank=True, default="", verbose_name="需求描述")),
                ("business_value", models.TextField(blank=True, default="", verbose_name="业务价值")),
                ("acceptance_criteria", models.TextField(blank=True, default="", verbose_name="验收标准")),
                ("type", models.CharField(db_index=True, default="", max_length=64, verbose_name="需求类型")),
                ("source", models.CharField(db_index=True, default="", max_length=64, verbose_name="需求来源")),
                ("priority", models.CharField(db_index=True, default="medium", max_length=32, verbose_name="优先级")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("submitted", "待评审"),
                            ("need_info", "待补充"),
                            ("accepted", "已接纳"),
                            ("planned", "已排期"),
                            ("in_dev", "开发中"),
                            ("in_acceptance", "待验收"),
                            ("done", "已完成"),
                            ("rejected", "已拒绝"),
                            ("archived", "已归档"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                ("attachments", models.JSONField(blank=True, default=list, verbose_name="附件文件ID列表")),
                ("review_due_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="评审截止时间")),
                ("dev_due_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="开发截止时间")),
                ("is_review_overdue", models.BooleanField(db_index=True, default=False, verbose_name="评审是否超时")),
                ("is_dev_overdue", models.BooleanField(db_index=True, default=False, verbose_name="开发是否超时")),
                ("submitted_at", models.DateTimeField(blank=True, null=True, verbose_name="提交时间")),
                ("accepted_at", models.DateTimeField(blank=True, null=True, verbose_name="接纳时间")),
                ("planned_at", models.DateTimeField(blank=True, null=True, verbose_name="排期时间")),
                ("dev_started_at", models.DateTimeField(blank=True, null=True, verbose_name="开发开始时间")),
                ("done_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_requirements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="责任人",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewing_requirements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评审人",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_requirements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提单人",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "需求单",
                "verbose_name_plural": "需求单",
                "db_table": "rc_requirement",
            },
        ),
        migrations.CreateModel(
            name="RequirementComment",
            fields=[
                ("id", models.CharField(default=uuid.uuid4, editable=False, help_text="主键ID", max_length=36, primary_key=True, serialize=False)),
                ("sys_create_datetime", models.DateTimeField(auto_now_add=True, db_index=True, help_text="创建时间")),
                ("sys_update_datetime", models.DateTimeField(auto_now=True, db_index=True, help_text="更新时间")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, help_text="是否删除（软删除标识）")),
                ("sort", models.IntegerField(db_index=True, default=0, help_text="排序（数字越大越靠前）")),
                ("content", models.TextField(verbose_name="评论内容")),
                ("mentions", models.JSONField(blank=True, default=list, verbose_name="@用户ID列表")),
                (
                    "commenter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requirement_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评论人",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="requirement_center.requirement",
                        verbose_name="所属需求",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "需求评论",
                "verbose_name_plural": "需求评论",
                "db_table": "rc_requirement_comment",
            },
        ),
        migrations.CreateModel(
            name="RequirementLog",
            fields=[
                ("id", models.CharField(default=uuid.uuid4, editable=False, help_text="主键ID", max_length=36, primary_key=True, serialize=False)),
                ("sys_create_datetime", models.DateTimeField(auto_now_add=True, db_index=True, help_text="创建时间")),
                ("sys_update_datetime", models.DateTimeField(auto_now=True, db_index=True, help_text="更新时间")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, help_text="是否删除（软删除标识）")),
                ("sort", models.IntegerField(db_index=True, default=0, help_text="排序（数字越大越靠前）")),
                ("action", models.CharField(db_index=True, max_length=64, verbose_name="操作动作")),
                ("from_status", models.CharField(blank=True, default="", max_length=32, verbose_name="变更前状态")),
                ("to_status", models.CharField(blank=True, default="", max_length=32, verbose_name="变更后状态")),
                ("note", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requirement_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="requirement_center.requirement",
                        verbose_name="所属需求",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "需求日志",
                "verbose_name_plural": "需求日志",
                "db_table": "rc_requirement_log",
            },
        ),
        migrations.CreateModel(
            name="RequirementWatcher",
            fields=[
                ("id", models.CharField(default=uuid.uuid4, editable=False, help_text="主键ID", max_length=36, primary_key=True, serialize=False)),
                ("sys_create_datetime", models.DateTimeField(auto_now_add=True, db_index=True, help_text="创建时间")),
                ("sys_update_datetime", models.DateTimeField(auto_now=True, db_index=True, help_text="更新时间")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, help_text="是否删除（软删除标识）")),
                ("sort", models.IntegerField(db_index=True, default=0, help_text="排序（数字越大越靠前）")),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchers",
                        to="requirement_center.requirement",
                        verbose_name="所属需求",
                    ),
                ),
                (
                    "sys_creator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sys_modifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="修改人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watching_requirements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关注用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "需求关注人",
                "verbose_name_plural": "需求关注人",
                "db_table": "rc_requirement_watcher",
                "unique_together": {("requirement", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="requirement",
            index=models.Index(fields=["status", "priority", "sys_create_datetime"], name="idx_rc_req_status_pri_ct"),
        ),
        migrations.AddIndex(
            model_name="requirement",
            index=models.Index(fields=["reviewer", "status"], name="idx_rc_req_reviewer_status"),
        ),
        migrations.AddIndex(
            model_name="requirement",
            index=models.Index(fields=["owner", "status"], name="idx_rc_req_owner_status"),
        ),
        migrations.AddIndex(
            model_name="requirement",
            index=models.Index(fields=["is_review_overdue", "is_dev_overdue"], name="idx_rc_req_overdue"),
        ),
        migrations.AddIndex(
            model_name="requirementcomment",
            index=models.Index(fields=["requirement", "sys_create_datetime"], name="idx_rc_req_comment_req_time"),
        ),
        migrations.AddIndex(
            model_name="requirementlog",
            index=models.Index(fields=["requirement", "sys_create_datetime"], name="idx_rc_req_log_req_time"),
        ),
        migrations.AddIndex(
            model_name="requirementlog",
            index=models.Index(fields=["action", "sys_create_datetime"], name="idx_rc_req_log_action_time"),
        ),
        migrations.AddIndex(
            model_name="requirementwatcher",
            index=models.Index(fields=["user", "sys_create_datetime"], name="idx_rc_req_watch_user_time"),
        ),
    ]
