# Generated by Django 5.2.7 on 2026-03-04

from django.db import migrations


def seed_requirement_dicts(apps, schema_editor):
    Dict = apps.get_model("core", "Dict")
    DictItem = apps.get_model("core", "DictItem")

    dict_groups = [
        {
            "name": "需求类型",
            "code": "requirement_type",
            "remark": "需求管理模块-需求类型",
            "items": [
                {"label": "功能需求", "value": "feature", "sort": 40},
                {"label": "优化需求", "value": "improvement", "sort": 30},
                {"label": "缺陷修复", "value": "bugfix", "sort": 20},
            ],
        },
        {
            "name": "需求来源",
            "code": "requirement_source",
            "remark": "需求管理模块-需求来源",
            "items": [
                {"label": "业务方", "value": "biz", "sort": 40},
                {"label": "客户反馈", "value": "customer", "sort": 30},
                {"label": "内部改进", "value": "internal", "sort": 20},
            ],
        },
        {
            "name": "需求优先级",
            "code": "requirement_priority",
            "remark": "需求管理模块-需求优先级",
            "items": [
                {"label": "低", "value": "low", "sort": 40},
                {"label": "中", "value": "medium", "sort": 30},
                {"label": "高", "value": "high", "sort": 20},
                {"label": "紧急", "value": "urgent", "sort": 10},
            ],
        },
    ]

    for group in dict_groups:
        dict_obj, _ = Dict.objects.update_or_create(
            code=group["code"],
            defaults={
                "name": group["name"],
                "status": True,
                "remark": group["remark"],
            },
        )

        for item in group["items"]:
            DictItem.objects.update_or_create(
                dict=dict_obj,
                value=item["value"],
                defaults={
                    "label": item["label"],
                    "status": True,
                    "sort": item["sort"],
                    "remark": f"{group['name']}选项",
                },
            )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_announcement_usermessage"),
        ("requirement_center", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_requirement_dicts, migrations.RunPython.noop),
    ]
