# Generated by Django 5.0.1 on 2026-03-04

from collections import defaultdict

import django.db.models.deletion
from django.db import migrations, models


def rebuild_tree_meta(apps, schema_editor):
    Requirement = apps.get_model("requirement_center", "Requirement")
    db_alias = schema_editor.connection.alias

    nodes = list(
        Requirement.objects.using(db_alias)
        .filter(is_deleted=False)
        .values("id", "parent_id")
    )
    if not nodes:
        return

    parent_map = {}
    for item in nodes:
        node_id = str(item["id"])
        parent_id = str(item["parent_id"]) if item.get("parent_id") else None
        parent_map[node_id] = parent_id

    node_ids = set(parent_map.keys())
    children_map = defaultdict(list)
    for node_id, parent_id in parent_map.items():
        if parent_id and parent_id in node_ids and parent_id != node_id:
            children_map[parent_id].append(node_id)
        else:
            children_map[None].append(node_id)
            parent_map[node_id] = None

    visited = set()
    updates = {}

    def walk(node_id: str, root_id: str, level: int, path: str):
        if node_id in visited:
            return
        visited.add(node_id)

        children = children_map.get(node_id, [])
        updates[node_id] = {
            "child_count": len(children),
            "is_leaf": len(children) == 0,
            "level": level,
            "root_id": root_id,
            "tree_path": path,
        }
        for child_id in children:
            walk(child_id, root_id, level + 1, f"{path}{child_id}/")

    for root_id in children_map.get(None, []):
        walk(root_id, root_id, 0, f"/{root_id}/")

    for node_id in node_ids:
        if node_id in visited:
            continue
        parent_map[node_id] = None
        walk(node_id, node_id, 0, f"/{node_id}/")

    for node_id, item in updates.items():
        Requirement.objects.using(db_alias).filter(id=node_id).update(
            parent_id=parent_map.get(node_id),
            root_id=item["root_id"],
            level=item["level"],
            tree_path=item["tree_path"],
            child_count=item["child_count"],
            is_leaf=item["is_leaf"],
        )


class Migration(migrations.Migration):
    dependencies = [
        ("requirement_center", "0002_seed_requirement_dicts"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirement",
            name="child_count",
            field=models.PositiveIntegerField(default=0, verbose_name="直接子需求数量"),
        ),
        migrations.AddField(
            model_name="requirement",
            name="is_leaf",
            field=models.BooleanField(db_index=True, default=True, verbose_name="是否叶子节点"),
        ),
        migrations.AddField(
            model_name="requirement",
            name="level",
            field=models.PositiveIntegerField(default=0, verbose_name="树层级"),
        ),
        migrations.AddField(
            model_name="requirement",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="requirement_center.requirement",
                verbose_name="父需求",
            ),
        ),
        migrations.AddField(
            model_name="requirement",
            name="root_id",
            field=models.CharField(db_index=True, default="", max_length=36, verbose_name="根需求ID"),
        ),
        migrations.AddField(
            model_name="requirement",
            name="tree_path",
            field=models.CharField(db_index=True, default="", max_length=700, verbose_name="树路径"),
        ),
        migrations.AddIndex(
            model_name="requirement",
            index=models.Index(fields=["parent", "sort"], name="idx_rc_req_parent_sort"),
        ),
        migrations.AddIndex(
            model_name="requirement",
            index=models.Index(fields=["root_id", "tree_path"], name="idx_rc_req_root_path"),
        ),
        migrations.AddIndex(
            model_name="requirement",
            index=models.Index(fields=["is_leaf", "status"], name="idx_rc_req_leaf_status"),
        ),
        migrations.AddConstraint(
            model_name="requirement",
            constraint=models.CheckConstraint(
                check=models.Q(parent__isnull=True) | ~models.Q(id=models.F("parent_id")),
                name="ck_rc_req_parent_not_self",
            ),
        ),
        migrations.RunPython(rebuild_tree_meta, migrations.RunPython.noop),
    ]
