# Generated by Django 5.2.7 on 2025-12-25 23:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_user_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceIndicator',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('code', models.CharField(blank=True, help_text='业务唯一标识', max_length=100, null=True, unique=True, verbose_name='业务唯一标识')),
                ('name', models.CharField(help_text='指标名称', max_length=255, verbose_name='指标名称')),
                ('module', models.CharField(help_text='所属模块', max_length=100, verbose_name='所属模块')),
                ('project', models.CharField(help_text='所属项目', max_length=100, verbose_name='所属项目')),
                ('chip_type', models.CharField(help_text='芯片类型', max_length=100, verbose_name='芯片类型')),
                ('value_type', models.CharField(choices=[('avg', '平均值'), ('min', '最小值'), ('max', '最大值')], default='avg', help_text='值类型', max_length=20, verbose_name='值类型')),
                ('baseline_value', models.FloatField(help_text='基线值', verbose_name='基线值')),
                ('baseline_unit', models.CharField(help_text='单位', max_length=50, verbose_name='单位')),
                ('fluctuation_range', models.FloatField(help_text='允许浮动范围', verbose_name='允许浮动范围')),
                ('fluctuation_direction', models.CharField(choices=[('up', '越大越好'), ('down', '越小越好'), ('none', '无方向')], default='none', help_text='浮动方向', max_length=20, verbose_name='浮动方向')),
                ('owner', models.CharField(blank=True, help_text='责任人', max_length=100, null=True, verbose_name='责任人')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '性能指标',
                'verbose_name_plural': '性能指标',
                'db_table': 'performance_indicator',
                'ordering': ['-sys_create_datetime'],
                'unique_together': {('project', 'module', 'chip_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceIndicatorData',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('date', models.DateField(help_text='测试日期', verbose_name='测试日期')),
                ('value', models.FloatField(help_text='具体测试值', verbose_name='具体测试值')),
                ('fluctuation_value', models.FloatField(help_text='浮动差值', verbose_name='浮动差值')),
                ('indicator', models.ForeignKey(help_text='指标', on_delete=django.db.models.deletion.CASCADE, related_name='data', to='performance.performanceindicator', verbose_name='指标')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '性能数据',
                'verbose_name_plural': '性能数据',
                'db_table': 'performance_indicator_data',
                'ordering': ['-date'],
                'unique_together': {('indicator', 'date')},
            },
        ),
    ]
