# Generated by Django 5.2.7 on 2025-12-28 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_manager'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceindicator',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='责任人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_indicators', to='core.user', verbose_name='责任人'),
        ),
    ]
