# Generated by Django 5.2.7 on 2026-01-22 23:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_manager'),
        ('performance', '0004_add_indicator_import_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceRiskRecord',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='主键ID', max_length=36, primary_key=True, serialize=False)),
                ('sys_create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('sys_update_datetime', models.DateTimeField(auto_now=True, db_index=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否删除（软删除标识）')),
                ('sort', models.IntegerField(db_index=True, default=0, help_text='排序（数字越大越靠前）')),
                ('occur_date', models.DateField(help_text='发生日期', verbose_name='发生日期')),
                ('status', models.CharField(choices=[('open', '未处理'), ('ack', '已确认'), ('resolved', '已解决')], default='open', help_text='状态', max_length=20, verbose_name='状态')),
                ('baseline_value', models.FloatField(help_text='基线值', verbose_name='基线值')),
                ('measured_value', models.FloatField(help_text='测量值', verbose_name='测量值')),
                ('deviation_value', models.FloatField(help_text='偏差值', verbose_name='偏差值')),
                ('allowed_range', models.FloatField(help_text='允许浮动范围', verbose_name='允许浮动范围')),
                ('direction', models.CharField(help_text='浮动方向', max_length=20, verbose_name='浮动方向')),
                ('message', models.CharField(blank=True, default='', help_text='说明', max_length=500, verbose_name='说明')),
                ('data', models.ForeignKey(help_text='数据', on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='performance.performanceindicatordata', verbose_name='数据')),
                ('indicator', models.ForeignKey(help_text='指标', on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='performance.performanceindicator', verbose_name='指标')),
                ('owner', models.ForeignKey(blank=True, help_text='责任人', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user', verbose_name='责任人')),
                ('sys_creator', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to='core.user')),
                ('sys_modifier', models.ForeignKey(blank=True, db_constraint=False, help_text='修改人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to='core.user')),
            ],
            options={
                'verbose_name': '性能风险',
                'verbose_name_plural': '性能风险',
                'db_table': 'performance_risk_record',
                'ordering': ['-sys_create_datetime'],
                'indexes': [models.Index(fields=['indicator'], name='performance_indicat_56e895_idx'), models.Index(fields=['status'], name='performance_status_31cffe_idx'), models.Index(fields=['occur_date'], name='performance_occur_d_4f70f2_idx')],
                'unique_together': {('indicator', 'data')},
            },
        ),
    ]
