# Generated by Django 5.2.7 on 2026-01-23 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_manager'),
        ('performance', '0005_performanceriskrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceriskrecord',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='确认时间', null=True, verbose_name='确认时间'),
        ),
        migrations.AddField(
            model_name='performanceriskrecord',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, help_text='确认人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_confirmed_risks', to='core.user', verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='performanceriskrecord',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='解决时间', null=True, verbose_name='解决时间'),
        ),
    ]
