"""
框架安全知识模块

包含各种框架的安全特性和常见漏洞模式
"""

from .fastapi import FASTAPI_SECURITY
from .django import DJANGO_SECURITY
from .flask import FLASK_SECURITY
from .express import EXPRESS_SECURITY
from .react import REACT_SECURITY
from .supabase import SUPABASE_SECURITY
from .android_component_security import ANDROID_COMPONENT_SECURITY
from .android_binder_system_service_security import ANDROID_BINDER_SYSTEM_SERVICE_SECURITY
from .android_crypto_network_security import ANDROID_CRYPTO_NETWORK_SECURITY
from .android_hmi_display_state import ANDROID_HMI_DISPLAY_STATE
from .android_intent_pendingintent_security import ANDROID_INTENT_PENDINGINTENT_SECURITY
from .android_ipc_binder_security import ANDROID_IPC_BINDER_SECURITY
from .android_jni_native_boundary import ANDROID_JNI_NATIVE_BOUNDARY
from .android_ota_update_security import ANDROID_OTA_UPDATE_SECURITY
from .android_privapp_platform_security import ANDROID_PRIVAPP_PLATFORM_SECURITY
from .android_storage_log_privacy import ANDROID_STORAGE_LOG_PRIVACY
from .android_vehicle_diagnostics_security import ANDROID_VEHICLE_DIAGNOSTICS_SECURITY
from .android_vehicle_hal_car_service_security import ANDROID_VEHICLE_HAL_CAR_SERVICE_SECURITY
from .android_webview_jsbridge_security import ANDROID_WEBVIEW_JSBRIDGE_SECURITY
from .java_parser_serialization_security import JAVA_PARSER_SERIALIZATION_SECURITY
from .java_runtime_reflection_security import JAVA_RUNTIME_REFLECTION_SECURITY

# 所有框架知识文档
ALL_FRAMEWORK_DOCS = [
    FASTAPI_SECURITY,
    DJANGO_SECURITY,
    FLASK_SECURITY,
    EXPRESS_SECURITY,
    REACT_SECURITY,
    SUPABASE_SECURITY,
    ANDROID_COMPONENT_SECURITY,
    ANDROID_IPC_BINDER_SECURITY,
    ANDROID_BINDER_SYSTEM_SERVICE_SECURITY,
    ANDROID_INTENT_PENDINGINTENT_SECURITY,
    ANDROID_WEBVIEW_JSBRIDGE_SECURITY,
    ANDROID_STORAGE_LOG_PRIVACY,
    ANDROID_JNI_NATIVE_BOUNDARY,
    ANDROID_HMI_DISPLAY_STATE,
    ANDROID_CRYPTO_NETWORK_SECURITY,
    ANDROID_PRIVAPP_PLATFORM_SECURITY,
    ANDROID_VEHICLE_DIAGNOSTICS_SECURITY,
    ANDROID_OTA_UPDATE_SECURITY,
    ANDROID_VEHICLE_HAL_CAR_SERVICE_SECURITY,
    JAVA_RUNTIME_REFLECTION_SECURITY,
    JAVA_PARSER_SERIALIZATION_SECURITY,
]

__all__ = [
    "ALL_FRAMEWORK_DOCS",
    "FASTAPI_SECURITY",
    "DJANGO_SECURITY",
    "FLASK_SECURITY",
    "EXPRESS_SECURITY",
    "REACT_SECURITY",
    "SUPABASE_SECURITY",
    "ANDROID_COMPONENT_SECURITY",
    "ANDROID_BINDER_SYSTEM_SERVICE_SECURITY",
    "ANDROID_CRYPTO_NETWORK_SECURITY",
    "ANDROID_HMI_DISPLAY_STATE",
    "ANDROID_INTENT_PENDINGINTENT_SECURITY",
    "ANDROID_IPC_BINDER_SECURITY",
    "ANDROID_JNI_NATIVE_BOUNDARY",
    "ANDROID_OTA_UPDATE_SECURITY",
    "ANDROID_PRIVAPP_PLATFORM_SECURITY",
    "ANDROID_STORAGE_LOG_PRIVACY",
    "ANDROID_VEHICLE_DIAGNOSTICS_SECURITY",
    "ANDROID_VEHICLE_HAL_CAR_SERVICE_SECURITY",
    "ANDROID_WEBVIEW_JSBRIDGE_SECURITY",
    "JAVA_PARSER_SERIALIZATION_SECURITY",
    "JAVA_RUNTIME_REFLECTION_SECURITY",
]
